2주차 2번과제 제출합니다!
CodeSoom/week2-assignment-2 pull request #1
Opened 2020-06-08 01:19 UTC by eonsang

2020-06-08 12:34 UTC, wholemann requested changes

2020-06-08 12:34 UTC, wholemann commented on src/TodoList.jsx
> +  );
이 컴포넌트를 사용하는 입장에서 TodoList 의 UI를 예상하고 들어왔을텐데
실제로 그 정보는 보이지 않습니다.

TodoListNotEmpty는 비어있지 않은 리스트인가요?
리스트가 비어있을 때와 비어있지 않을 때 전혀 다른 리스트인지 생각해보면 좋겠죠?

2020-06-08 12:34 UTC, wholemann commented on src/TodoListForm.jsx
> +      <input type="text" value={input} onChange={onChange} />
placeholder도 하나 넣어주면 어떨까요?

2020-06-08 12:34 UTC, wholemann commented on src/TodoListItem.jsx
> +      <button type="button" style={{ marginLeft: '10px' }} onClick={onClick}>완료</button>
const style로 따로 빼주는 것도 좋아보입니다.

2020-06-08 12:34 UTC, wholemann commented on src/index.jsx
> +  const [input, setInput] = useState('');
상태가 늘어날수록 useState 호출이 계속 늘어날 겁니다.
어떻게 하면 이 부분을 깔끔하게 바꿀 수 있을까요?

2020-06-08 12:34 UTC, wholemann commented on src/index.jsx
> +  const handleAddTodoList = () => {
Click 이벤트에 대한 핸들러 함수이니 handleClick~ 으로 시작하는 게 적절해보입니다.
그리고 Todo를 하나 추가하는 것이니 뒤에 List가 붙는 건 조금 이상하지 않을까요?

2020-06-08 12:34 UTC, wholemann commented on src/index.jsx
> +  const [todoListLength, setTodoListLength] = useState(0);
길이를 상태로 둬야 하는 이유가 있을까요?

2020-06-08 12:34 UTC, wholemann commented on src/index.jsx
> +    setInput(e.target.value);
위의 피드백을 반영한다면 이 부분도 아주 간략하게 변할 수 있을 겁니다ㅎㅎ

2020-06-09 23:13 UTC, wholemann requested changes
상태관리를 Todo로 옮기셨는데 그렇다면 지금 굳이 App이 필요할까요?

이전 과제를 생각해보시면 올바른 파일 분리를 생각해보실 수 있을 겁니다:)

2020-06-09 23:13 UTC, wholemann commented on src/TodoList.jsx
> +        list.map((item) => (
어떤 list인가요? 변수명이 어떤 자료들을 담고 있는지 충분히 설명하고 있지 않습니다.

또한 조건식은 명확하게 써주는 게 좋을 듯 합니다.

2020-06-09 23:13 UTC, wholemann commented on src/Todo.jsx
> +    };
resetInput이 굳이 필요한진 모르겠네요ㅎㅎ

그냥 클릭이 될 때마다 ...state, input: '', 을 setState해주면

input 컴포넌트를 공백으로 만들 방법이 있습니다. 연구해보세요:)

2020-06-09 23:13 UTC, wholemann commented on src/Todo.jsx
> +  const handleInput = (e) => {
handleChangeInput이 일관성 있고 적절하겠네요.

2020-06-09 23:13 UTC, wholemann commented on src/Todo.jsx
> +      <TodoListForm input={input} onChange={handleInput} onClick={handleClickAddTodo} />
onChangeInput과 같이 명확하게 써주는 게 좋겠습니다.
onClick은 뒤에 무엇이 붙으면 좋을까요?

2020-06-11 12:00 UTC, wholemann requested changes
거의 다 오신 듯 하네요.

몇 가지 아쉬운 부분 comment 남겨드렸습니다.

잘 생각해보시고 궁금하신 점은 DM주세요!

2020-06-11 12:00 UTC, wholemann commented on src/components/TodoItem.jsx
> +export default function TodoItem({ item, onClicktoRemove }) {
매개변수에서 item을 구조분해 할당 하는 방법이 있겠군요.

onClicktoRemove에서 to는 빠져도 좋을 것 같네요.

2020-06-11 12:00 UTC, wholemann commented on src/index.jsx
> +}
앱은 따로 컴포넌트로 뺍니다.

강의를 보시면 아시겠지만 최상위 컴포넌트인 App에서 상태관리를 하는 걸 볼 수 있습니다. 강의를 복습해주세요.

관심사의 분리에 대해서 고민해보셔요!

2020-06-11 12:00 UTC, wholemann commented on src/pages/Todo.jsx
> +  const handleClickAddTodo = () => {
Submit 이벤트에 대한 핸들러 함수에서 호출되는 함수인데

이 함수 표현도 Click 이벤트에 대한 핸들러로 표현되고 있습니다.

어떻게 정리해야 할까요?

2020-06-11 12:00 UTC, wholemann commented on src/pages/Todo.jsx
> +    }
이전 상태에서 id를 취해오고 있습니다. 어떤 문제가 생길 수 있을까요?

표현하고자 했던 바는 마지막 id에 +1씩 더해서 다음 id를 만들 때 사용하려던 것임을 잊어선 안 됩니다.

2020-06-11 12:00 UTC, wholemann commented on src/pages/Todo.jsx
> +        onClickSubmitButton={handleClickAddTodo}
Click인지 Submit인지 햇갈립니다!

2020-06-12 01:01 UTC, wholemann requested changes
마지막으로 아쉬운 부분 1개 comment 드렸습니다ㅎㅎ

2020-06-12 01:01 UTC, wholemann commented on src/index.jsx
> +        id: prevState.id + 1,
굳이 prevState를 얻어올 필요 없이 상단에 id가 있으므로 id + 1이면 되지 않을까요?

2020-06-12 13:05 UTC, wholemann requested changes

2020-06-12 13:05 UTC, wholemann commented on src/components/TodoItem.jsx
> +function TodoItem({ item, onClickRemove }) {
TodoItem({ id, text}, onClickRemove })으로 변경하면 밑에서 구조분해 할당을 할 필요가 없겠네요.

2020-06-12 13:05 UTC, wholemann commented on src/App.jsx
> +        ...state,
`...state`는 언제 필요한 걸까요?

2020-06-12 13:49 UTC, eonsang commented on src/App.jsx
> +        ...state,
> `...state`는 언제 필요한 걸까요?

`todoList, input, id`를 가지는 하나의 `state`로 작성했습니다.
그러다보니 state중 하나를 변경할때마다 기존 값들은 그대로 유지할수 있도록 `...state`를 넣어뒀습니다!

ex. input 값을 변경하고 싶을때, setState 함수가 실행될때마다 기존 todoList, id 값은 그대로 유지
```
const [state, setState] = useState({
    todoList: [],
    input: '',
    id: 0,
  });
  const { todoList, input } = state;

  const handleChangeInput = ({ target: { value } }) => {
    setState({
      ...state,
      input: value,
    });
  };
```

체크해주신걸 다시 한번 생각해보니 뭔가 불필요한거같아서 
todoList, input, id를 각각의  state로 변경했습니다!
```
  const [todoList, setTodoList] = useState([]);
  const [input, setInput] = useState('');
  const [nextId, setNextId] = useState(0);
```

다만 걸리는게 처음에 저런식으로 나눠서 state를 만들었을때 주신 [피드백](https://github.com/CodeSoom/week2-assignment-2/pull/1#discussion_r436656307)에 대한 해답은 아직 찾지 못했습니다 ㅠㅠㅠ 좀 더 고민해보겠습니다!

2020-06-12 23:28 UTC, wholemann requested changes
피드백에 오해가 있었군요.

해당 부분에서는 `...state` 이 필요가 없었습니다.

3가지 상태를 모두 명시적으로 변경했으니까요.

보통 부분적으로 객체의 속성을 갱신해야될 필요가 있을 때

펼침 연산자를 사용합니다. 이전으로 돌아가셔도 좋습니다.

제가 조언드리고 싶었던 부분은 '왜?' 쓰는지에 대한 고민없이

관성적으로 `...state`를 하신 것 같아서 말씀드렸어요🙏

2020-06-12 23:28 UTC, wholemann commented on src/App.jsx
> +  const [nextId, setNextId] = useState(0);
이 부분을 바꾸라는 얘기가 아니었어요~

이런 부분은 하나의 객체로 상태 관리하는 게 좋습니다.

2020-06-14 07:57 UTC, wholemann approved these changes
Page는 명시적으로 TodoPage와 같이 드러내주는 게 좋아 보입니다.

그 외에는 아주 잘해주셔서 이 과제는 Merge하겠습니다.

이후 아샬님의 피드백 강의를 참고하시면 와닿는 부분들이 있으실 겁니다.
잘 소화해내시길 바라겠습니다:)

고생하셨습니다!

2020-06-14 07:57 UTC, merged