ToDo-List
CodeSoom/week2-assignment-2 pull request #11
Opened 2020-06-11 08:46 UTC by kc7851

컴포넌트를 분리하여 ToDo List를 만들었습니다.

root 컴포넌트에서 상태와 함수를 관리하도록 구성하였습니다.

2020-06-11 11:20 UTC, wholemann requested changes

2020-06-11 11:20 UTC, wholemann commented on src/App.jsx
> +    toDos: [],
Do만 왜 갑자기 대문자인가요ㅋㅋㅋ todos가 좋겠네요.

2020-06-11 11:20 UTC, wholemann commented on src/App.jsx
> +  }
이 부분의 의도를 읽기가 힘드네요. 새로운 아이디를 만들어 내는 곳인데 좀 더 단순한 표현이 가능할 것 같습니다.

2020-06-11 11:20 UTC, wholemann commented on src/App.jsx
> +  function handleInputText(event) {
handleChange겠죠? 어떤 이벤트에 대한 핸들러인지 표현되면 좋겠네요.

2020-06-11 11:20 UTC, wholemann commented on src/App.jsx
> +      handleInputText={handleInputText}
이벤트에 대한 표현이 추가되면 좋겠습니다.

2020-06-11 11:20 UTC, wholemann commented on src/Main.jsx
> +function Main({
메인은 어떤 걸 뜻하나요? 이 컴포넌트가 무엇인지 표현되면 좋겠네요.

Page인가요 컴포넌트인가요?

2020-06-11 11:20 UTC, wholemann commented on src/TodoList.jsx
> +                  key={id}
todo.id가 가능하겠네요. 상단에 굳이 변수 선언 및 할당이 필요해보이진 않습니다.

2020-06-11 11:20 UTC, wholemann commented on src/Task.jsx
> +function Task({ toDo, handleDeleteTask }) {
{ { id, task }, handleDeleteTask } 로 구조분해 할당을 인자에서 해버리면
변수 선언을 줄일 수 있습니다.

2020-06-11 13:14 UTC, kc7851 commented on src/App.jsx
> +    toDos: [],
흠.. todo로 했다가 실제로 To와 Do는 다른 단어라서 toDo로 바꾼거였는데, todos가 더 나을까요 ㅋㅋ

2020-06-11 13:16 UTC, kc7851 commented on src/App.jsx
> +  }
리스트중에서 가장 큰 id값을 찾아서 +1을 하는 부분인데, max같은 함수를 사용하는게 더 좋을까요?

2020-06-11 13:19 UTC, kc7851 commented on src/App.jsx
> +      handleInputText={handleInputText}
음.. 잘 이해가 안됐습니다. 어떤 식으로 표현하면 될까요?

2020-06-11 13:21 UTC, kc7851 commented on src/Main.jsx
> +function Main({
MainPage를 생각하고 만들긴 했습니다.

2020-06-11 13:22 UTC, kc7851 commented on src/TodoList.jsx
> +                  key={id}
두개 이상 사용하지 않으면 그냥 바로 사용하는게 더 좋을까요? 이 부분 좀 애매해서 명확한 기준이 없네요.

2020-06-11 13:22 UTC, kc7851 commented on src/Task.jsx
> +function Task({ toDo, handleDeleteTask }) {
오 이렇게 수정하겠습니다~

2020-06-12 01:03 UTC, wholemann requested changes

2020-06-12 01:03 UTC, wholemann commented on src/TodoList.jsx
> +                  key={id}
네 보통 그렇죠ㅎㅎ

2020-06-13 00:34 UTC, wholemann commented on src/App.jsx
> +    toDos: [],
요즘은 사실상 한 단어로 쓰이고 있죠ㅎㅎ

2020-06-13 00:34 UTC, wholemann commented on src/App.jsx
> +  }
네 그게 표현력은 훨씬 좋겠네요.

2020-06-13 00:35 UTC, wholemann commented on src/App.jsx
> +      handleInputText={handleInputText}
handleClick

handleChange 등이 있겠죠?

2020-06-13 06:38 UTC, kc7851 commented on src/App.jsx
> +    toDos: [],
넵 todos로 고고하겠습니다 ㅎㅎ

2020-06-13 09:30 UTC, kc7851 commented on src/Task.jsx
> +function Task({ toDo, handleDeleteTask }) {
![스크린샷 2020-06-13 오후 6 28 44](https://user-images.githubusercontent.com/29528994/84565396-d00cdd80-ada3-11ea-84b7-c09bab9900de.png)

이렇게 하니 이런 오류가 발생하는데 어떻게 하면 될까요?

2020-06-13 11:29 UTC, wholemann commented on src/Task.jsx
> +function Task({ toDo, handleDeleteTask }) {
오우 제가 실수했네요.

{ todo: { id, task}, handleClickDeleteTask } 로 하셔야 합니다.

객체엔 순서 개념이 없기에...ㅎㅎ

2020-06-13 11:31 UTC, wholemann requested changes
거의 다 오셨네요ㅎㅎ 다음 PR 기다리겠습니다!

2020-06-13 11:31 UTC, wholemann commented on src/App.jsx
> +      state={state}
state를 2개의 prop으로 각각 나누어 보내는 건 어떨까요?

2020-06-13 11:31 UTC, wholemann commented on src/Task.jsx
> +function Task({ todo, handleClickDeleteTask }) {
답변 드린대로라면 이부분 구조분해 할당 가능할 겁니다.

2020-06-14 01:51 UTC, wholemann approved these changes
훌륭히 잘해주셨습니다ㅎㅎ 이 과제는 Merge할게용.

다음주에도 화이팅입니다!!!

2020-06-14 01:51 UTC, merged

2020-06-14 08:04 UTC, kc7851 commented
고생하셨습니다!!