Simple TodoList V1
CodeSoom/week2-assignment-2 pull request #13
Opened 2020-06-11 10:32 UTC by SeaFalcon

리뷰 요청드립니다!

제가 뭘 모르는지(?) 모르는 상태라 질문할 게 없네요 ㅠㅠ
아직 첫번째 과제 통과 전이라 첫번째 과제에서 피드백을 받게되면 여기에도 적용할 수 있을 것 같습니다.

2020-06-11 11:36 UTC, hannut91 requested changes

2020-06-11 11:36 UTC, hannut91 commented on src/Component/App.jsx
> +    tempArray.splice(items.indexOf(item), 1);
자바스크립트의 `splice`는 해당 배열을 직접 고치게 되어서 어떻게 동작할지 예측하기가 매우 어렵게 됩니다. 원본 배열을 건드리지 않으면서 원하는 목표를 이루려면 어떻게 해야 할까요?

지금 우리는 리스트 중에서 해당 id를 가지고 있는 애를 제외하고 싶은거죠?

2020-06-11 11:36 UTC, hannut91 commented on src/Component/Todo.jsx
> +    ))
여러개를 반환하고 있는데 컴포넌트의 이름은 `Todo`네요. 이 처리를 `TodoList`에서 처리해주는건 어떨까요?

2020-06-11 11:36 UTC, hannut91 commented on src/Component/App.jsx
> +    tempArray.push({ id: items.length + 1, value: text });
변수 이름에 `temp`와 자료형 `Array`를 사용하는건 좋지 않아요. 그리고 만약 
[1, 2, 3]이 있었는데 2를 삭제하여 
[1, 3,]이 되고 이 상태에서 todo하나를 추가하면
[1, 3, 3]이 되어서 아이디가 겹치지 않나요?

2020-06-11 14:04 UTC, SeaFalcon commented on src/Component/App.jsx
> +    tempArray.splice(items.indexOf(item), 1);
좋은 피드백입니다 ㅠ_ㅠ

"테스트만 통과하자!" 라는 마음가짐으로 인해 나온 결과물이에요
그래도 말씀안해주셨으면 아마 몰랐을 것 같습니다.

원본 배열을 건드리지 않으려면 배열을 복사해서 쓰면 될 것 같아요

2020-06-11 14:05 UTC, SeaFalcon commented on src/Component/Todo.jsx
> +    ))
> 여러개를 반환하고 있는데 컴포넌트의 이름은 `Todo`네요. 이 처리를 `TodoList`에서 처리해주는건 어떨까요?

그렇다면, TodoList에서 직접 처리하는것
Todo의 컴포넌트 명을 Todos로 바꾸는 것 이렇게 두 가지 방식이 가능할까요?

2020-06-11 14:07 UTC, hannut91 commented on src/Component/Todo.jsx
> +    ))
`TodoList`에서 이 처리를 담당해야 할 것 같아요.

2020-06-11 14:38 UTC, SeaFalcon commented on src/Component/App.jsx
> +    tempArray.push({ id: items.length + 1, value: text });
앗 그러네요.. 
마땅히 좋은 방법이 떠오르지 않아서
지적해주신 부분만 해결되도록 일단 수정은 했는데
확신이 없네요 ㅎㅎ...

2020-06-11 14:42 UTC, SeaFalcon commented on src/Component/Todo.jsx
> +    ))
> `TodoList`에서 이 처리를 담당해야 할 것 같아요.

그 이유는 과제 1과 마찬가지로 <Todo> 컴포넌트 자체가 하는 일이 없기 때문일까요?

2020-06-11 14:43 UTC, hannut91 commented on src/Component/Todo.jsx
> +    ))
아니요 투두 목록을 처리하는 것을 `TodoList`가 하는게 맞는 것 같아서요 ㅎㅎ

2020-06-11 14:50 UTC, SeaFalcon commented on src/Component/App.jsx
> +    tempArray.push({ id: items.length + 1, value: text });
댓글이 지워졌네요;
말씀하신 부분만 '일단' 개선하여 푸쉬하였습니다 ㅠㅠ

2020-06-11 14:50 UTC, SeaFalcon commented on src/Component/Todo.jsx
> +    ))
> 아니요 투두 목록을 처리하는 것을 `TodoList`가 하는게 맞는 것 같아서요 ㅎㅎ
각 컴포넌트가 해야할일을 나누는게 쉽지 않네요.. ㅠㅠ
참고할 만한 자료가 있을까요?

2020-06-11 14:58 UTC, hannut91 commented on src/Component/Todo.jsx
> +    ))
관심사의 분리를 찾아보시면 될 것 같아요

2020-06-12 00:18 UTC, hannut91 requested changes

2020-06-12 00:18 UTC, hannut91 commented on src/Component/App.jsx
> +    setItem([...items].filter((i) => i.id !== item.id));
자바스크립트의 `filter`함수는 원본 배열에 영향을 주지 않고 새로운 배열을 만들어 냅니다 따라서 `[...items]`라고 안쓰셔도 돼요

2020-06-12 00:18 UTC, hannut91 commented on src/Component/App.jsx
> +    if (!items.length) todos.push({ id: 1, value: text });
아니요. 해당하지 않습니다. 그냥 `if else`에요

2020-06-12 00:18 UTC, hannut91 commented on src/Component/App.jsx
> +    if (items.length) todos.push({ id: todos[todos.length - 1].id + 1, value: text });
이렇게 id를 생성하면 id가 겹치는 문제가 발생할 거에요
그리고 

```js
const id = items.length === 0 ? 1 : todos[todos.length - 1].id + 1;
setItem([...todos, { id, value: text}]);
```

처럼 간단하게 쓸 수 있지만 일단 id만드는 것을 고쳐야 할 것 같아요

2020-06-12 00:18 UTC, hannut91 commented on src/Component/App.jsx
> +  const [items, setItem] = useState([]);
`setItem`이 아니라 `setItems`가 되야 할 것 같네요

2020-06-12 11:30 UTC, SeaFalcon commented on src/Component/App.jsx
> +    if (!items.length) todos.push({ id: 1, value: text });
역시 스스로 꼼수라고 생각한다면 그것은 실제로 꼼수네요 ㅋㅋ

2020-06-12 11:31 UTC, SeaFalcon commented on src/Component/App.jsx
> +    setItem([...items].filter((i) => i.id !== item.id));
앗 그러네요
filter 자체가 원본에 영향을 주지 않으니 상관없겠네요

2020-06-12 11:32 UTC, SeaFalcon commented on src/Component/App.jsx
> +  const [items, setItem] = useState([]);
items에 set을 해주기 때문에
이름도 역시 setItems를 써야하는건가요?

2020-06-12 11:32 UTC, hannut91 commented on src/Component/App.jsx
> +  const [items, setItem] = useState([]);
아니요 ㅎㅎ 복수형으로 맞춰주는거에요

2020-06-12 11:33 UTC, SeaFalcon commented on src/Component/App.jsx
> +    if (items.length) todos.push({ id: todos[todos.length - 1].id + 1, value: text });
일단 유니크하게 만들 수 있는 값이 무엇인가 생각하다가
Date함수를 활용하면 어떨까 생각해서 이것저것 구글링해보다가 
날짜 함수와 랜덤함수를 합성한 값으로 id 값을 정하기로 했습니다 ㅎㅎ

그리고 [...array, {}]와 같이 활용할 수 있는 점은 편리하네요!

2020-06-12 23:54 UTC, hannut91 approved these changes
고생하셨습니다! 아샬님 과제 풀이 영상을 통해서, 변수명을 어떻게 사용하는지 더 유심히 관찰하면서 보시면 유익할 것 같습니다!

2020-06-12 23:55 UTC, merged