[2주차-과제1] '간단한 Todo App 만들기' 코드 리뷰
CodeSoom/week2-assignment-2 pull request #14
Opened 2020-06-11 15:32 UTC by sogoagain

트레이너님, 안녕하세요 :)

'간단한 Todo App 만들기' 코드 리뷰 요청드립니다.

1. Atomic Design
- 최대한 컴포넌트를 쪼개려고 노력해보았습니다.
- Atomic Design 방법론에서 착안하여 컴포넌트들을 'atoms', 'molecules', 'organisms', 'templates', 'page'로 구성하였습니다.

2. 상태 값 관리
- Todo와 관련된 상태 값과 이를 관리하는 기능들은 최상위 컴포넌트인 App 컴포넌트에서 관리하도록 하였습니다.
- 이렇게 한 이유는 Todo 리스트 관리하는 것이 비즈니스 로직이라 생각되었기 때문입니다.
- 그러나, 입력을 받는 InputBox에서 관리하는 상태 값(입력값 관련)은 따로 App 컴포넌트로 옮기지 않았습니다.
- InputBox의 상태값은 비즈니스 로직이라기보다 UI 로직이라 생각되어 이렇게 작성하였는데요, 혹시 이 상태값도 App으로 옮기는 것이 바람직 한 것일까요?
(고민을 계속하고 있는 중인데, 확신이 서질 않네요... 그래서 일단 현재와 같이 구현하였습니다. )

감사합니다! 👍

2020-06-12 01:14 UTC, hannut91 requested changes
템플릿 기능을 만들면 어떻게 될까요? 화면 최상단에 할 일 템플릿이 있어서 그걸 누르면 수정해서 추가할 수 있도록 자동으로 값을 입력해 줍니다. 그리고 이건 입력만 담당하는 컴포넌트와 별개로 존재해야 합니다.

2020-06-12 01:14 UTC, hannut91 commented on src/components/App.jsx
> +  };
`items`가 있으니 items를 사용해서 바로 함수를 호출해도 될 것 같아요

2020-06-12 01:14 UTC, hannut91 commented on src/components/App.jsx
> +  };
`index`로 요소를 찾아서 그 요소를 제거하신 것 같아요. `filter`를 사용해서도 동일하게 문제를 해결할 수 있을까요?

2020-06-12 13:14 UTC, sogoagain commented
> 템플릿 기능을 만들면 어떻게 될까요? 화면 최상단에 할 일 템플릿이 있어서 그걸 누르면 수정해서 추가할 수 있도록 자동으로 값을 입력해 줍니다. 그리고 이건 입력만 담당하는 컴포넌트와 별개로 존재해야 합니다.

아샬님께서 피드백 주신대로 추측에 의존하지 않고 직접 실험해 보았습니다.
트레이너님께서 제안 주신 template 기능을 아래의 두 가지 상황에서 구현했습니다.

Case 1 - InputBox 컴포넌트에서 input 값과 관련된 state를 관리하는 경우
1. Template 컴포넌트 구현
2. Template 컴포넌트에서 템플릿 텍스트가 선택되면 이벤트 핸들러를 통해 상위 컴포넌트로 그 값을 전파
3. App 컴포넌트에서 전달받은 템플릿 텍스트를 별도의 state로 저장
4. state로 관리되는 템플릿 텍스트를 자식 컴포넌트에 props로 전파
5. InputBox 컴포넌트에서 props로 전달받은 템플릿 텍스트를 이용해 input 값과 연관된 state를 변경

Case 2- input 값과 관련된 state를 App 컴포넌트에서 관리하는 경우
1. Template 컴포넌트 구현
2. Template 컴포넌트에서 템플릿 텍스트가 선택되면 이벤트 핸들러를 통해 상위 컴포넌트로 그 값을 전파
3. App 컴포넌트에서 input 값과 연관된 state 값을 설정
4. input 값과 연관된 state를 props로 하위 컴포넌트로 전파
5. InputBox 컴포넌트에서는 props로 전달받은 input 값을 value로 설정

- 차이점
'Case 2'보다 'Case 1'의 경우 관리해야 하는 state가 하나 더 늘어났습니다. 그로 인해 템플릿 테스트 데이터가 전파되는 과정에서 'Case 2'에서는 없어도 되는 로직이 'Case 1'에는 필요했습니다.
예를 들면, App에서 템플릿값을 처리한 뒤 그 결과만 자식에게 전파하면 되었던 'Case 2'와 달리 'Case 1'은 InputBox에서 template props에 값이 포함되는지 여부에 따라 출력되는 값을 달리 해야 하는 등의 로직이 필요했습니다.

- 결론
최상위 App 컴포넌트에서 상태 값들을 관리하고 자식 컴포넌트들은 화면에 출력되는 'View'에 집중하는 설계의 이점을 실험을 통해 직접적으로 알게 되었습니다.

감사합니다. :)

2020-06-12 13:20 UTC, sogoagain commented
> 템플릿 기능을 만들면 어떻게 될까요? 화면 최상단에 할 일 템플릿이 있어서 그걸 누르면 수정해서 추가할 수 있도록 자동으로 값을 입력해 줍니다. 그리고 이건 입력만 담당하는 컴포넌트와 별개로 존재해야 합니다.

그러나 아직 최상위 컴포넌트가 상태값들을 관리하면서 생기는 성능 문제에 대한 궁금증은 여전히 남아있습니다..

이것도 한번 실험을 해보았는데요, React DevTools에서 'Highlight updates when components render.' 옵션을 켜고 렌더링이 어떻게 진행되는지 지켜보았습니다.

Case 1 - InputBox 컴포넌트에서 input 값과 관련된 state를 관리하는 경우

 입력창에 글씨를 입력하면 InputBox 컴포넌트만 렌더링 되는 것을 확인할 수 있었습니다.

<img width="221" alt="스크린샷 2020-06-12 오후 10 09 40" src="https://user-images.githubusercontent.com/23417465/84506458-608ee380-acfa-11ea-94d6-841028f19dda.png">

Case 2- input 값과 관련된 state를 App 컴포넌트에서 관리하는 경우

그런데, Case 2의 경우에 입력값을 입력하면 전체 App이 다시 렌더링 되는 것을 확인하였어요.

<img width="217" alt="스크린샷 2020-06-12 오후 10 08 44" src="https://user-images.githubusercontent.com/23417465/84506552-81efcf80-acfa-11ea-8db8-029f2847acc1.png">

DOM에 변경사항이 없기에 실제 반영되는 것은 아니겠지만, render 처리를 거치긴 하는 것 같은데 큰 규모의 App에선 성능 문제가 발생할 수 있지 않을까...하는 궁금증이 계속 남아있습니다. ㅠㅠ

2020-06-12 13:21 UTC, sogoagain commented on src/components/App.jsx
> +  };
items 배열을 직접 수정하면 immutable 하게 배열을 다루지 못하게 되어 이렇게 했는데요, 직접 수정해도 괜찮을까요?

2020-06-12 13:21 UTC, sogoagain commented on src/components/App.jsx
> +  };
> `items`가 있으니 items를 사용해서 바로 함수를 호출해도 될 것 같아요

items 배열을 직접 수정하면 immutable 하게 배열을 다루지 못하게 되어 이렇게 했는데요, 직접 수정해도 괜찮을까요?

2020-06-12 13:22 UTC, sogoagain commented on src/components/App.jsx
> +  };
> `index`로 요소를 찾아서 그 요소를 제거하신 것 같아요. `filter`를 사용해서도 동일하게 문제를 해결할 수 있을까요?

그렇네요, filter를 사용하면 더 간단해지는 것 같습니다. 목적도 명확하고요.
수정했습니다. 👍

2020-06-13 00:27 UTC, hannut91 requested changes
실험을 하셨군요! 좋네요 ㅎㅎ

이번 과제는 UI와 상태를 관리하는 컴포넌트로 관심사의 분리를 하는데 집중하고 있어요

2020-06-13 00:27 UTC, hannut91 commented on src/components/organisms/TodoContent.jsx
> +      return <></>;
비어있을 때 아무것도 렌더링 하지 않기 위해서 작성하신것으로 보입니다. `return null`하면 동일한 결과를 얻으실 수 있습니다.

See also
  - https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering

2020-06-13 00:27 UTC, hannut91 commented on src/components/App.jsx
> +    : Math.max(...todoItems.map((i) => i.id)));
이렇게 작성해도 같은 결과를 나타낼 것 같아요

```js
Math.max(0, ...todoItems.map(({id}) => id);
```

2020-06-13 00:27 UTC, hannut91 commented on src/components/App.jsx
> +  };
여기서 `todoItems`를 사용하고 있지 않네요. 지워도 될 것 같아요

2020-06-13 00:27 UTC, hannut91 commented on src/components/App.jsx
> +    const lastId = getLastId(todoItems);
`getLastId(state.todoItems)`라고 쓰면 `todoItems`는 파라미터로 안넘겨줘도 될 것 같아요

2020-06-13 00:27 UTC, hannut91 commented on src/components/App.jsx
> +  const removeItemById = (todoItems, id) => [...todoItems].filter((i) => i.id !== id);
`filter`는 원본 배열을 변경하지 않고 새로운 배열을 반환합니다. 따라서

```js
todoItems.filter((i) => i.id !== id);
```

로 써줘도 될 것 같아요

2020-06-13 05:09 UTC, sogoagain commented
> 실험을 하셨군요! 좋네요 ㅎㅎ
> 
> 이번 과제는 UI와 상태를 관리하는 컴포넌트로 관심사의 분리를 하는데 집중하고 있어요

네, 과제의 목적을 연습하는데 초점을 맞추도록 하겠습니다. :)

2020-06-13 05:11 UTC, sogoagain commented on src/components/organisms/TodoContent.jsx
> +      return <></>;
null 값으로 return 하려니 마음 한 켠이 불편했는데, 레퍼런스가 있으니 불편함이 사라지네요 :)
반영 했습니다!

2020-06-13 05:11 UTC, sogoagain commented on src/components/App.jsx
> +    : Math.max(...todoItems.map((i) => i.id)));
훨씬 간결하네요.
또 한번 배웁니다. 감사합니다!

2020-06-13 05:12 UTC, sogoagain commented on src/components/App.jsx
> +  };
네, 지웠습니다. :) 
혹시 여기서는 과제1과 같이 참조투명성을 만족시키지 않아도 괜찮은 것 일까요?

2020-06-13 05:12 UTC, sogoagain commented on src/components/App.jsx
> +    const lastId = getLastId(todoItems);
네! 이벤트 핸들러에서 state 값을 사용하도록 수정했어요.
위에서도 질문을 남겼는데요, 이번 과제에서는 저번 과제처럼 참조투명성을 만족시키지 않아도 괜찮은 것 일까요?

2020-06-13 05:13 UTC, sogoagain commented on src/components/App.jsx
> +  const removeItemById = (todoItems, id) => [...todoItems].filter((i) => i.id !== id);
반영했습니다. :)

2020-06-13 05:26 UTC, hannut91 commented on src/components/App.jsx
> +  };
제가 저번에 조금 잘못 설명한 것 같아요. 진짜 순수한 함수를 말하는 사람들은 위에도 참조 투명성을 깨트린다고 보는 사람도 있는데, handleComplete가 state의 값에 따라 다르게 동작할 수 있기 때문이에요. 하지만 사실 `App` 함수가 실행될 때 `state`는 값이 결정되어 `state`는 값이 변하지 않기 때문에 `handleComplete`를 값으로 치환해도 같은 결과를 나타내므로 참조 투명성을 지킨다고 얘기 할 수 있어요

이 순수한 함수에도 주장하는 사람마다 조금 차이가 있기 때문에 저도 조금 헷갈려서 잘못 설명한 부분인 것 같아요.

2020-06-13 05:27 UTC, hannut91 commented on src/components/App.jsx
> +    const lastId = getLastId(todoItems);
https://github.com/CodeSoom/week2-assignment-2/pull/14#discussion_r439710942

에 답변 드렸습니다!

2020-06-13 05:35 UTC, sogoagain commented on src/components/App.jsx
> +  };
> 제가 저번에 조금 잘못 설명한 것 같아요. 진짜 순수한 함수를 말하는 사람들은 위에도 참조 투명성을 깨트린다고 보는 사람도 있는데, handleComplete가 state의 값에 따라 다르게 동작할 수 있기 때문이에요. 하지만 사실 `App` 함수가 실행될 때 `state`는 값이 결정되어 `state`는 값이 변하지 않기 때문에 `handleComplete`를 값으로 치환해도 같은 결과를 나타내므로 참조 투명성을 지킨다고 얘기 할 수 있어요
> 
> 이 순수한 함수에도 주장하는 사람마다 조금 차이가 있기 때문에 저도 조금 헷갈려서 잘못 설명한 부분인 것 같아요.

답변 감사드립니다!
여러 시각으로 바라볼 수 있군요. 아직 제가 함수형 패러다임에 대한 이해가 깊지 않아 내공을 더 쌓아야겠다는 생각이 드네요... ㅎㅎ
최근 '함수형 자바스크립트 입문'이라는 책을 읽으며 함수형 패러다임에 대해서 공부를 시작했는데, 과제와 같이해나가니 경험을 통해 이해할 기회가 주어져 좋은 것 같습니다. :)

2020-06-13 06:20 UTC, hannut91 commented on src/components/App.jsx
> +  };
그책은 추천드리지 않습니다
아샬님의 트윗을 참고하세여
https://twitter.com/ahastudio/status/1269928014445305860?s=20

http://mobile.kyobobook.co.kr/showcase/book/KOR/9788968480799?orderClick=Ow4
http://mobile.kyobobook.co.kr/showcase/book/KOR/9791162240427?orderClick=Ow4
이 두책을 추천드려요

2020-06-13 09:58 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 더 자세한 내용은 아샬님 과제풀이를 보고 복습하시면 좋을 것 같아요!

2020-06-13 09:58 UTC, hannut91 commented on src/components/organisms/TodoContent.jsx
> +}
이렇게 더 간단히 표현할 수 있을거에요
```js
if (todoItems.length === 0) {
  return <Message message="할 일이 없어요!" />
}

return (
  <OrderedList>
    {[...items].map((item) => (
      <ListItem
          key={item.id}
      >
        <TodoItem
            text={item.text}
            onComplete={() => onComplete(item.id)}
        />
      </ListItem>
    ))}
  </OrderedList>
);
```

2020-06-13 10:50 UTC, merged

2020-06-13 13:24 UTC, sogoagain commented on src/components/App.jsx
> +  };
> 그책은 추천드리지 않습니다
> 아샬님의 트윗을 참고하세여
> https://twitter.com/ahastudio/status/1269928014445305860?s=20
> 
> http://mobile.kyobobook.co.kr/showcase/book/KOR/9788968480799?orderClick=Ow4
> http://mobile.kyobobook.co.kr/showcase/book/KOR/9791162240427?orderClick=Ow4
> 이 두책을 추천드려요

엇, 그렇군요 ㅠㅠ 제일 최근에 출간된 것이라 구매하였는데...
추천 감사드립니다!

2020-06-13 13:25 UTC, sogoagain commented on src/components/organisms/TodoContent.jsx
> +}
아! return 문을 활용해서 예외 처리를 하니 훨씬 더 간결해지네요.
감사합니다.

2020-06-13 13:26 UTC, sogoagain commented
> 고생하셨습니다 ㅎㅎ 더 자세한 내용은 아샬님 과제풀이를 보고 복습하시면 좋을 것 같아요!

네! 꼼꼼한 리뷰 감사드립니다. :)