[wee2-2] To-do list app
CodeSoom/week2-assignment-2 pull request #15
Opened 2020-06-12 02:45 UTC by dididy

아직 파일을 나누지는 않았는데 마감이 얼마 남지 않은 관계로.. lint와 테스트를 통과한 코드부터 제출합니다. 최대한 빠르게 파일을 용도에 맞게 구조화한 커밋을 push하도록 하겠습니다.

과제를 하다보니 궁금한 점이 생겼는데, 
```javascript
something.map((i, keyEach) => (
<div key={i}>
</div>
```
위와같은 코드에서 key를 keyEach로 잡게되면 `Do not use Array index in keys | react/no-array-index-key` 라는 lint 에러가 발생하는데 왜 이렇게 하면 안되는 걸까요?

2020-06-12 03:02 UTC, dididy commented
파일도 나눠 놨습니다! 코드리뷰 부탁드립니다. 감사합니다.

2020-06-13 00:49 UTC, wholemann commented
> 파일도 나눠 놨습니다! 코드리뷰 부탁드립니다.
> 
> 추가적인 질문이 생겼는데
> 
> ```js
>   function deleteTodo(passedKey) {
>     setState({
>       todo:  state.todo.splice(passedKey, 1),
>     });
> }
> ```
> 
> ```js
>   function deleteTodo(passedKey) {
>     const array = state.todo.filter((i, key) => (key !== passedKey));
>     setState({
>       todo: array,
>     });
>   }
> ```
> 
> 첫번째 코드는 정상적으로 동작하지 않고 두번째 코드는 정상적으로 동작하는데 splice를 사용했을 때 의도한대로 동작하지 않는 이유가 궁금합니다!

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

splice 함수의 스펙 학습이 필요합니다.

자주 실수하는 부분인데 sort, splice, slice 와 filter, map, reduce 이 두 묶음을 나눠서 살펴보시면
결정적인 차이를 아실 수 있습니다.

2020-06-13 00:50 UTC, wholemann commented
> 아직 파일을 나누지는 않았는데 마감이 얼마 남지 않은 관계로.. lint와 테스트를 통과한 코드부터 제출합니다. 최대한 빠르게 파일을 용도에 맞게 구조화한 커밋을 push하도록 하겠습니다.
> 
> 과제를 하다보니 궁금한 점이 생겼는데,
> 
> ```js
> something.map((i, keyEach) => (
> <div key={i}>
> </div>
> ```
> 
> 위와같은 코드에서 key를 keyEach로 잡게되면 `Do not use Array index in keys | react/no-array-index-key` 라는 lint 에러가 발생하는데 이런식으로 사용하면 안되는 이유가 뭘까요?

https://ko.reactjs.org/docs/lists-and-keys.html

그 답은 위의 링크에 잘 설명되어 있습니다. 배열의 index로 key를 사용하면 안 되는 이유에 대해서
추가적인 링크까지 남김 없이 읽어보시면 좋겠네요👍

2020-06-13 01:59 UTC, wholemann requested changes
어려운 과제를 그래도 잘 구현해주셨습니다.

몇 가지 아쉬운 부분과 생각해볼 부분을  comment 드렸습니다.

질문이 있으시면 언제든 DM 주세요:)

2020-06-13 01:59 UTC, wholemann commented on src/component/AddPart.jsx
> +function AddPart({ addTodo }) {
AddPart는 모호한 컴포넌트 이름입니다.
이건 어떤 역할을 하는 컴포넌트인가요?

2020-06-13 01:59 UTC, wholemann commented on src/component/BelowPart.jsx
> +function BelowPart({ todo, deleteTodo }) {
BelowPart도 사람마다 기준이 달라서 무엇을 지칭하는지 정확히 알 수가 없습니다.

2020-06-13 01:59 UTC, wholemann commented on src/component/BelowPart.jsx
> +        todo.length !== 0 ? todo.map((i, key) => (
map을 실행한다는 건 복수형태의 collection이란 것인데
todo보단 todos와 같은 복수표현이 좋겠습니다.

2020-06-13 01:59 UTC, wholemann commented on src/index.jsx
> +    });
DOM을 직접 조작하지 않기 위해 사용하는 게 리액트입니다.

만약 DOM을 직접 조작하고 있다면 무언가 잘못하고 있다는 신호입니다.

input에 입력되는 값 자체도 상태로 바라본다면 어떨까요?

2020-06-13 01:59 UTC, wholemann commented on src/index.jsx
> +function App() {
이곳은 index.jsx입니다. App 컴포넌트는 따로 분리하는 게 좋겠습니다.

2020-06-13 01:59 UTC, wholemann commented on src/component/BelowPart.jsx
> +          <div key={i}>
key는 유일하게 식별할 수 있어야 합니다.
아래 문서를 상세히 학습하시고 key값에 대해 고민해보세요.

- https://ko.reactjs.org/docs/lists-and-keys.html

2020-06-13 01:59 UTC, wholemann commented on src/index.jsx
> +      todo: array,
굳이 array를 위에서 변수로 선언하고 할당할 필요는 없어보입니다.

또한 array라는 표현은 굉장히 모호한 변수명이죠.

2020-06-13 01:59 UTC, wholemann commented on src/index.jsx
> +    const array = state.todo.filter((i, key) => (key !== passedKey));
이후에 기능추가에 따라서 배열에서 index의 순서와 실제 화면에서 보여지는 리스트 안의 todo의 순서는 다를 수 있습니다.

위와 같은 상황은 어떤 게 있을까요? 그리고 현재와 같은 구현은 그 상황에서 어떤 문제를 만들 수 있을까요?

간단한 실험을 통해 확인해보는 것도 좋습니다.

2020-06-13 03:08 UTC, dididy commented on src/index.jsx
> +function App() {
따로 분리하였습니다!

2020-06-13 03:23 UTC, dididy commented on src/index.jsx
> +      todo: array,
수정하였습니다!

2020-06-13 04:02 UTC, dididy commented on src/component/BelowPart.jsx
> +        todo.length !== 0 ? todo.map((i, key) => (
반영하였습니다!

2020-06-13 05:12 UTC, dididy commented on src/component/AddPart.jsx
> +function AddPart({ addTodo }) {
AddPart라는 컴포넌트 이름을  AddTodoList로 변경하였습니다.

2020-06-13 05:12 UTC, dididy commented on src/component/BelowPart.jsx
> +function BelowPart({ todo, deleteTodo }) {
BelowPart라는 컴포넌트 이름을 ShowTodoList로 변경하였습니다.

2020-06-13 05:13 UTC, dididy commented on src/index.jsx
> +    });
input태그의 값을 해당 함수의 매개변수로 전달할 수 있도록 수정하였습니다!

2020-06-13 05:26 UTC, dididy commented on src/component/BelowPart.jsx
> +          <div key={i}>
말씀해 주신 문제를 해결하기 위해 useState로 만든 todos를 object array로 만들어 객체에 id라는  key를 만들고 todo를 추가할 때 unique한 id를 value를 넣은 뒤 props로 가져와 이를 넘기는 방식으로 해결하였습니다.

2020-06-13 05:32 UTC, dididy commented
개선해야 할 사항들에 대해 리팩토링을 진행하였습니다. map함수를 사용할 때 key를 설정하는 것에 대해 가볍게 생각했었는데 앞으로는 어떻게 처리해야 할지 확실하게 알게된 것 같습니다. 하지만 역시 이부분도 애매한게 있는데 저는 key를 위한 랜덤한 4자리 문자열로 구성된 id를 만들어서 이것을 props로 넘겨 key에 매핑하였는데 혹시 더 좋은 방법이 있을까요?

이 외에도 다듬어야 할 부분이 있다면 알려주시면 감사하겠습니다!

2020-06-14 07:49 UTC, wholemann requested changes
강의에서 주어진 기본적인 틀을 참고하시면 좋을 듯 합니다.

강의 코드에서 등장하는 함수명이나 변수명 등 모두 이유가 있기 때문에
왜 그런 명명을 하는지 고민해볼 필요가 있습니다:)

몇 가지 고민해보시고 수정하실 부분 comment 드렸습니다.
comment에 대한 질문은 언제든 DM 주세요!

2020-06-14 07:49 UTC, wholemann commented on src/App.jsx
> +      id: Math.random().toString(16).slice(-4),
겹칠 확률이 높진 않을텐데요.

보통은 이러한 부분은 DB에서 사용하는 방식대로 정수로 auto increment 처리를 해서 계속 증가하는 ID를 부여하거나,

uuid와 같은 사실상 중복이 불가능한 방식을 취하기도 합니다.

2020-06-14 07:49 UTC, wholemann commented on src/component/AddTodoList.jsx
> +function AddTodoList({ addTodo }) {
이건 List가 아니라 InputForm에 가깝지 않을까요?

2020-06-14 07:49 UTC, wholemann commented on src/component/AddTodoList.jsx
> +  const [sentence, setSentence] = useState('');
입력 텍스트에 대한 상태관리를 이곳에서 하는 건 어떤 상황에 불편함을 줄까요?

만약 화면 최상단에 할 일 템플릿이 있어서 그걸 누르면 수정해서 추가할 수 있도록 자동으로 값(기본 문구)을 입력해 줍니다.
그리고 이건 입력만 담당하는 컴포넌트와 별개로 존재해야 합니다. 즉, Template 컴포넌트가 있는 것이죠.

이렇게 입력 텍스트가 다른 컴포넌트에서 온다면 현재 이곳에서 상태관리를 했을 때 어떤 불편함 점이 있을지 고민해보세요.
실험을 직접 해보셔도 좋습니다ㅎㅎ

강의 3편에서 관심사의 분리를 다시 보시면 힌트를 얻으실 수 있을 겁니다.

2020-06-14 07:49 UTC, wholemann commented on src/component/AddTodoList.jsx
> +  }
passedSentence는 모호한 표현같아요. 통과된 문장을 무엇이라 해석해야 할까요?

2020-06-14 07:49 UTC, wholemann commented on src/component/ShowTodoList.jsx
> +          </div>
Item 컴포넌트로 분리해도 좋지 않을까요?

Todo에 기능이 복잡해진다면 어떤 일이 벌어질까요?

2020-06-14 07:49 UTC, wholemann commented on src/component/ShowTodoList.jsx
> +function ShowTodoList({ todos, deleteTodo }) {
Show는 동사입니다. 어떤 의미로 해석될 수 있을까요?
컴포넌트 이름으로 적절한 지 고민해보면 좋겠네요.

2020-06-14 07:49 UTC, wholemann commented on src/App.jsx
> +  function deleteTodo(passedKey) {
핸들러인데 어떤 이벤트에 대한 핸들러인지 전혀 드러나지 않고 있습니다.

강의를 보시면 적절한 convention을 알 수 있습니다.

2020-06-14 07:49 UTC, wholemann commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
state를 하나의 객체로 관리하는 건 어떨까요?

강의에 힌트가 있습니다.

2020-06-14 09:23 UTC, dididy commented on src/App.jsx
> +      id: Math.random().toString(16).slice(-4),
더 간단하게 함수형태로 만들었습니다!

2020-06-14 09:23 UTC, dididy commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
todos와 inputSentence를 객체로 관리할 수 있도록 변경하였습니다!

2020-06-14 09:24 UTC, dididy commented on src/App.jsx
> +  function deleteTodo(passedKey) {
click 이벤트에 대한 핸들러인걸 알 수 있도록 handleClickDelete라는 이름으로 바꾸었습니다!

2020-06-14 09:24 UTC, dididy commented on src/component/AddTodoList.jsx
> +function AddTodoList({ addTodo }) {
AddTodoList에서 AddTodoInputForm으로 이름을 변경하였습니다!

2020-06-14 09:26 UTC, dididy commented on src/component/AddTodoList.jsx
> +  const [sentence, setSentence] = useState('');
상태관리를 App 컴포넌트에서 하도록 변경하였습니다!

2020-06-14 09:27 UTC, dididy commented on src/component/AddTodoList.jsx
> +  }
간결하게 id를 넘겨주므로 id라고 변경하였습니다!

2020-06-14 09:29 UTC, dididy commented on src/component/ShowTodoList.jsx
> +function ShowTodoList({ todos, deleteTodo }) {
EntireTodoListView로 변경하였습니다!

2020-06-14 10:06 UTC, dididy commented
리팩토링 진행하였습니다!

2020-06-14 11:32 UTC, wholemann requested changes
몇 가지 수정사항 comment 남겨드렸습니다.

잘 고민해보시고 질문 있으시면 DM 주세요!

2020-06-14 11:32 UTC, wholemann commented on src/App.jsx
> +  }
이건 길이가 항상 증가한다는 가정하에 사용할 수 있습니다. 그러나 길이는 가변이죠.

길이에 기반해서 id를 만든다면 어떤 문제가 생길까요?

2020-06-14 11:32 UTC, wholemann commented on src/App.jsx
> +      todos: todos.filter((i) => (i.id !== id)),
i는 모호한 표현 같습니다. todo는 어떨까요?

2020-06-14 11:32 UTC, wholemann commented on src/App.jsx
> +        handleClickDelete={handleClickDelete}
props key의 네이밍이 전달하는 핸들러 함수와 같다면 Page 내에서 어떻게 사용되는지 굉장히 모호해집니다.

이 핸들러 함수를 어떤 상황에 쓰겠다가 자연스럽게 표현되면 좋겠죠.

onClickAddTodo={handleClickAddTodo} 와 같이 표현한다면 제가 위에 말씀드린 맥락으로 읽히겠죠?

2020-06-14 11:32 UTC, wholemann commented on src/component/EntireTodoListView.jsx
> +            handleClickDelete={handleClickDelete}
i와 같은 변수명은 모호해요.

2020-06-14 11:32 UTC, wholemann commented on src/component/EntireTodoListView.jsx
> +function EntireTodoListView({ todos, handleClickDelete }) {
Entire의 의미를 모르겠습니다.

그리고 보통 컴포넌트에 View라는 이름을 붙이진 않아요. 이건 Java같은 언어에서 쓰는 convention이죠.

리액트 자체가 이미 View임이 명확한 상황에 굳이 View라는 네이밍을 붙일 필요가 있을까요?

그러면 컴포넌트인데 View가 붙어있지 않다면 코드를 읽는 입장에서 어떤 혼란이 올까요?

2020-06-14 19:03 UTC, dididy commented on src/App.jsx
> +  }
겹치는 key가 생길 수 있을 것 입니다. 이부분은 기존 객체배열의 각각의 id 중 가장 큰 id에 +1을 하는방식으로 개선하였습니다.

2020-06-14 19:04 UTC, dididy commented on src/App.jsx
> +      todos: todos.filter((i) => (i.id !== id)),
수정하였습니다!

2020-06-14 19:08 UTC, dididy commented on src/App.jsx
> +        handleClickDelete={handleClickDelete}
모호함을 줄일 수 있도록 수정하였습니다. 혹시 이런식으로 props key를 수정해야하는 다른 부분이 있을까요?

2020-06-14 19:09 UTC, dididy commented on src/component/EntireTodoListView.jsx
> +            handleClickDelete={handleClickDelete}
i를 todo로 변경하였습니다!

2020-06-14 19:29 UTC, dididy commented on src/component/EntireTodoListView.jsx
> +function EntireTodoListView({ todos, handleClickDelete }) {
EntireTodoListView에서 TodoList로 컴포넌트 이름을 변경하였습니다!

2020-06-14 19:33 UTC, dididy commented
수정이 늦어졌네요 죄송합니다. 위에서 리뷰해주신 상황 외에 props key 네이밍을 변경해야 하는 상황에 대한 감이 안잡히긴 하는데 앞으로  React를 사용해나가면서 알게될 것 같습니다.

생각보다 제가 React를 사용하여 코딩할 때 엉망으로 짜왔다는걸 알게되어서 좋았습니다. 더 좋은 방향으로 교정해나갔으면 하네요.

리뷰해주시느라 수고 많으셨습니다!

2020-06-14 22:47 UTC, wholemann approved these changes
Merge하겠습니다. 고생하셨습니다:)

나머진 아샬님 피드백 강의를 보시면 더 채울 수 있을 겁니다.

사소한 부분이라 생각할 수 있지만 좋은 코드는 항상 신경써야 하는 게 많습니다.
공백 한 줄도 의미가 있어야 합니다.
앞으로 점점 좋아지실 거에요:)

2020-06-14 22:47 UTC, merged