<2주차 과제2 - 간단한 Todo App 만들기>
CodeSoom/week2-assignment-2 pull request #156
Opened 2022-08-10 11:55 UTC by xunxee

1. 미완성의 첫 번째 commit 입니다.
2. 기본적인 세팅을 진행했습니다.
  - input에 작성한 값을 담기 위해 "inputValue"라는 state를 생성했습니다.
  - "추가 버튼"을 누르면, 값들의 list 목록을 만들기 위해 "list"라는 state를 생성했습니다.
3. 작업 내용을 그때그때 commit 남겨야 하는데, 자꾸 잊어버리고 한 번에 commit을 올리네요🥲 죄송합니당 ㅠ

2022-08-10 14:28 UTC, daadaadaah requested changes
계속 진행해주세요!🚀  

이 commit 라도 한번 작업별로 commit 작성하는거 도전해보세요!ㅎㅎ

2022-08-10 14:28 UTC, daadaadaah commented on src/App.jsx
> +          type="inputValue"
type에 `inputValue`가 있던가용?ㅎㅎ

2022-08-11 06:56 UTC, xunxee commented on src/App.jsx
> +          type="inputValue"
🥲 아공, 제가 value프로퍼티와 헷갈렷네요

2022-08-11 12:54 UTC, daadaadaah requested changes
> commit을 남기는 부분에 있어서 어느 작업까지 나눠서 올려야 하는 것인지 조금 어렵습니다 ㅠㅠ
보통 파일별 작업을 기준으로 commit을 나누어 올리는 것이 좋은까요~?

- 저는 목적 단위로 commit을 만들어요! 예를 들어, 변수명을 A->B로 변경하는 작업을 해야 되고, 이 변수명이 여러 파일에 있다면, 1개의 commit으로 만듭니다! 그리고, 질문은 코멘트로 남겨주시는게 좋을 것 같아요!ㅎㅎ

2022-08-11 12:54 UTC, daadaadaah commented on src/App.jsx
> +  const [list, setList] = useState([]);
`할일목록` 데이터에서 중요한 건 `목록`이 아니라 `할일`이라는 명사인 것 같아요!ㅎㅎ`할일들`이라는 의도가 드러나도록 한번 바꿔봅시당!ㅎㅎ

2022-08-11 12:54 UTC, daadaadaah commented on src/App.jsx
> +  }
1. uuid 를 만드셨군요!ㅎㅎnpm install 해서 한번 사용해보셔도 좋을 것 같아요!ㅎㅎ
2. 만약, 직접 구현한 걸 사용하고 싶으시면, util 파일 하나 만들어서 관리하는게 좋을 것 같아요!ㅎㅎ

2022-08-11 12:54 UTC, daadaadaah commented on src/App.jsx
> +            setList={setList}
`setList`가 언제 필요한 props 인가요? 오타인가용?ㅎㅎ

2022-08-12 03:14 UTC, xunxee commented on src/App.jsx
> +  const [list, setList] = useState([]);
바꾸고 나니 훨씬 보기 좋네용! 감사합니당

2022-08-12 03:27 UTC, xunxee commented on src/App.jsx
> +  }
UUID, npm으로 간단히 설치가 가능했네요 🐥
UUID 사용하니 너무 편리하네요, 감사합니다!

2022-08-12 03:30 UTC, xunxee commented on src/App.jsx
> +            setList={setList}
앗 오타입니다! 🥲

2022-08-12 12:38 UTC, daadaadaah approved these changes
잘하셨어요!👏
이번주 피드백 강의를 보며 아샬님은 어떻게 하셨는지 한번 잘 관찰해보세요~! 주간회고도 작성하시는거 잊지마시구요~ㅎㅎ

2022-08-15 03:31 UTC, merged