React로 Todo 앱 만들기
CodeSoom/week2-assignment-2 pull request #158
Opened 2022-08-11 12:01 UTC by 0-Chan

안녕하세요 트레이너님~! Todo 앱 첫 PR 드립니다.

지금 src 폴더의 구조가
                                ┌ Todos.jsx
App.jsx -> Page.jsx │
                                └ AddTodo.jsx(미완)

혹시 해당 구조가 맞는지 틀린지 아직도 의아한 상황이라서요... 한번 봐주시면 감사하겠습니다 ㅎㅎ

2022-08-11 13:31 UTC, daadaadaah requested changes
이번주 강의가 많이 어려우셨나요? 😭 전반적으로 코드가 너무 복잡합니다ㅠㅠ
일단 1차 목표로 App.jsx 파일에 모든 기능을 구현해보시고, 그 다음 컴포넌트를 분리해보시는 건 어떠신가요?

2022-08-11 13:31 UTC, daadaadaah commented on src/index.jsx
> +);
1. 과제 1에서 index.jsx 파일을 어떻게 만들어주었는지 다시한번 봅시당!ㅎㅎ
2. 마지막 한줄 띄어주시구요!ㅎㅎ

2022-08-11 13:31 UTC, daadaadaah commented on src/AddTodo.jsx
> +        Add
요구사항에 나와있는 단어를 사용해주셔야 해요!ㅎㅎ
"추가" 로 단어 변경해주세요~ㅎㅎ

2022-08-11 13:31 UTC, daadaadaah commented on src/AddTodo.jsx
> +export default function AddTodo({ onClick }) {
react에서 컴포넌트 네이밍을 어떻게 하는지 한번 찾아봅시당!ㅎㅎ

2022-08-12 09:31 UTC, 0-Chan commented on src/index.jsx
> +);
React 18에서 사용하는 방식이라고 해서 시도 해보았는데.. 다시 ReactDOM 방식으로 호다닥 바꿨습니다.

2022-08-12 09:31 UTC, 0-Chan commented
그리고 나눈 컴포넌트를 App.jsx 하나로 일원화 하였습니다.!! 잘못 눌러서 PR을 close 해버렸네요.

2022-08-12 09:31 UTC, 0-Chan commented on src/AddTodo.jsx
> +        Add
넵. 추가로 바꾸었습니다.

2022-08-12 12:32 UTC, daadaadaah requested changes
아직 미구현된 기능이 있는데, 진행중이신건가용?ㅎㅎ

2022-08-12 12:32 UTC, daadaadaah commented on src/App.jsx
> +  const todoLists = todos.map(todo =>
48~54줄에서 동일한 역할을 하는데, 따로 변수화 시켜주신 이유가 있을까용?ㅎㅎ

2022-08-12 12:32 UTC, daadaadaah commented on src/App.jsx
> +      <input></input>
input 요소에 기본적으로 type 같은 거 명시해주는 것이 좋아요! 
또한, 요구사항에 맞게 placeholder 같은 속성을 이용해보세요!ㅎㅎ
```jsx
      <input
        type="text"
        placeholder="할 일을 입력해 주세요"
      />
```

2022-08-12 12:32 UTC, daadaadaah commented on src/App.jsx
> +      id: 1,
uuid 에 대해 한번 공부해보세요!ㅎㅎ

2022-08-13 12:22 UTC, 0-Chan commented on src/App.jsx
> +  const todoLists = todos.map(todo =>
앗.. App.jsx로 급하게 일원화 하다가 지우지 못했습니다ㅜ.

2022-08-13 12:23 UTC, 0-Chan commented on src/App.jsx
> +      <input></input>
앞으로 MDN에서 input에서 사용하는 요소 등을 잘 봐보겠습니다!

2022-08-13 12:33 UTC, daadaadaah requested changes
잘하셨어요!👏👏👏👏
이제 컴포넌트를 분리해봅시다!ㅎㅎ

2022-08-13 13:46 UTC, 0-Chan commented on src/App.jsx
> +      id: 1,
오옷.. uuid 앞으로 유용할 것 같아서 짧게 정리하여 기억 해놓겠습니다!

- UUID
 32자리 값을 무작위로 생성하기에 같은 UUID를 생성할 확률이 매우 낮은 식별자.<br>
16 바이트 크기를 가짐.<br>
작업의 진행 상태(작업 ID), 사용자 구분(유저 ID), 웹 서버 요청 구분(세션 ID) 등에 쓰이게 됨.


### 패키지 사용법
```javascript
$ npm install uuid
이 후에 사용할 jsx 파일에 가서

import { v4 as uuidv4 } from 'uuid';
하면 이제
const uuid = uuidv4();
```

2022-08-14 12:04 UTC, 0-Chan commented
> 잘하셨어요!clapclapclapclap 이제 컴포넌트를 분리해봅시다!ㅎㅎ

감사합니닷.. 일단 해설을 보고 과제를 마무리 하긴 했는데요.

아직 React의 전체 흐름이 크게 와닿지 않는 상태네요... 

일단 주간회고도 진행 하도록 하겠습니다~! 즐거운 공휴일 보내세요^^

2022-08-15 03:31 UTC, merged

2022-08-15 03:37 UTC, daadaadaah reviewed
이번주도 수고하셨습니다!ㅎㅎ
저도 코드숨에서 처음 react 배웠는데, 익숙해지는데 시간이 좀 걸리더라구요!
처음에 이렇게 하는게 맞나? 라는 생각도 들고~ 
그래서, 그때 그냥 나보다 잘하는 사람인 아샬님의 방식을 그대로 따라 배우자 라는 생각으로 코드숨 과정을 이수했던 것 같아요! 매주 과제를 수행하시다보면 리액트에 익숙해질 겁니당!ㅎㅎ앞으로도 같이 잘해봐요💪

2022-08-15 03:37 UTC, daadaadaah commented on src/AddTodo.jsx
> +export default function AddTodo({ value, onChange, onClick }) {
보통 이런 컴포넌트는 Form 이라는 용어를 사용해서 네이밍 합니다! 
이 점 알아두세용!ㅎㅎ