Implement todo list
CodeSoom/week2-assignment-2 pull request #16
Opened 2020-06-12 14:20 UTC by min-w-park

이번 과제는 좀 어렵네요.. 
그만큼 피드백 많이 받고 싶었는데 너무 늦었군요. 
피드백 미리 감사합니다!

2020-06-13 01:44 UTC, wholemann requested changes
몇 가지 아쉬운 부분 comment 남겨드렸습니다.

comment에 대해 궁금하신 점이 있으면 언제든 DM 주세요ㅎㅎ

2020-06-13 01:44 UTC, wholemann commented on src/InsertTodoItem.jsx
> +export default function InsertTodoItem({ todoItems, onChange, onClick }) {
InsertTodoItem은 자칫 Item 그 자체로 오해받기 쉬운 이름 같습니다.

InsertForm과 같이 명확한 역할이 컴포넌트 이름에서 나타나면 좋겠습니다.

2020-06-13 01:44 UTC, wholemann commented on src/TodoItems.jsx
> +            key={item.task + item.id}
item.task와 item.id를 +해서 key를 만든 이유는 무엇인가요?

2020-06-13 01:44 UTC, wholemann commented on src/Page.jsx
> +  todoItems, onChange, onClick, onClickConfirm,
onClickAddTodo가 명확한 것 같네요.
onChange도 마찬가지로 명확하게 할 수 있을 겁니다.

2020-06-13 01:44 UTC, wholemann commented on src/TodoList.jsx
> +export default function TodoList({ todoItems, onClickConfirm }) {
이 부분에서 todoItems를 구조분해 할당하는 건 어떨까요?

아래 링크에서 매개변수 구조분해 할당을 살펴볼 수 있습니다.

- https://ko.javascript.info/destructuring-assignment

2020-06-13 01:44 UTC, wholemann commented on src/TodoList.jsx
> +  const defaultLabel = todoItems.todoList[0] === undefined ? '할 일이 없어요!' : '';
표현하고자 했던 게 비어있는 todolist라면 todoList[0] === undefined 같은 조건식이 올바른 표현일까요?

2020-06-13 01:44 UTC, wholemann commented on src/index.jsx
> +}
이곳은 index.jsx입니다. 컴포넌트가 아님을 알 수 있죠.
App 컴포넌트는 분리하는 게 좋겠습니다.

2020-06-13 07:44 UTC, min-w-park commented on src/TodoItems.jsx
> +            key={item.task + item.id}
key에 대해서 좀 알아보니깐, index 를 쓸 수는 없고 알려진 방법 중 하나가 UUID를 쓰면 되던데 강의에서 배우지 않은 다른 것을 써도 되나 고민이 되었습니다.
그래서 결국 데이터베이스의 `unique key`를 만드는 것처럼 사용되는 필드(변수)의 조합으로 key를 만들어 봤네요. 근데 문제는 저렇게 하면 같은 내용의 `task`는 생성이 안되네요.. 

UUID가 적합해 보이는데 써도 될까요? 아니면 다른 방법이 있을까요?

2020-06-13 07:45 UTC, min-w-park commented on src/TodoList.jsx
> +  const defaultLabel = todoItems.todoList[0] === undefined ? '할 일이 없어요!' : '';
length 로 바꿔 보았습니다. 처음에 length로 하다가 뭐가 잘 안됐었는데.. 새벽에 졸면서 해서 실수가 좀 있었나보네요.. ㅎ

2020-06-13 08:18 UTC, min-w-park commented on src/TodoList.jsx
> +export default function TodoList({ todoItems, onClickConfirm }) {
이것저것 시도해 보다가 잘 안되서, 호출하는 부분에서 `TodoItems` 내의 `todoList` 를 직접 넘겨 주었습니다. 확인해 보니깐 `TodoList` 의 하위 컴포터넌트에서 `TodoItems` 내의 `todoList` 말고는 다른 프로퍼티를 사용하고 있지 않더라고요.

2020-06-13 08:35 UTC, min-w-park commented
수정 후에 다시 커밋 하였습니다.! 

질문 있습니다.!

``` 
todoItems = {note: '', todoList: []}
```

      <TodoList
        todoItems={todoItems}
        onClickConfirm={onClickConfirm}
      />

```function TodoList( { todoItems , onClickConfirm } )```

구조분해 할당 문제에서, TodoList 컴포넌트의 매개변수로 이미  {} 를 이용해서 받고 있는데, 
`todoItems` 객체를 또 구조 분해 할당 하려니 잘 되지 않았습니다. 
참고해 주신 자료를 보았는데도 잘 안되네요.. 
아래처럼 중첩 구조 할당 같은 건 없을까요? 
_`function TodoList( { { todoList: [] }, onClickConfirm })`_

2020-06-13 11:06 UTC, wholemann commented on src/TodoItems.jsx
> +            key={item.task + item.id}
네 사용하셔도 무관합니다.

2020-06-13 11:18 UTC, wholemann requested changes
몇 가지 아쉬운 부분 comment 드렸습니다.

질문있으시면 언제든 DM 주세요:)

2020-06-13 11:18 UTC, wholemann commented on src/App.jsx
> +    });
push대신 spread syntax를 이용해보세요.

push는 부수효과를 일으킵니다. 즉, 배열의 원본을 바꾸는 건 권장되지 않습니다.

2020-06-13 11:18 UTC, wholemann commented on src/App.jsx
> +    todoItems.note = '';
이건 19라인의 setState에서 동시에 처리할 수 있지 않을까요?

2020-06-13 11:18 UTC, wholemann commented on src/App.jsx
> +  const todoItems = state;
이 부분에서 state의 내부의 상태들을 구조분해 할당한다면 밑에 로직들에서 상당히 깔끔해지는 부분들이 있을 겁니다.

2020-06-13 11:18 UTC, wholemann commented on src/App.jsx
> +    const { todoList } = todoItems;
11라인을 개선한다면 매 함수에서 중복된 구조분해 할당이 필요 없어집니다.

2020-06-13 11:18 UTC, wholemann commented on src/App.jsx
> +      .filter((item) => (item !== selectedItem));
같은 내용의 todo들이 있다면 어떤 문제가 생길까요?

2020-06-13 11:18 UTC, wholemann commented on src/Page.jsx
> +  todoItems, onChangeWriteTodo, onClickAddTodo, onClickConfirm,
애초에 App에서 props로 전달할 때 todoList만 보낸다면 어떨까요?
마찬가지로 App의 11라인 개선을 통해 이 부분도 해결됩니다.

2020-06-13 11:18 UTC, wholemann commented on src/TodoList.jsx
> +      />
이 부분에서 TodoItems로 컴포넌트를 묶은 이유는 무엇인가요?

이곳에서 배열을 이용해서 Items를 나열하는 건 어떻게 생각하시나요?

2020-06-13 11:42 UTC, wholemann commented
> 수정 후에 다시 커밋 하였습니다.!
> 
> 질문 있습니다.!
> 
> ```
> todoItems = {note: '', todoList: []}
> ```
> 
> ```
>   <TodoList
>     todoItems={todoItems}
>     onClickConfirm={onClickConfirm}
>   />
> ```
> 
> `function TodoList( { todoItems , onClickConfirm } )`
> 
> 구조분해 할당 문제에서, TodoList 컴포넌트의 매개변수로 이미 {} 를 이용해서 받고 있는데,
> `todoItems` 객체를 또 구조 분해 할당 하려니 잘 되지 않았습니다.
> 참고해 주신 자료를 보았는데도 잘 안되네요..
> 아래처럼 중첩 구조 할당 같은 건 없을까요?
> _`function TodoList( { { todoList: [] }, onClickConfirm })`_

function TodoList( { todoItems: { todoList, note }, onClickConfirm })

로 한다면 구조분해 할당을 할 수 있습니다. 중첩된 객체이기 때문에 명시적으로 어떤 key값인지 구분을 해줘야 합니다.

2020-06-13 13:42 UTC, min-w-park commented on src/App.jsx
> +      .filter((item) => (item !== selectedItem));
좋은 포인트 입니다.! ID를 사용해서 처리해 보겠습니다.

2020-06-13 14:00 UTC, min-w-park commented on src/TodoList.jsx
> +      />
나열되는 todo 리스트의 공간이 잡힌다는 개념으로 생각했는데, 또 생각해보니 불필요한 것 같기도 하네요. 
삭제하였습니다

2020-06-13 14:16 UTC, min-w-park commented on src/App.jsx
> +      .filter((item) => (item !== selectedItem));
string 타입의 비교일 경우에는 다른 인덱스에 있는 todo도 영향을 받을 것 같습니다.
그러나 todoList의 item 을 객체 {task: 'note'} 로 만들어 놓아서 object의 비교가 되다보니 문제는 없어 보입니다.

2020-06-13 14:19 UTC, min-w-park commented on src/TodoItems.jsx
> +            key={item.task + item.id}
Date를 사용해서 현재 시간을 받아서 테스트 해보았는데, 몇초뒤에 생성 하더라도 같은 key 에러가 나네요.. 일단은 uuid를 써서 제출했습니다만, 좀 의문이긴 하네요.. 
좀 더 봐야 할 것 같습니다.

2020-06-14 02:11 UTC, wholemann requested changes
uuid로 고유키를 부여하셨는데 component의 key로 부여하셨군요.
만약 Item들을 이용해서 여러 리스트를 보여줘야 한다면 어떨까요?

아래 문서를 보시면 대부분 어떻게 ID를 부여하는지 보실 수 있습니다.
그 이유를 한 번 생각해보시면 좋을 것 같네요!

- [리스트와 Key](https://ko.reactjs.org/docs/lists-and-keys.html#keys)

몇 가지 아쉬운 부분 comment 남겼습니다.

다음 PR에선 거의 마무리 될 듯 하네요:)

2020-06-14 02:11 UTC, wholemann commented on src/App.jsx
> +      .filter((item) => (item !== selectedItem));
참조되는 메모리 주소가 같다는 전제하에 인스턴스가 같은지 여부로 비교하고 있습니다.

어떤 상황에 문제가 될 수 있을까요?

2020-06-14 02:11 UTC, wholemann commented on src/InsertForm.jsx
> +          label={label}
굳이 이곳에서 label을 넘길 이유가 있을까요?

2020-06-14 02:11 UTC, wholemann commented on src/Button.jsx
> +      {label}
단순 텍스트라면 이곳에서 '추가' 를 표현해도 좋아보입니다.

2020-06-14 02:11 UTC, wholemann commented on src/Item.jsx
> +  const label = '완료';
여기도 마찬가지 같네요ㅎㅎ

2020-06-14 11:33 UTC, min-w-park commented on src/InsertForm.jsx
> +          label={label}
Button 컴포넌트를 만들기 위해서 썼습니다. 
`<button>`에서 label을 안쓰면 린트에러가 나네요. 
Button 컴포넌트를 지우고 각각의 컴포넌트에서 바로 처리하도록 수정하였습니다.

2020-06-14 11:50 UTC, min-w-park commented
메모리 주소의 비교는 만약 다른데서 어떤 객체가 같은 주소를 바라보고 있을 때 문제가 될 수도 있겠네요. 

uuid 를 todo 내의 taskId로 사용하도록 수정하였습니다.
또한 해당 taskId가 key가 되도록 수정하였습니다.

2020-06-14 14:34 UTC, wholemann approved these changes
마지막으로 조금 아쉬운 부분에 대해 comment 남겨드렸습니다.
이후 과제에서 참고하시면 좋을 겁니다.

아샬님 피드백 강의를 보면 한번 더 정리되는 부분들이 있을테니 보시고
다시 처음부터 복습해보시면 이후 과제에 큰 도움이 될 겁니다:)

Merge하겠습니다. 고생하셨어요!

2020-06-14 14:34 UTC, wholemann commented on src/App.jsx
> +      taskId: keyId,
`taskId: uuidv4(),`

를 바로 해줘도 문제가 없겠네요.

2020-06-14 14:34 UTC, wholemann commented on src/App.jsx
> +      todoList: filteredList,
filteredList의 의미가 불분명하여 34-35라인 로직을 다시 봐야 하는 불편함이 있네요.
이런 경우는 inline variable로 처리하면 좋습니다.

- [refactoring - inline variable](https://refactoring.com/catalog/inlineVariable.html)

2020-06-14 14:34 UTC, merged