과제 2 - 간단한 Todo App 만들기
CodeSoom/week2-assignment-2 pull request #164
Opened 2022-10-18 09:51 UTC by yxxnhx

# 목표
파일 분리 및 카운터 만들기

## 진행사항
### 2일차
현재 todo 작성할 수 있게 input을 활용하여 간단하게 틀만 잡았습니다.
입력한 값을  handleChange로 받아서 handleTodoSubmit으로 등록할 수 있게 할 예정입니다. 아직까지는 제대로 입력이 되지 않아 조금 해봐야 할 것 같습니다.

2022-10-19 03:41 UTC, daadaadaah reviewed
진행중이지만 PR 보내신 점 너무 잘하셨어요!👏
다음 PR 기다리고 있겠습니당!ㅎㅎ

2022-10-21 05:00 UTC, daadaadaah requested changes
구현 중이시지만 PR 날리신 점 잘하셨어요!👏
`todos`가 초기에 문제인지, 아니면, sumbit 하면서 문제인지, 아니면 넘어가면서 문제인지 상황별로 콘솔을 찍어보시는 걸 추천드려요!ㅎㅎ

2022-10-21 05:00 UTC, daadaadaah commented on src/index.jsx
> +        handleChange={handleChange}
`onSubmit`과 `onClick`처럼 패턴을 맞춰주시는게 더 좋을 것 같아요!ㅎㅎ

2022-10-21 05:00 UTC, daadaadaah commented on src/index.jsx
> +  function deleteTodoButton(todoId) {
1. `Button`을 빼도 의도를 전달하는데 문제가 없을것 같아요!ㅎㅎ
2.  이 함수도 `handleXXX`으로 표현해주시는거 어떠신가요? ㅎㅎ

2022-10-21 05:00 UTC, daadaadaah commented on src/Todo/Todos.jsx
> +import React from 'react';
[과제1때 드린 피드백](https://github.com/CodeSoom/react-week2-assignment-1/pull/179#discussion_r998905815) 참고하세요!

2022-10-21 05:00 UTC, daadaadaah commented on src/index.jsx
> +      [...values,
이 줄은 어떤 의도로 작성해주셨나요? ㅎㅎ

2022-10-21 05:00 UTC, daadaadaah commented on src/index.jsx
> +  const [values, setValues] = useState({
`value` 보다 좀더 의도가 드러나는 단어로 표현해주시는게 좋을 것 같아요!

2022-10-22 10:29 UTC, yxxnhx commented on src/index.jsx
> +  function deleteTodoButton(todoId) {
넵 의도가 드러나게 변경해보겠습니다

2022-10-22 10:30 UTC, yxxnhx commented on src/index.jsx
> +      [...values,
값을 입력한 것을 풀어서 하고 싶었는데 잘못 작성한 것 같아요 다시 작성해보겠습니다!

2022-10-22 10:30 UTC, yxxnhx commented on src/index.jsx
> +  const [values, setValues] = useState({
넵 변경해보겠습니다!

2022-10-23 03:17 UTC, daadaadaah commented
E2E 테스트가 깨지네요! 한번 확인 부탁드려요🙇‍♀️

2022-10-23 12:47 UTC, daadaadaah approved these changes
이번주도 수고 많으셨습니다!👏 다음주에도 같이 힘내봐요👊

2022-10-25 12:38 UTC, merged