assignment2- Todo App 만들기
CodeSoom/week2-assignment-2 pull request #165
Opened 2022-10-19 11:57 UTC by hyeji07

### 내용
**Todo App 만들기**

- Todo App 구현

  - '추가'버튼 누를 시 할 일 추가 가능
  - '완료' 버튼 누를 시 할 일 삭제 가능
  - Todo List 없을 시 할 일이 없다는 문구 보이게 설정

- 컴포넌트를 분리하여 각 파일 만들기

### 스크린샷
![2022-10-20 03;23;38](https://user-images.githubusercontent.com/108104436/196783721-11cb9174-e781-4215-8605-f604311980bd.gif)

2022-10-20 05:02 UTC, daadaadaah requested changes
빠른 PR 보내기 너무 잘하셨어요!👏
남겨드린 코멘트 참고해보세요!ㅎㅎ

2022-10-20 05:02 UTC, daadaadaah commented on src/TodoForm.jsx
> +    if (onSubmit) {
이 조건문은 왜 필요한 건가용?ㅎㅎ

2022-10-20 05:02 UTC, daadaadaah commented on src/TodoPage.jsx
> +      <Todos todoItems={todoItems} onClick={onClick} />
데이터를 그냥 받기만하는 `<Todos />` 컴포넌트와 달리, `<TodoForm />`에서는 `todoText` 데이터로 상태를 관리해주는데, 어떤 기준으로 또는 왜 둘 컴포넌트를 다르게 만드셨나용?ㅎㅎ

2022-10-20 05:02 UTC, daadaadaah commented on src/TodoPage.jsx
> +function TodoPage({
혹시, props drilling에 대해 아시나요? 물론, 지금은 뎁스가 깊지는 않지만, 한번 공부해보시면 좋을 것 같아요!ㅎㅎ

2022-10-20 10:29 UTC, hyeji07 commented on src/TodoForm.jsx
> +    if (onSubmit) {
onSubmit의 경우 작동되게 한건데
없애도 되네요..!
수정하였습니다.

2022-10-20 11:43 UTC, hyeji07 commented on src/TodoPage.jsx
> +function TodoPage({
props drilling을 해결하기 위해 
App.jsx에 있던 state,함수를 TodoPage.jsx로 옮겼습니다.
App.jsx에서 관리하는 것보다 여기서 관리하는 게 나은 건가요??

2022-10-20 11:57 UTC, hyeji07 commented on src/TodoPage.jsx
> +      <Todos todoItems={todoItems} onClick={onClick} />
Q.해당 컴포넌트에서 사용되는 것이기 때문에 같이 작성했는데, UI적인 부분만 작성하는 것이 나은 건가요?

Q.
리뷰를 받고 TodoFrom.jsx를 아래와 같이 변경하고,
![image](https://user-images.githubusercontent.com/108104436/196941041-76f8a03c-dfcd-4bbe-8720-c7d1991365de.png)
(값을 받아 전달되기 때문에 `TodoPage.jsx`로 위 코드마저 옮길시엔 에러가 나서 위와 같이 작성했습니다..)

기존 코드를 `TodoPage.jsx` 에서 관리되도록 옮겨 수정했는데
이렇게 작성하는 게 맞는지, 더 나은 코드가 있는지 궁금합니다.

2022-10-21 05:26 UTC, daadaadaah commented on src/TodoPage.jsx
> +      <Todos todoItems={todoItems} onClick={onClick} />
> Q.해당 컴포넌트에서 사용되는 것이기 때문에 같이 작성했는데, UI적인 부분만 작성하는 것이 나은 건가요?
+다른 컴포넌트에서 작성후 받아오면 props drilling이 일어나는데 괜찮나요?

- 관심사분리 관점에서 UI랑 비즈니스 로직이랑 분리해서 관리하는게 좋아요!
- 추가로 다른 컴포넌트에서 작성 후 받아오면서도 props drilling이 발생하지 않도록 할 수 있습니다!ㅎㅎ관심사 분리 관점에서 컴포넌트를 관리하고, props drilling을 해결하기 위한 다른 방법을 생각해보시는걸 추천드려요!ㅎㅎ

2022-10-21 05:28 UTC, daadaadaah commented on src/TodoPage.jsx
> +function TodoPage({
그렇게 옮기는 방법도 있지만, 현재 앱이 여러 페이지로 구성되어 있지 않으므로, TodoPage를 없애는 방법도 있습니다!

2022-10-21 05:29 UTC, daadaadaah requested changes
잘하셨습니당!👏 
남겨드린 답변 참고해서 다음 PR 날려주세요! 기다리고 있을게요!ㅎㅎ

2022-10-21 07:38 UTC, hyeji07 commented on src/TodoPage.jsx
> +function TodoPage({
넵 TodoPage를 삭제하고 App.jsx에서 관리되도록 옮겼습니다!

2022-10-21 07:43 UTC, hyeji07 commented on src/TodoPage.jsx
> +      <Todos todoItems={todoItems} onClick={onClick} />
매개변수로 넘겨주지 않고 App.jsx에서 관리 되도록 `handleSubmit` 코드를 수정하였습니다!

2022-10-21 07:50 UTC, hyeji07 commented
리뷰 반영하여 코드를 다시 수정해서 커밋했습니다 ! 😀

2022-10-22 04:52 UTC, daadaadaah requested changes
잘하셨어요! 거의다 완성이 된것 같아요!ㅎㅎ남겨드린 코멘트 참고해서 마지막 PR 날려봅시당!ㅎㅎ

2022-10-22 04:52 UTC, daadaadaah commented on src/App.jsx
> +  const handleChange = (e) => setTodoText(e.target.value);
이렇게 한줄로 쓸수 있더라도 중괄호를 넣어주는게 읽기 편한 것같아요!ㅎㅎ

2022-10-22 04:52 UTC, daadaadaah commented on src/App.jsx
> +    if (!todoText) {
한줄 띄어줍시당!ㅎㅎ

2022-10-22 04:52 UTC, daadaadaah commented on src/App.jsx
> +        handleChange={handleChange}
1. 42번째 줄처럼 바꿔주시는건 어떠신가요?ㅎㅎ
2. 데이터는 데이터끼리, 함수는 함수끼리 묶어주시는게 좋을 것 같아요ㅎㅎ

2022-10-22 05:50 UTC, hyeji07 commented
넵 리뷰반영하여 다시 올렸습니다!😊

2022-10-23 03:14 UTC, daadaadaah approved these changes
이번주도 수고 많으셨습니다!👏👏 주간회고를 통해 한주를 되돌아보는 시간을 가져보시고, 다음주도 같이 힘내봐요👊

2022-10-25 12:38 UTC, merged