2주차 과제 - Todo 만들기
CodeSoom/week2-assignment-2 pull request #166
Opened 2022-10-20 08:49 UTC by sejineeee

## 내용
- Todo, TodoEditor, TodoList, TodoItem 컴포넌트 구분
- 입력창에 아무것도 입력을 하지 않았을 경우 return으로 입력이 되지 않게 처리(alert 으로 입력해주세요 알리고 싶었으나 eslint 표시를 보고 사용하지 않았습니다!)
- todo에 id는 `Math.random()`을 사용할까 고민하다가, `Date.now()`가 더 적절한 것 같다고 생각했습니다!
- todoList 배열의 길이가 0일 때 할 일이 없어요를 보여주도록 삼항연산자를 이용하여 구현

## 스크린샷

https://user-images.githubusercontent.com/86041335/196902195-e29a4a05-0af0-4925-8f58-37aaf0e59640.mov

2022-10-21 05:06 UTC, daadaadaah requested changes
잘하셨어요!👏 
남겨드린 피드백 참고해서 PR 보내주세요🚀

2022-10-21 05:06 UTC, daadaadaah commented on src/components/App.jsx
> +      <Todo />
`Todo`랑 `TodoItem` 혼동할 수 있을 것 같아요! 구별할 수 있는 네이밍이면 좋을 것 같아요!ㅎㅎ

2022-10-21 05:06 UTC, daadaadaah commented on src/components/Todo.jsx
> +      <TodoList todoList={todoList} onDelete={handleDelete} />
props가 여러개면 세로정렬하시는 걸 추천드립니당!ㅎㅎ

2022-10-21 07:45 UTC, sejineeee commented on src/components/App.jsx
> +      <Todo />
이런 경우에는 Todo가 TodoPage 이름인 경우가 더 적절할까요?
Counter(2주차 1과제)처럼 CounterPage를 없이 하는 방법이 있듯이, 이것도 Todo라고 따로 분리해줄 필요 없이 App 컴포넌트에서 각 컴포넌트로 props 전달해줘도 괜찮을까요?

2022-10-21 09:23 UTC, sejineeee commented
`babel.config` 파일에 `runtime: 'automatic'`을 추가하고, import react를 생략하였습니다. 
Todo와 TodoItem의 이름이 헷갈릴 수 있다는 피드백을 듣고 생각해보았는데, Todo가 필요할지 먼저 생각이 들었고, 없이 App 컴포넌트에서 작성하는 방향으로 수정하였습니다. 감사합니다!! 😁

2022-10-22 04:46 UTC, daadaadaah commented on src/components/App.jsx
> +      <Todo />
페이지를 만들고 싶다면,  저라면 TodoPage로 할 것 같아요!
만약, 페이지 컴포넌트 없이 가고 싶다면, 말씀하신대로 App 컴포넌트에서 각 컴포넌트로 props로 전달해주는 방법도 괜찮구요!ㅎㅎ

2022-10-22 04:49 UTC, daadaadaah approved these changes
이번주 한주도 수고 많으셨습니당!ㅎㅎ회고를 통해 한주를 되돌아보는 시간을 가져봅시당!ㅎㅎ👊

2022-10-22 04:49 UTC, daadaadaah commented on src/components/App.jsx
> +    setTodo({
각각 한줄씩 띄어주는게 좋을 것 같아요!ㅎㅎ

2022-10-22 04:49 UTC, daadaadaah commented on src/components/App.jsx
> +        onClick={handleClick}
데이터는 데이터끼리, 함수는 함수끼리 정렬해주는게 좋을 것 같아요!ㅎㅎ

2022-10-23 06:04 UTC, sejineeee commented
리뷰 반영하여 props를 데이터는 데이터끼리, 함수는 함수끼리 정렬하였습니다.
각각 한 줄씩 띄우는 부분은 if문과 구분해서 띄워야 되는 것인지 setState 함수를 띄워야 되는 것인지, 모두 띄워야 되는 것인지 알지 못하여, setState 함수만 띄워 수정하였습니다!!
또한 주말 공부방에서 윤석님께 약간의 코드 리뷰를 도움 받아서, 수정해보았습니다!! 이번 한 주도 감사합니다!!! 🥰

2022-10-23 12:49 UTC, daadaadaah approved these changes

2022-10-25 12:38 UTC, merged