2주차 과제 - 간단한 Todo App 만들기
CodeSoom/week2-assignment-2 pull request #167
Opened 2022-12-13 11:40 UTC by naji0001

이번주도 잘 부탁드립니다!

2022-12-14 04:24 UTC, daadaadaah requested changes
과제1과 중복되는 피드백은 따로 하지 않았습니다!ㅎㅎ과제2하실 때, 과제1에서 드린 코멘트도 참고해주세요!

2022-12-14 04:24 UTC, daadaadaah commented on src/components/Input.jsx
> +      <button type="button" onClick={(eventObject) => onClick(eventObject)}>추가</button>
아래 코드처럼 props를 바로 주입해주는 방식으로 했을 때, 다르게 기능이 동작할까용?ㅎㅎ
```js
<input placeholder="할 일을 입력해 주세요" onChange={onChange} />
<button type="button" onClick={onClick}>추가</button>
```

2022-12-14 04:24 UTC, daadaadaah commented on src/components/List.jsx
> +            <Row key={todo} todo={todo} index={index} onClick={onClick} />
`key`를 좀더 유니크하게 관리하는 방법은 없을까요?

2022-12-14 04:24 UTC, daadaadaah commented on src/index.jsx
> +    e.target.previousSibling.value = '';
Input 창을 초기화 해주는 코드 같은데, `todoInput`을 활용해서 구현해보시는건 어떠신가요?

2022-12-14 04:24 UTC, daadaadaah commented on src/index.jsx
> +      todoList: [...todoList.slice(0, index), ...todoList.slice(index + 1)],
filter 함수를 이용해서도 구현하실 수 있습니다!

2022-12-14 12:38 UTC, naji0001 commented on src/components/List.jsx
> +            <Row key={todo} todo={todo} index={index} onClick={onClick} />
Date.now() 메서드를 이용해서 유니크하게 만들어봤습니다.

2022-12-14 12:42 UTC, naji0001 commented on src/index.jsx
> +      todoList: [...todoList.slice(0, index), ...todoList.slice(index + 1)],
쉬운방법 나두고 너무 어렵게 생각했네요 ㅎㅎ

2022-12-14 12:44 UTC, naji0001 commented on src/index.jsx
> +    e.target.previousSibling.value = '';
아직 useState에 익숙하지 않아서 거기까지 생각못했습니다. 수정했습니다!

2022-12-15 04:01 UTC, daadaadaah requested changes

2022-12-15 04:01 UTC, daadaadaah commented on src/App.jsx
> +    todoInput: '',
할일을 담는 데이터를`todoInput`이 아닌 객체로 관리해보시는 건 어떠신가요?

2022-12-15 10:22 UTC, naji0001 commented on src/App.jsx
> +    todoInput: '',
오.. 객체로 관리하니까
Row 컴포넌트를 생성할때 Date.now() key가 중복되는 문제가 있었는데 해결되었습니다.
`Date.now() + 할일`
`if (todoInput === '' || todoList.includes(todoInput)) return;`
중복 문제를 해결하려고 사용했었는데 이제 필요 없겠네요!
감사합니다!

2022-12-16 02:51 UTC, daadaadaah approved these changes
잘하셨어요!👏 피드백 강의를 보면 아샬님은 어떻게 하셨는지 잘 관찰하시고, 주간 회고를 통해 한주를 되돌아봅시당!ㅎㅎ 다음주도 같이 화이팅해봐요👊

2022-12-26 11:59 UTC, merged