과제 2 - 간단한 Todo App 만들기
CodeSoom/week2-assignment-2 pull request #168
Opened 2022-12-14 12:24 UTC by KwangMin-Moon

안녕하세요 트레이너님

아직 과제 진행 중입니다.

<질문>
List 컴포넌트에서 li 만들어 주는 부분을 함수로 빼려고 했는데 todo를 매개변수로 전달하려고 했는데 타입 지정이 안돼서 todo.length에서 
에러가 났습니다.  
List 컴포넌트에 props 넘겨준거 처럼 default parameters를 했는데도 unExpected token이라고 나오는데 어떤게 문제일까요?

2022-12-15 04:10 UTC, daadaadaah requested changes
> List 컴포넌트에 props 넘겨준거 처럼 default parameters를 했는데도 unExpected token이라고 나오는데 어떤게 문제일까요?

- 좀더 구체적인 상황과 에러를 스샷해주시면 답변하는데 도움될 것 같아요!

2022-12-15 04:10 UTC, daadaadaah commented on src/list.jsx
> +        ? todo.map((t, i) => (
`t`, `i` 보다 좀더 의미 있는 변수명을 사용해주세요!

2022-12-15 04:10 UTC, daadaadaah commented on src/todo.jsx
> +  const [todo, setTodo] = useState([]);
배열을 담고있는 변수이므로, 복수형이라는 의미를 드러내주시는 건 어떠신가요?

2022-12-15 04:10 UTC, daadaadaah commented on src/todo.jsx
> +  const [input, setInput] = useState('');
input 보다 좀더 의미 있는 변수명은 없을까요?

2022-12-15 12:20 UTC, KwangMin-Moon commented
코드리뷰 반영 및 기존 미구현사항 반영해서 push 했습니다!
위 질문은 오타로 인한 에러였어요ㅎㅎ

2022-12-16 02:49 UTC, daadaadaah requested changes

2022-12-16 02:49 UTC, daadaadaah commented on src/form.jsx
> +      <button>추가</button>
type 속성 삭제 하신 이유가 있으신가요?

2022-12-16 02:49 UTC, daadaadaah commented on src/list.jsx
> +const makeTodoList = (todos = [], onClick) => {
함수로 빼는 것보다 그냥 List 안에 넣는게 좀더 읽기 좋을 것 같아요!
아니면 할일 컴포넌트로 빼서 관리하시는 방법도 있구요!

2022-12-16 02:49 UTC, daadaadaah commented on src/todo.jsx
> +  const [todos, setTodos] = useState([]);
오! 변수명 너무 좋네용👍

2022-12-16 02:49 UTC, daadaadaah commented on src/todo.jsx
>    };
완료버튼을 눌렀을 때, 동작하는 함수이므로, 좀더 그 의도가 드러났으면 좋겠어요! 현재 네이밍으로는 `리스트를 클릭한다`고 해서, 그 동작이 어떤 걸 의미하는지 파악하기 어려운것 같아요!

2022-12-16 02:49 UTC, daadaadaah commented on src/todo.jsx
> +    unFinishedTodo.splice(index, 1);
불변 데이터를 관리하는 방법과 filter에 대해 공부해보시고, splice와 어떤 차이가 있는지에 대해 파악해보세요!

2022-12-16 02:49 UTC, daadaadaah commented on src/todo.jsx
> +  const onClickTodoList = (index) => {
`함수명`을 통일된 형태로 작성해보시는 건 어떠신가요?
위에는 `addTodo`로 작성했으면, 밑에 함수도 `동사+명사`로 작성해보시는 걸 추천드려요!

2022-12-16 11:01 UTC, KwangMin-Moon commented on src/form.jsx
> +      <button>추가</button>
type을 submit으로 하기 위해 지웠는데 type='submit'으로 해주는게 의도가 더 명확할거 같아요

2022-12-16 11:02 UTC, KwangMin-Moon commented
코드리뷰 반영해서 다시 push했습니다:)
이번주도 많이 배웠습니다
감사합니다:)

2022-12-17 05:58 UTC, daadaadaah approved these changes
이번 한주도 고생 많으셨어요!👏
다음주에도 같이 화이팅해봐여👊

2022-12-26 11:59 UTC, merged