과제 2-2
CodeSoom/week2-assignment-2 pull request #19
Opened 2020-06-13 10:14 UTC by aumilkyeong

진행하면서 가장 신경 쓰였던 부분은, 
제가 학습했던 state 관리법과 실제가 달랐던 것입니다.
https://ko.reactjs.org/docs/state-and-lifecycle.html
<img width="935" alt="Screen Shot 2020-06-13 at 7 11 13 PM" src="https://user-images.githubusercontent.com/33819896/84566123-bec6cf80-ada9-11ea-8da6-123555fbeab9.png">
새로운 state에서 필요한 변수만 독립적으로 변경하고자 했으나, 명시되지 않은 나머지 데이터가 
유실되는 문제가 생겼습니다. 제가 뭔가 잘못이해하고 하는 걸까요? 도와주세요 ㅠ

2020-06-13 10:15 UTC, aumilkyeong commented
부득이 setState에서 필요한 데이터만 명시하는 형태가 아닌 나머지 파라미터를 이용하여 데이터를 전달했습니다.

2020-06-13 10:50 UTC, wholemann commented
> 진행하면서 가장 신경 쓰였던 부분은,
> 제가 학습했던 state 관리법과 실제가 달랐던 것입니다.
> https://ko.reactjs.org/docs/state-and-lifecycle.html
> <img alt="Screen Shot 2020-06-13 at 7 11 13 PM" width="935" src="https://user-images.githubusercontent.com/33819896/84566123-bec6cf80-ada9-11ea-8da6-123555fbeab9.png">
> 새로운 state에서 필요한 변수만 독립적으로 변경하고자 했으나, 명시되지 않은 나머지 데이터가
> 유실되는 문제가 생겼습니다. 제가 뭔가 잘못이해하고 하는 걸까요? 도와주세요 ㅠ

지나가다가 comment 남깁니다ㅎㅎ 아래 문서를 잘 읽어보시면 답을 얻으실 수 있습니다.

- https://ko.reactjs.org/docs/hooks-state.html

2020-06-13 13:13 UTC, aumilkyeong commented
아... 결국 useState 훅을 이용하는 방식과 클래스를 이용하는 방식의 차이네요. 감사합니다 ㅎㅎ

2020-06-13 13:19 UTC, hannut91 requested changes

2020-06-13 13:19 UTC, hannut91 commented on src/component/App.jsx
> +    });
`push`함수는 `todos`의 배열을 직접 고치게 됩니다.`todos`를 직접 고치지 않고 새로운 상태로 전달하려면 어떻게 해야 할까요?

2020-06-13 13:19 UTC, hannut91 commented on src/component/App.jsx
> +    const newText = event.target.value;
`newText`에서 `new`가 의미하는 것이 무엇인가요?

2020-06-13 13:19 UTC, hannut91 commented on src/component/TodoList.jsx
> +}
`checkEmpty`라는 변수를 사용해서 표현력을 높이려고 하셨군요 ㅎㅎ 이럴 때는 이렇게 하시면 더 표현력이 좋을 것 같아요

```js
const isEmpty = (arr) => arr.length === 0;

if (isEmpty(todos)) {
   return '할 일이 없어요!';
}

return (
  <SingleTodo
      key={todo.id}
      todo={todo}
      handleTodoDone={handleTodoDone}
  />
);
```

2020-06-13 13:19 UTC, hannut91 commented on src/component/TodoList.jsx
> +import SingleTodo from './SingleTodo';
`SingleTodo`에서 `Single`이 의미하는바가 무엇인가요? 한 개라는 뜻인가요? `Todo`는 한 개 일까요 여러개 일까요?

2020-06-13 13:19 UTC, hannut91 commented on src/component/SingleTodo.jsx
> +      <button type="button" id={todo.id} onClick={handleTodoDone}>완료</button>
id 속성을 이용해서 구현해주셨군요! id는 html에서 유일해야 하기 때문에 만약 다른 데이터와 id가 겹치면 문제가 발생할 수 있어요. `id`없이 이 문제를 해결할 수 있을까요?

2020-06-13 13:19 UTC, hannut91 commented on src/component/App.jsx
> +    const newTodos = todos.filter((element) => element.id !== id);
`newTodos`에서 `new`가 의미하는 것이 무엇인가요?

2020-06-13 13:19 UTC, hannut91 commented on src/component/App.jsx
> +      id: '',
여기서 `id`속성이 없으면 어떻게 되나요?

2020-06-13 13:25 UTC, aumilkyeong commented on src/component/App.jsx
> +    });
이 부분은 빈 배열에 레스트 파라미터를 이용해서 할당해주면 되겠네요 ㅎㅎ 수정하겠습니다.

2020-06-13 13:25 UTC, aumilkyeong commented on src/component/App.jsx
> +    });
이 부분은 빈 배열에 레스트 파라미터를 이용해서 할당해주면 되겠네요 ㅎㅎ 수정하겠습니다.

2020-06-13 13:27 UTC, aumilkyeong commented on src/component/App.jsx
> +    const newText = event.target.value;
갱신할 텍스트라는 의미였는데 문맥상 불필요한것 같아요 ㅎㅎ 수정하겠습니다.

2020-06-13 13:41 UTC, aumilkyeong commented on src/component/TodoList.jsx
> +}
이 경우 제안해주신 코드가 라인이 더 짧기 때문인가요?

2020-06-13 13:42 UTC, hannut91 commented on src/component/TodoList.jsx
> +}
아니요. Guard clauses를 사용해서 표현했을 뿐입니다.

2020-06-13 13:42 UTC, aumilkyeong commented on src/component/TodoList.jsx
> +import SingleTodo from './SingleTodo';
네 단일 할일 항목을 표현하고 싶어서 선택한 어휘였는데 todoItem 정도가 적합할까요?

2020-06-13 13:43 UTC, hannut91 commented on src/component/TodoList.jsx
> +import SingleTodo from './SingleTodo';
Item이 어떤 의미를 가지고 있나요?

2020-06-13 13:43 UTC, aumilkyeong commented on src/component/App.jsx
> +    const newTodos = todos.filter((element) => element.id !== id);
이 경우 filteredTodos로 하면 의미가 더 명확해질 것 같아요. 수정하겠습니다.

2020-06-13 13:44 UTC, hannut91 commented on src/component/App.jsx
> +    const newTodos = todos.filter((element) => element.id !== id);
filtered가 무엇을 의미하나요?

2020-06-13 13:45 UTC, aumilkyeong commented on src/component/App.jsx
> +      id: '',
작동에는 영향이 없을 것 같은데, 추가할 때 뿅하고 갑자기 id 속성이 생기는 것보다는 할일 객체의 속성을 미리 망라해주는게 좋을 것 같아서 넣었어요. 제거하는게 더 나은 방향일까요?

2020-06-13 13:56 UTC, aumilkyeong commented on src/component/SingleTodo.jsx
> +      <button type="button" id={todo.id} onClick={handleTodoDone}>완료</button>
넵 인자를 직접 넘겨주는 방법으로 처리해야겠네요 수정하겠습니다.

2020-06-14 01:18 UTC, aumilkyeong commented on src/component/TodoList.jsx
> +import SingleTodo from './SingleTodo';
아하 단순히 todo면 된다라는 의미군요 이해했습니다. ㅎㅎ

2020-06-14 01:18 UTC, aumilkyeong commented on src/component/TodoList.jsx
> +}
이해했습니다 ㅎㅎ

2020-06-14 01:36 UTC, hannut91 requested changes

2020-06-14 01:36 UTC, hannut91 commented on src/component/App.jsx
> +    });
`filtered`라는게 무슨 의민지 잘 모르겠어요. inlineVariable 리팩터링을 해보는게 어떨까요? 

See also
  - https://refactoring.com/catalog/inlineVariable.html

2020-06-14 01:36 UTC, hannut91 commented on src/component/App.jsx
> +      },
여기서는 `id`가 안쓰이고 있어요.

2020-06-14 01:36 UTC, hannut91 commented on src/component/SingleTodo.jsx
> +      <button type="button" id={todo.id} onClick={() => handleTodoDone(todo.id)}>완료</button>
`id={todo.id}`는 이제 필요가 없을 것 같아요

2020-06-14 04:42 UTC, aumilkyeong commented on src/component/App.jsx
> +    });
반영 완료

2020-06-14 04:43 UTC, aumilkyeong commented on src/component/SingleTodo.jsx
> +      <button type="button" id={todo.id} onClick={() => handleTodoDone(todo.id)}>완료</button>
완료

2020-06-14 04:44 UTC, aumilkyeong commented on src/component/App.jsx
> +      },
그러네요 수정했습니다 ㅎㅎ

2020-06-14 11:16 UTC, hannut91 requested changes
주말까지 고생 많으시네요! 모호한 것 있으면 질문 남겨주시면 답변드리겠습니다!

2020-06-14 11:16 UTC, hannut91 commented on src/component/App.jsx
> +      id: '',
쓰이지 않는데 있는 건 더 헷갈릴 것 같아요. `TypeScript`를 사용해서 타입을 잡아주거나 모델을 만들어서 표현하는게 저는 더 좋을 것 같아요

2020-06-14 11:16 UTC, hannut91 commented on src/component/App.jsx
> +        handleTodoAdd={handleTodoAdd}
`handleChangeInput`이라는 이름은 핸들러 함수를 사용하는 곳에서만 사용되야 해요. 실제로 이 핸들러 함수를 어떻게 사용할지는 다르게 잡아줘야 해요. `InputPanel`에서 이 핸들러 함수를 어떻게 사용할지 더 명확하게 드러내줘야 합니다. 이 함수를 사용하는 입장을 생각해줘야 해요


`click`을 했을 때 이 함수를 실행하라고 하는 것 보다 우리가 읽을 때 ~~하면 ~~한다 라고 읽히는게 좋아요

이렇게 쓰는건 어떨까요? 

```js
<InputPanel onInputChange={handleChangeInput} />
```

2020-06-14 11:16 UTC, hannut91 commented on src/component/TodoList.jsx
> +  const isEmpty = (array) => array.length === 0;
나중에 이 함수를 사용하는 곳이 많아지면 util로 빼는 것도 좋을거에요

2020-06-14 11:22 UTC, aumilkyeong commented on src/component/App.jsx
> +        handleTodoAdd={handleTodoAdd}
오 좋은것 같아요 반영하겠습니다

2020-06-14 11:23 UTC, aumilkyeong commented on src/component/TodoList.jsx
> +  const isEmpty = (array) => array.length === 0;
그렇겠네요 ㅎㅎ

2020-06-14 11:49 UTC, aumilkyeong commented
@hannut91 저야말로 감사드립니다 ㅎㅎ 말씀해주신 부분들은 잘 이해가 갔습니다. 모델을 만들어서 표현한다고 하셨는데 현재 코드에 적용한다면 어떤식으로 표현이 될까요?

2020-06-14 12:06 UTC, hannut91 commented
타입을 잡아서 사용하면 됩니다. 그리고 그 타입을 가지고 새로운 todo를 만들 때 사용할 수 있어요

2020-06-14 12:08 UTC, aumilkyeong commented
클래스로 만들어서 사용하라는 의미인건가요?

2020-06-14 12:09 UTC, hannut91 commented
클래스를 사용할 수도 있지만 타입스크립트에서는 인터페이스를 많이 사용합니다

2020-06-14 12:12 UTC, aumilkyeong commented
감사합니다 ㅎㅎ 내일 올라올 아샬님 영상도 기대되네요

2020-06-14 13:25 UTC, hannut91 commented
고생하셨습니다 ㅎㅎㅎ 이번 과제를 진행하면서 무엇을 배우셨나요? 좋았던 점이나 아쉬웠던 점이 있으신가요?

2020-06-14 13:25 UTC, merged