Implement TodoList
CodeSoom/week2-assignment-2 pull request #2
Opened 2020-06-08 12:26 UTC by daadaadaah

리뷰 요청 부탁드립니다!

2020-06-09 00:00 UTC, hannut91 requested changes

2020-06-09 00:00 UTC, hannut91 commented on src/TodoList.jsx
> +}
3항 연산자를 읽기 어렵죠? 이럴 때는 위에서 바로 `return`을 해도 괜찮아요

```js
if (todos.length === 0) {
  return '할 일이 없어요!';
}
```

혹은

```js
const isEmpty = (arr) => arr.length === 0;

if (isEmpty(todos)) {
  return '할 일이 없어요!';
}
```

2020-06-09 00:00 UTC, hannut91 commented on src/TodoList.jsx
> +function TodoList({ todos, handleRemoveTodo }) {
`export default`를 바로 써줘도 됩니다.

2020-06-09 00:00 UTC, hannut91 commented on src/TodoList.jsx
> +import TodoItem from './TodoItem';
위에 한 줄로 비어주세요.

2020-06-09 00:00 UTC, hannut91 commented on src/TodoList.jsx
> +            const key = index + 1;
`index`를 키로 사용하시면 안됩니다. 키로 사용하게 되면 순서가 바뀌거나 중간에 값이 바뀌면 오작동할 수 있어요. 

See also
  - https://reactjs.org/docs/lists-and-keys.html

2020-06-09 00:00 UTC, hannut91 commented on src/TodoItem.jsx
> +    <li style={liStyle} key={index}>
여기서는 `key`를 사용하지 않아요

See also
  - https://reactjs.org/docs/lists-and-keys.html

2020-06-09 00:00 UTC, hannut91 commented on src/Title.jsx
> +function Title() {
`export default`를 바로 써줘도 될 것 같아요

2020-06-09 00:00 UTC, hannut91 commented on src/App.jsx
> +    todos.splice(indexTodo - 1, 1);
`splice` 메소드는 `todos`를 직접 고치고 있어요. 직접 수정하지 않고 이 문제를 해결하려면 어떻게 해야 할까요?

2020-06-09 00:00 UTC, hannut91 commented on src/App.jsx
> +  const handleRemoveTodo = (indexTodo) => {
`indexTodo`에서 `Todo`를 빼면 어떻게 되나요?

2020-06-09 00:00 UTC, hannut91 commented on src/App.jsx
> +
여기 빈 줄이 하나 더 있네요

2020-06-09 12:00 UTC, hannut91 requested changes

2020-06-09 12:00 UTC, hannut91 commented on src/App.jsx
> +        id: new Date().getTime(),
오 유니크한 이름을 만들기 위해 시간을 사용하셨군요! 더 유니크하게 만들고 싶으면 UUID를 사용할 수 있습니다.

2020-06-09 12:00 UTC, hannut91 commented on src/TodoItem.jsx
> +      <button type="button" onClick={() => handleRemoveTodo(todo.id)}>
`TodoItem`에서 버튼을 클릭했을 때 어떤 동작을 할지 결정하고 있어요. 버튼이 클릭 됐을 때 어떤 동작을 할지는 이 컴포넌트가 결정하지 않아야 해요. 이 `TodoItem` 컴포넌트를 사용하는 컴포넌트가 어떻게 동작할지 결정해야 해요

2020-06-09 14:32 UTC, daadaadaah commented on src/TodoItem.jsx
> +      <button type="button" onClick={() => handleRemoveTodo(todo.id)}>
TodoItem의 재사용성을 위해 TodoList가 TodoItem이 무엇을 보여줄지, 어떤 역할을 해야할지 결정해야 된다!!!ㅎㅎㅎ

2020-06-10 00:21 UTC, hannut91 approved these changes
고생하셨습니다! ㅎㅎ 벌써 통과하셨네요!

2020-06-10 02:32 UTC, daadaadaah commented
수고하셨습니다~~ㅎㅎ

2020-06-12 05:47 UTC, merged