과제 2-2 리뷰 요청드립니다
CodeSoom/week2-assignment-2 pull request #20
Opened 2020-06-13 15:27 UTC by amorfati0310

할 일을 입력해서 등록하고, 완료할 수 있는 간단한 To-do 리스트를 만들어주세요.

### 기능 구현

- [ ] 사용자는 할 일을 입력할 수 있습니다.
- [ ] 사용자는 추가 버튼을 눌러서 할 일을 추가할 수 있습니다.
- [ ] 사용자는 할 일 목록을 볼 수 있습니다.
- [ ] 사용자는 완료 버튼을 눌러 할 일을 삭제할 수 있습니다.

### 제한 조건

- [ ] if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- [ ] switch는 사용하실 수 없습니다.
- [ ] let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- [ ] 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- [ ] indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

###  점검사항

- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.

### 스크린샷 

![스크린샷 2020-06-14 오전 12 22 54](https://user-images.githubusercontent.com/25189066/84572556-c9975980-add5-11ea-824b-b5978f9ae4fb.png)

2020-06-14 02:15 UTC, hannut91 requested changes

2020-06-14 02:15 UTC, hannut91 commented on src/components/TodoList.jsx
> +        const { id, todoText } = todo;
파라미터를 바로 디스트럭처링 해도 될 거에요

`todoList.map(({ id, todoText }) => { ... })`

2020-06-14 02:15 UTC, hannut91 commented on src/App.jsx
> +        todoText,
`todo`의 `text`를 의미하니 `todoText`라고 이름을 지으신 것 같아요. 만약의 사람의 나이를 나타내려고 할 때 둘 중에 어떤게 더 좋을까요? 
```
Person.age

Person.personAge
```

2020-06-14 02:15 UTC, hannut91 commented on src/App.jsx
> +  const deleteTodo = (deleteTodoId) => {
위에 빈 줄 하나를 추가해서 구분해주면 좋을 것 같아요

2020-06-14 02:15 UTC, hannut91 commented on src/App.jsx
> +  };
삭제할 `Todo`의 `id`를 나타내기 위해 `deleteTodoId`라고 하신 것 같아요. 삭제하기 위해 이 메소드를 호출할 떄 둘 중에 어떤게 더 나아 보이시나요?

```
deleteTodo(deleteTodoId);

deleteTodo(id);
```

2020-06-14 02:15 UTC, hannut91 commented on src/App.jsx
> +  );
GuardClauses리팩터링을 실시하면 이렇게 될 것 같아요

```js
const isEmpty = (arr) => arr.length === 0;

if (isEmpty(todoList)) {
  return <div>입력 된 할 일이 없습니다.</div>;
}

return <TodoList todoList={todoList} onClick={deleteTodo} />;
```

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-06-14 02:15 UTC, hannut91 commented on src/App.jsx
> +        completed: false,
`completed`는 사용되지 않고 있네요. 사용되지 않는 속성은 삭제하는게 어떨까요?

2020-06-14 15:05 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 과제를 진행하시면서 어떤 것을 배우셨나요? 좋았던 점이나 아쉬운 점이 있으신가요?

2020-06-15 14:27 UTC, amorfati0310 commented
> 고생하셨습니다 ㅎㅎ 과제를 진행하시면서 어떤 것을 배우셨나요? 좋았던 점이나 아쉬운 점이 있으신가요?

리뷰 넘 감사합니다. 

좋았던 점 
- 컴포넌트 분리하는 관점 (Presentational and Container Components) 로직과 
props만 전달 받아서 렌더하는 부분으로 나눠면 관심사 분리적인 면에서 재사용성 가능한 컴포넌트를 만들기 유리한면을 더 와닿게 되었다. 
- 리뷰 받으면서 하니 안정감이 든다 같이 하는 느낌 
- GuardClauses 에 배워서 좋았다.
- uuid나 propTypes 적용해본게 좋았다. -> propTypes array나 object를 
그냥 쓰면 걸리는데 더 구체적으로 쓰게 하는 옵션이 있는 걸 처음 알게 되었다. 
-> 조금 이라도 공부하고 이용해봐야지 많이 배울 수 있다. 

아쉬웠던 점 
- e2e test 실패했는데 _ㅇ 실행하는데 동작은 잘 되서 나중에 알아봐야지 하다가 우선순위에 밀려서 못 고쳤다. 
- todo의 text를 의미하니 todoText 전반적으로 naming에 더 신경 써야 겠다 
- 수정, 삭제 추가 구현을 더 해보고 싶었는데 못했다. 
- React 별로 공부를 못하고 거의 강의 듣고 나온 것만 이용해서 했다.  -> useEffect, ... 성능 및 다른 부분도 더 적용해보면 좋을 것 같다.

2020-06-15 17:23 UTC, amorfati0310 commented on src/App.jsx
> +        todoText,
`Person.age` 전자가 좋을 것 같습니다

2020-06-15 17:28 UTC, amorfati0310 commented on src/App.jsx
> +        completed: false,
이 부분은 추가로 update랑 edit 등을 작업해보려고 했었는데  기능이랑 같이 추가하는게 좋겠네요

2020-09-06 14:46 UTC, merged