[2주차|과제2] 간단 to-do 리스트 만들기 코드 리뷰 부탁드립니다.
CodeSoom/week2-assignment-2 pull request #22
Opened 2020-06-13 18:15 UTC by jiunkoo

첫 번째 과제를 토대로 작업했습니다.

2020-06-14 02:04 UTC, hannut91 requested changes
컴포넌트의 파일명은 PaskalCase로 작성합니다. 근데 지금 파일명을 변경하게 되면 CI에서 파일을 인식하지 못해 에러가 발생하니 변경하지는 마시고, 다음번에 파일이름은 PaskalCase로 작성해주세요

2020-06-14 02:04 UTC, hannut91 commented on src/app.jsx
> +  const [todoList, setTodoList] = useState(null);
`null`은 아에 존재하지 않는다는 것을 의미하는데 지금 보면 `todoList`라는 배열을 나타내려고 하는 것이니 배열의 가장 원시적인 기본값은 `[]`빈 배열이에요

2020-06-14 02:04 UTC, hannut91 commented on src/app.jsx
> +    const newTodoList = [...todoList.slice(0, index), ...todoList.slice(index + 1, length)];
`todoList`에서 특정 `index`를 제외하는 거죠? `filter`를 쓰면 어떨까요?

2020-06-14 02:04 UTC, hannut91 commented on src/app.jsx
> +export default App;
`export default function`을 사용하시면 이 줄을 작성안해도 될 것 같아요

2020-06-14 02:04 UTC, hannut91 commented on src/app.jsx
> +  const [todoList, setTodoList] = useState(null);
그리고 `todoList`의 `List`는 데이터 자료형을 나타내는 것 같아서 다른 이름을 사용하는게 좋을 것 같아요. `List`를 안쓰면서 여러개임을 나타내는 이름을 사용하는건 어떨까요?

2020-06-14 02:04 UTC, hannut91 commented on src/todoComplete.jsx
> +}
```js
if (isEmpty(todoList)) {
  return '할 일이 없어요!';
}

return (
  <div>
    ... 
  </div>
)
```

이렇게 표현하면 3항 연산자 없이 더 간단하게 표현할 수 있을거에요

2020-06-14 02:04 UTC, hannut91 commented on src/todoComplete.jsx
> +        <div key={String(index)}>
`index`를 이용해 key를 사용하면 각 요소들을 수정하거나 삭제했을 때 vDOM이 제대로 추적할 수 없어 의도치 않게 동작할 수 있습니다. 

See also
  - https://reactjs.org/docs/lists-and-keys.html

2020-06-14 02:59 UTC, jiunkoo commented
1. uuid 사용해서 key 매핑
2. 완료한 todo 제외할 때 slice에서 filter 사용
3. function App(){} -> export default function App(){} 변경
4. todoList -> todos로 변수명 변경 및 초기화 값 변경

위와 같이 작업했습니다.

2020-06-14 11:33 UTC, hannut91 requested changes

2020-06-14 11:33 UTC, hannut91 commented on src/app.jsx
> +      handleTodoChange={handleTodoChange}
`handleTodoChange`라는 함수 이름은 이 함수에서만 유효한 것에요. 어떤 이벤트에 대해서 처리를 해줄 것 이라는 것을 나타내고 있어요. 하지만 `Page`라는 함수안에서는 그 의미가 통하지 않습니다. `Page`에서 저것을 어떻게 사용하는지 더 고민을 해보는게 좋을 것 같아요. 만약에 이렇게 한다면 어떤 변화가 있을까요?

```js
<Page onTodoChange={handleTodoChange} />
```

2020-06-14 11:33 UTC, hannut91 commented on src/app.jsx
> +    const newTodos = (todos === []) ? [todo] : [...todos.flat(), todo];
여기서 `flat`은 어떤 의도로 사용하신건가요?

2020-06-14 11:33 UTC, hannut91 commented on src/app.jsx
> +    const newTodos = todos.filter((t) => t !== todos[index]);
이렇게 비교하시면 의도치 않은 결과가 나올 수 있어요. 동등성과 동일성을 구분해야 하는데 동등성이란 같은 것을 참조하는지를 나타내고 동일성이란 그 값이 실제로 같은지를 나타내는거에요. 예를들면

```js
const yunseok = {name: '윤석'};
const yunseok2 = {name: '윤석'};

console.log(yunseok === yunseok2); // false;
console.log(yunseok.name === yunseok.name) // true;
```

사람의 이름이 중복된 것이 없다고 가정한다면

yunseok 과 yunseok2는 사실 같은 사람인데 비교하면 다른 사람이라고 나오죠. 지금 같은 상황에서
todo에서도 같은 문제가 발생할 것 같아요

2020-06-14 15:05 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 과제를 진행하시면서 어떤 것을 배우셨나요? 좋았던 점이나 아쉬운 점이 있으신가요?

2020-06-14 15:51 UTC, jiunkoo commented
좋았던 점 : 코드 리뷰 자체가 좋습니다. 일반적인 강의처럼 제출이 끝이 아니라 과제의 피드백을 받을 수 있기 때문에 제가 모르고 있던 습관을 개선해 나갈 수 있어서 좋았습니다.

 또한 코드 리뷰 시간이 정해져서 좋습니다. 지난 1주차 과제에서 아쉬운 점으로 말씀드렸던 코드리뷰-피드백 부분이 개선되어 시간이 정해지니 한결 더 편하게 제출할 수 있었습니다.

아쉬운 점 : 강의를 보고, 과제를 이해한 후 코드를  제출하기까지 어느 정도의 시간이 꼭 필요해서 코드 리뷰를 매일 받을 수 없는 게 아쉽습니다. 물론 코드 리뷰 자체는 일주일 내내 열려 있지만, 학습이 제 마음처럼 빨리 이루어지지는 않으니...

 또한 코드 리뷰 시간이 정해져 있기는 한데, 리뷰를 하신 후 제가 곧바로 확인하기 힘든 점이 아쉽습니다. 예를 들어 7~10시 사이 리뷰가 이루어지면 저는 시간을 두고 11~12시 즈음 리뷰가 되었는지 확인합니다.

보통 강사님께서 학생의 코드 리뷰를 한 그 순간에 가장 코드에 대한 이해력이 높으실 것이고, 코드 리뷰 시간이라 답장도 빠를텐데 그 순간에 곧바로 소통하지 못하는 건 아쉽네요.

2020-06-15 01:49 UTC, jiunkoo commented
[2주차 과제에 관해]
좋았던 점 : 모호했던 리액트에 대한 개념을 좀 더 확실하게 알 수 있었습니다. '리액트는 컴포넌트 기반으로 재사용이 가능한 라이브러리이다'라는 문구에서, 저는 '재사용'에 집중해 반드시 중복되는 것만 컴포넌트로 작성해야 한다고 생각했습니다. 이번에 과제를 진행하면서 처음에 index.js에 모든 코드를 작성하고 하나씩 컴포넌트로 분리를 해보니까 제 생각과는 다르다는 걸 알게 되었습니다.

 다만 무조건적인 분리가 능사는 아니었던게 자잘한 버튼이랑 input을 컴포넌트로 전부 분리했더니 한 가지를 수정하기 위해 봐야하는 코드가 너무 많았습니다. 결국 너무 잘게 쪼개지 않기로 하고 다시 합쳤는데, 수정할 때 건드려야 하는 최소한의 코드 뭉치가 컴포넌트라는 생각이 들었습니다.

아쉬운 점 : input을 어떻게 처리해야 할까...그 생각을 가장 오래했던 것 같습니다. input에 name을 지정하고 DOM 객체에 직접 접근해서 처리하는 방식은 곧잘 떠오르는데, 그 외의 방식은 잘 떠오르지 않았습니다. 버튼은 사용자가 클릭할 때 함수를 실행한다면 input은 사용자가 입력할 때 함수를 실행하면 된다는 걸 깨닫기까지 시간이 많이 걸렸습니다. 어떻게 보면 기본적인 이벤트 처리인데 너무 많은 시간을 낭비한 건 아닌가, 아쉬움이 드네요.

2020-06-28 10:36 UTC, jiunkoo commented
시간이 조금 지났지만 리팩토링 했습니다. 확인 후 merge 부탁드립니다!

2020-06-29 01:03 UTC, hannut91 commented
완벽하네요 ㅎㅎㅎ 고생하셨습니다!

2020-06-29 01:03 UTC, merged