[Draft] Make Simple TODO App
CodeSoom/week2-assignment-2 pull request #27
Opened 2020-09-21 13:11 UTC by gringrape

2020-09-21 16:30 UTC, Kihyun92 commented
오 벌써 PR을 올리셨군요~ 시작이 반이라는데 월요일에 두번째 과제까지 시작하시다니 좋습니다! 👍

2020-09-22 12:17 UTC, gringrape commented
## 작업 내용
- [ ] 할 일을 입력받는다.
- [ ] 할 일을 입력받아 화면에 띄운다.

2020-09-22 13:16 UTC, gringrape commented
## 작업 계획
- 이후에 다음을 진행할 계획 입니다.
1. 컴포넌트를 각 관심사에 맞게 추출
2. 완료버튼 구현

2020-09-22 15:30 UTC, Kihyun92 requested changes
하나의 컴포넌트에서 모든 기능을 수행하려고 하다보니 로직이 복잡해지는 것 같습니다. 한번 기능별로 컴포넌트를 분리해보고 하나하나 기능을 추가해보는건 어떨까요?

그리고 id로 쓸만한 값으로 date를 추가하신건 좋습니다! 다만 key가 변하는게 걱정이 되시면 id값 자체를 상태로 관리해도 좋을 것 같아요~

2020-09-22 15:30 UTC, Kihyun92 commented on src/App.jsx
> +  );
많이 복잡해보이네요. 그럴땐 분리를 해보는게 좋습니다 :)

2020-09-22 15:40 UTC, gringrape commented
@Kihyun92 아 네 작업계획에 썼는데 전달이 잘안되었네요 ㅎ 이후에 컴포넌트 분리를 할 예정입니다. :) 피드백 감사합니다 :)

2020-09-23 00:26 UTC, gringrape commented
## 컴포넌트 구분
![UI](https://user-images.githubusercontent.com/53764714/93950342-37143800-fd7e-11ea-9439-dfa8a25d398d.jpg)

- **UpdatableTodoList**: 어플리케이션의 상태를 관리
- **Form**: user input 을 처리
- **TodoList**: 할일 목록을 렌더링
- **TodoItem**: 할일 하나를 렌더링

2020-09-23 04:12 UTC, gringrape commented
## 고민한 것
### 상태를 변화시키는 함수가 handleClick, handleSubmit 과 같은 로직을 갖는 것이 적절한가?
[관심사의 분리 - 위키백과](https://ko.wikipedia.org/wiki/%EA%B4%80%EC%8B%AC%EC%82%AC_%EB%B6%84%EB%A6%AC#:~:text=%EC%BB%B4%ED%93%A8%ED%84%B0%20%EA%B3%BC%ED%95%99%EC%97%90%EC%84%9C%20%EA%B4%80%EC%8B%AC%EC%82%AC%20%EB%B6%84%EB%A6%AC,%EC%9D%98%20%EA%B4%80%EC%8B%AC%EC%82%AC%EB%A5%BC%20%ED%95%B4%EA%B2%B0%ED%95%9C%EB%8B%A4.&text=%EA%B4%80%EC%8B%AC%EC%82%AC%20%EB%B6%84%EB%A6%AC%EB%A5%BC%20%EC%9D%B4%EC%9A%A9%ED%95%98%EB%A9%B4,%EC%A0%95%EB%8F%84%EC%9D%98%20%EC%9E%90%EC%9C%A0%EA%B0%80%20%EC%83%9D%EA%B8%B4%EB%8B%A4.)

위에서 관심사의 분리를 달성하는 수단을 이렇게 말하고 있습니다.

> 관심사의 분리는 정보를 잘 정의된 인터페이스가 있는 코드 부분 안에 캡슐화시킴으로써 달성한다

리액트에서 하나의 모듈을 컴포넌트라고 보면, 현재는 파라메터를 통해 넘겨주는 것이 인터페이스 역할을 한다고 생각했습니다.
App Component 에서 보면 onClick, onSubmit 과 같은 함수가 현재 존재하는데, 이부분이 마치 자식 컴포넌트가 어떻게 구성되어있는지 알고 있다. 라는 생각이 들었고, 인터페이스인 파라메터 부분 이외에도 자식 컴포넌트 정보가 존재해서 캡슐화가 이루어지지 않는다고 생각했습니다.

2020-09-23 15:17 UTC, Kihyun92 requested changes
관심사의 분리에 대해서 정말 많은 고민을 해보신 것 같아요!! 💯 

답은 없겠지만, 제 생각엔 지금과 같은 구조로 된다면 기능 수정이 생겼을 경우엔 하나의 파일이 아니라 연결된 의존성을가지는 여러 파일들을 보고 수정하고, 다른 영향도는 없는지 체크해보는 비용이 발생할 것 같아요. App컴포넌트에서 기능을 모두 처리한다면 App파일만 수정하면 될 것 같구요ㅎㅎ

2020-09-23 15:17 UTC, Kihyun92 commented on src/App.jsx
> +    <UpdatableTodoList
UpdatableTodoList라는 컴포넌트 명을 사용하신 이유를 알려주세요~ 개인적으로는 간결하고 명확한 네이밍을 선호하는데 이렇게 길 필요가 있을까 라는 생각이 들어서요

2020-09-23 15:17 UTC, Kihyun92 commented on src/App.jsx
> +        name: newTask,
name 대신 title이라고 하는건 어떨까요?

2020-09-23 15:17 UTC, Kihyun92 commented on src/App.jsx
> +  };
말씀하신 관심사 분리 측면에서 딱 기능에 맞는 함수 네이밍을 하는 것도 좋지만, event handler convention 관점에서 `on~~={handle~~}`과 같은 네이밍을 추천드려요.

참고: https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2020-09-23 15:22 UTC, gringrape commented on src/App.jsx
> +    <UpdatableTodoList
@Kihyun92 좀 긴가요 ㅎㅎ;; 추가, 삭제가 가능한 TodoList 라는 뜻으로 붙였습니다. 하위 컴포넌트들을 다 포괄하는 이름이라고 생각해서요.

2020-09-23 15:27 UTC, gringrape commented on src/App.jsx
> +  };
@Kihyun92 아 이건 첫째주에도 들었던 피드백이네요. 이름 지을때, convention 을 찾아보고 했어야 하는데..
읽어보고 고쳐보겠습니다. 감사합니다!

2020-09-23 15:49 UTC, Kihyun92 commented on src/App.jsx
> +    <UpdatableTodoList
개인적으로 제가 네이밍에 -able을 잘붙여보질 않아서 그럴수도 있을것 같네요.

2020-09-24 11:48 UTC, gringrape commented
## 작업 계획
### 1. 상태 관리 함수 이름변경
이름을 convention 에 맞도록 수정

> (on/handle) + subject + event -> Ex) handleCountChange



### 2. 컴포넌트 이름 수정
[컴포넌트 이름 convention 참고자료](https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364)

아래와 같이 적용

> 페이지 or 상위 컴포넌트 / (하는일 보충 설명) / 컴포넌트 타입

ex) Todo + AddToList + Form -> TodoAddForm

2020-09-24 13:03 UTC, gringrape commented
### 작업 주안점
계획처럼 이름변경을 주로 진행했습니다.
컨벤션의 규칙에 따르면서 한눈에 읽기 좋은 이름으로 컴포넌트, 함수, 변수의 이름을 변경하도록 했습니다.
변수이름을 변경하면서, task 를 todo 로 바꾸었습니다. 
task 와 todo 는 같은 것을 가리키고 있으므로, 서로다른 이름은 불필요한 혼란이라고 생각했습니다.

2020-09-24 14:52 UTC, Kihyun92 requested changes
많은 고민을 하면서 과제를 하는게 느껴집니다 👍 
이렇게 잘해주시니 아마 마지막 피드백이 될지도 모르겠네요 ☺️

2020-09-24 14:52 UTC, Kihyun92 commented on src/TodoAddForm.jsx
> +        onChange={(e) => onChange(e.target.value)}
```suggestion
        onChange={onChange}
```
라고만 처리하고 App의 핸들러에서 e를 매개변수로 받아와 처리하는건 어떨까요?

2020-09-24 14:52 UTC, Kihyun92 commented on src/TodoAddForm.jsx
> +  };
인풋 폼 영역에서 처리할 필요가 있을까요?
만약 제출 기능 수정이 필요해 졌다면 어떤 처리가 필요해 질까요?

2020-09-24 14:52 UTC, Kihyun92 commented on src/TodoList.jsx
> +  );
list가 비었을때도 고민해 보셨네요~ 좋아요 👍 
다만 개인적으론 조건문은 `if (todos.length === 0) {` 과 같이 조금 더 명확하게 처리해줄 것 같습니다~

2020-09-24 14:52 UTC, Kihyun92 commented on src/App.jsx
> +    }
이 부분은 빈 문자열을 입력했을 경우에 대한 방어로직이 맞을까요?
그렇다면 입력을 받는 Form쪽에 버튼에 `disabled={!value}`와 같이 애초에 버튼이 안눌리도록 처리하는건 어떨까요?

2020-09-25 13:00 UTC, gringrape commented on src/App.jsx
> +    }
@Kihyun92 이건 정말 확다르네요. 사용자에게 불가능한 동작을 직접 알려준다는 점에서 훨씬 좋은것 같습니다.

2020-09-25 13:08 UTC, gringrape commented on src/TodoAddForm.jsx
> +        onChange={(e) => onChange(e.target.value)}
이 부분은 조금 더 생각해보겠습니다. 의도는 확실히 파악된 것 같습니다.

저는 '상태 업데이트' 와 '이벤트 핸들링' 을 분리 시켜서 상태업데이트는 App 에서 수행하고 
하위 컴포넌트에서 이벤트 핸들링을 할때, 상태업데이트를 의존성을 불러와서 처리하는 것을 관심사의 분리로 생각했고,

트레이너님은 둘을 분리시키지 않고 '이벤트 핸들링' 함수 로직을 모두 App에 모으고,
하위 컴포넌트에서, 이벤트 핸들러를 의존성으로 처리하는것을 관심사의 분리로 생각하신것 같습니다.

확실히, 이벤트 핸들러 로직이 한군데 모여 있는편이 더 심플할 것 같다는 생각이 듭니다.
굳이 상태 업데이트와 이벤트 핸들링을 분리해서 생각할 이유가 있나 생각도 들구요.
조금더 생각해 보겠습니다. ㅎ
감사합니다!

2020-09-26 14:15 UTC, Kihyun92 requested changes
좋습니다~ 전반적으로 명확하지 않은 네이밍이나 불필요한 기능들이 없는지 마지막으로 한번 돌아보면 될 것 같네요 :)

2020-09-26 14:15 UTC, Kihyun92 commented on src/App.jsx
> +  const handleNewTodoChange = (source) => {
함수명에 new는 빼도 되지 않을까요? 없어도 명확한것 같습니다~
그리고 매개변수가 source라고 되어있으니, 뭐가 전달되는건지 알기 어려운 것 같네요

2020-09-26 14:15 UTC, Kihyun92 commented on src/App.jsx
> +  const handleTodosAdd = () => {
함수 네이밍이 handleAddTodos와 같은 순서가 되는건 어떨까요?

2020-09-26 14:15 UTC, Kihyun92 commented on src/App.jsx
> +    newTodo: '',
newTodo보다는 todoTitle이라고 하면 어떨까요?

newTodo라고 하니 왠지 todo 객체가 들어올 것 같네요.

2020-09-26 14:15 UTC, Kihyun92 commented on src/TodoListItem.jsx
> +export default function TodoListItem({ index, title, onClick }) {
컴포넌트명에 List는 빠져도 될 것 같습니다 ~

2020-09-26 14:15 UTC, Kihyun92 commented on src/TodoListItem.jsx
> +      .
HTML 태그를 사용해서 표현하면 좋겠네요~ 불필요한 index를 넘겨줄 필요가 없을 것 같습니다

2020-09-26 14:15 UTC, Kihyun92 commented on src/TodoListItem.jsx
> +      <button type="button" onClick={onClick}>완료</button>
```suggestion
      <button type="button" onClick={onClick}>
        완료
      </button>
```

2020-09-27 06:37 UTC, gringrape commented on src/App.jsx
> +  const handleTodosAdd = () => {
그러네요 ㅎ Todos 가 목적어네요. 네이밍 컨벤션에선 (on/handle) + **subject** + event 라고 말하고 있지만, 여기서는 add to todos 가 되어서 목적어니, handle + addToTodos 나 handleAddTodos 가 더 자연스럽네요. 네이밍 컨벤션을 도입할때도, 일괄적이 아니라, 생각을 더 해야되는군요..!

2020-09-27 06:41 UTC, gringrape commented on src/App.jsx
> +    newTodo: '',
이것도 반영하겠습니다.

2020-09-27 07:09 UTC, gringrape commented on src/App.jsx
> +  const handleTodosAdd = () => {
고민이 되네요. 컨벤션 통일성을 유지하고 싶긴한데, handleTodosAdded? handleTodosPushed?

2020-09-27 07:22 UTC, gringrape commented on src/TodoListItem.jsx
> +export default function TodoListItem({ index, title, onClick }) {
html 태그명에서 list 안에 들어있는 아이템을 <li> 로 list item 으로 부르기도 하고,
상위 컴포넌트가 TodoList 라 좀 더 명확하게 해주었는데, Item 이면 list item 이라고 생각되는것 같군요.

2020-09-27 07:30 UTC, gringrape commented on src/TodoListItem.jsx
> +      .
ordered list 를 활용하면 되겠네요. html tag 로 간단하게 활용할 수 있는 방법들을 먼저 찾아보는게 좋겠군요.

2020-09-27 07:52 UTC, gringrape commented
## 작업 회고
### 1. 컴포넌트는 초기에 설계를 했으면 좋겠다.
일단 구성요소를 다 만들어놓고 추출하는 방식보다 화면 레이아웃을 통해 컴포넌트 설계를 먼저 하는 방식이 더 효율적인것 같습니다. 설계가 일단 있으면 해당 설계를 바탕으로 구현해가면서 수정이 이루어지기 때문에, 부분적 구현을 하면서도 전체적인 어플리케이션 고려를 잃지 않는것 같습니다.

### 2. 관심사의 분리의 목적은 유지보수의 편리함
관심사의 분리에 대해 생각하면서 여러가지 지식을 얻었지만, 생산적이지는 못했다고 생각합니다.
논리적으로 무엇이 옳고 무엇이 그른지 판단하기 보다, 실제로 변경해보고 어떤 것이 더 좋은지 경험해보는것이
더 효율적이었겠다는 생각이 듭니다. 

### 3. guard clause, 함수를 통한 가독성 향상
guard clause 를 쓰는것으로 어떤 의도로 코드를 작성했는지 작성하고,
value.length === 0 을 isBlank 와 같이 쓰는 것으로 코드의 의미를 명시적으로 전달하면,
주석없이도 읽기 좋은 코드가 만들어지는 것 같습니다.
어떤것이 읽기 좋은 코드냐? 하면 명확한 예제같은 것이 떠오르지 않았는데,
이제 조금씩 생겨가는 것 같습니다.

### 4. html tag 를 활용하자
tag 는 div 만을 사용하고 나머지는 자바스크립트의 기능으로 어떻게든 해보려는 생각이 많았던것 같습니다.
생각보다 html tag 로 손쉽고 확실하게 처리하는 방법이 있는것을 느꼈고, mdn 을 부지런히 열어서
사용할 수 있는 태그와 속성을 확인해야 겠다고 생각했습니다.

2020-09-27 14:45 UTC, Kihyun92 approved these changes
이번주도 고생하셨습니다~! 👍

2020-10-05 13:05 UTC, merged