[과제2] 투두 앱 만들기 (9춸 21일 작업분)
CodeSoom/week2-assignment-2 pull request #28
Opened 2020-09-21 14:19 UTC by juunini

# 기능 구현
- [x] 사용자는 할 일을 입력할 수 있습니다.
- [ ] 사용자는 추가 버튼을 눌러서 할 일을 추가할 수 있습니다.
- [ ] 사용자는 할 일 목록을 볼 수 있습니다.
- [ ] 사용자는 완료 버튼을 눌러 할 일을 삭제할 수 있습니다.

2020-09-21 15:55 UTC, hannut91 commented
브렌치를 사용하시는게 인상적이네요 ㅎㅎ 계속 진행해주세요!

2020-09-23 12:50 UTC, juunini commented
# 오늘 작업 내용
- To-do 리스트를 추가하는 기능
- To-do 리스트를 보여주는 기능
- To-do 완료를 누르면 제거되는 기능

# 새로 알게된 것
- array함수 중 filter를 알게 됨

2020-09-23 16:52 UTC, hannut91 requested changes

2020-09-23 16:52 UTC, hannut91 commented on src/App.jsx
> +  }
e는 UI 이벤트인데 `handleChange`는 상태를 변경해주는 함수이니까, UI 이벤트변수를 여기서 처리하지 않는게 좋을 것 같아요. 왜냐하면 UI와 강하게 결합되기 때문입니다. 이 함수는 단순히 주어진 상태로 변환시키는 일만 하면 될 것 같아요

2020-09-23 16:52 UTC, hannut91 commented on src/App.jsx
> +    list: [],
`list`는 어떤 값인지 가늠하기가 어렵습니다. 이 값들이 어떤 것을 나타내는지 더 표현해주면 좋을 것 같아요

2020-09-23 16:52 UTC, hannut91 commented on src/App.jsx
> +    input: '',
`input`도 이 값이 나타내는 것이 무엇인지 더 표현해주면 좋을 것 같아요

2020-09-23 16:52 UTC, hannut91 commented on src/App.jsx
> +      list: list.indexOf(input) === -1 ? [...list, input] : list,
단순히 존재하는지만 보고 싶으시다면 `includes`를 쓰는건 어떨까요?

See also
  - https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2020-09-23 16:52 UTC, hannut91 commented on src/components/TodoList.jsx
> +}
Guard clauses를 사용하면 없는 경우와 있는 경우를 더 명확하게 의도를 드러낼 수 있을거에요.

```js
const isEmpty = (arr) => arr.length === 0;

function TodoList({ list, onClick }) {
  if (isEmpty(list)) {
    return <p>할 일이 없어요!</p>;
  }

  return (
    <div>
      <TodoItems
        list={list}
        onClick={onClick}
      />
    </div>
  );
}
```

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-24 11:24 UTC, juunini commented on src/App.jsx
> +  }
이벤트 함수에서 UI 이벤트를 직접 건드리면 서로 강하게 결합되게 되어서 컴포넌트에서 사용할 때 넣도록 의도해야 하는군요
전혀 생각하지 못했는데 말씀 듣고 곰곰히 생각해보니 불필요하게 사용자가 공급자에 대한 의존성을 가지게 되는 안좋은 흐름이었다는걸 알게되었습니다.

2020-09-24 11:46 UTC, juunini commented on src/components/TodoList.jsx
> +}
경우가 두가지라서 `? :` 조건연산자를 쓰면 좋을줄 알았는데 오히려 guard clauses 를 이용하니 더 심플하고 의도도 명확하게 표현이 되었습니다.

2020-09-24 11:55 UTC, juunini commented
# 오늘 한 일
- `TodoList` 컴포넌트에 조건연산자 대신 guard clauses를 이용하였습니다.
- indexOf 대신 includes 함수를 이용하였습니다.
- state의 parameter 변수명을 변경하였습니다.
  - `input` -> `todoInputValue`
  - `list` -> `todoList`

# 알게된 것
- javascript의 includes 함수를 알고있었지만 전혀 쓸 생각을 하지 않았구나 하는걸 깨달았습니다.
  - 4년 전에 웹 퍼블리셔로 일하던 당시 includes 함수를 쓰니 IE에서 동작하지 않았던 트라우마가 있었던 것 같습니다.
- 역시나 '이름'은 더 정확하게. 뭐하는건지 더 자세하게.
- jsx 표현식 내에서 조건연산자를 쓰니 코드의 가독성이 떨어진다는걸 깨달았습니다.
  - guard clauses는 "이것도 아니고, 저것도 아니고, 그것도 아니고, 다 치우고나서 남는걸로" 같은 느낌으로 써야한다는 강박같은게 있었는데, 더 의도를 명확하게 표현할 수 있으면 뭘 쓰든 그쪽이 더 좋구나 라는걸 깨달았습니다.

2020-09-24 15:01 UTC, hannut91 requested changes

2020-09-24 15:01 UTC, hannut91 commented on src/App.jsx
> +    todoInputValue: '',
`todo`를 입력하는 값을 나타내기 때문에 `todoInputValue`라고 하신 것 같아요. 이 상태를 나타내는 값은 UI에서 어떻게 표현할지는 전혀 상관이 없어요. 우리가 가지고 있는 상태란 본질적으로 무엇인지에 대해서 더 고민해보시면 좋을 것 같아요

2020-09-24 15:01 UTC, hannut91 commented on src/App.jsx
> +    todoList: [],
todo의 목록을 나타내기 위해서 `List`라는 이름을 붙이신 것 같아요. 근데 실제로 여기의 자료형은 배열입니다.
어떤 단어의 복수형을 사용하면 변수의 이름만 봐도 여러개라는 것을 바로 드러낼 수 있을거에요.

2020-09-24 15:01 UTC, hannut91 commented on src/App.jsx
> +        : todoList,
조건문에 부정문이 들어가면 읽기가 훨씬 어려워요. 특별한 상황이 아니라면 긍정문을 사용하는게 좋을 것 같아요

2020-09-24 15:01 UTC, hannut91 commented on src/App.jsx
> +        : todoList,
제 생각에는 여기도 Guard clauses를 사용하는게 단순해 보여요. 의도도 더 명확하게 드러낼 수 있을 것 같아요
```js
if (todoList.includes(todoInputValue)) {
  return;
}

setState({
  todoList: [...todoList, todoInputValue],
  todoInputValue: '',
});
```

2020-09-24 15:01 UTC, hannut91 commented on src/components/TodoList.jsx
> +        list={list}
list는 아무런 의도도 드러내지 않아요. 어떤 데이터인지 이름으로 의도를 드러내면 좋을 것 같아요

2020-09-25 02:53 UTC, juunini commented on src/App.jsx
> +        : todoList,
어흑 저도 부정문 쓰면서 "아닌게 아닌게 아니라..." 하는 느낌이어서 이건 아닌 것 같은데 하는 기분이 들긴 했습니다 ㅠㅠ

2020-09-25 11:14 UTC, juunini commented on src/App.jsx
> +    todoList: [],
items 라고 이름을 변경했습니다.

사용하면서 이게 투두 리스트인지 뭔지 이게 알 필요가 있을까?
그냥 아이템 여러개라는 의도를 전달하고 각자가 받아서 사용만 하면 되지 않을까?

하는 생각을 하면서 고쳤는데 이 생각이 맞는건지 사실 확신이 없습니다.

2020-09-25 11:15 UTC, juunini commented on src/components/TodoList.jsx
> +        list={list}
이 부분도 위와 마찬가지로 items로 바꿨습니다.

이 컴포넌트가 받은게 아이템들이지 더 알 필요가 있을까 하는 생각을 하며 변경했습니다.

2020-09-25 11:34 UTC, juunini commented on src/App.jsx
> +    todoInputValue: '',
`typingValue` 라는 이름으로 수정했습니다.
입력중인 값 이라는 의미를 내포하고싶어서 어떻게 할까 하면서 번역기도 돌려보고 했지만 마땅한 좋은 단어가 떠오르질 않더라구요...

사실 state의 변수명들을 어떤 기준으로 지어야하는지 정확한 이해를 못하고있다는 생각이 듭니다.

2020-09-25 11:41 UTC, juunini commented
# 오늘 작업 내용
- 부정문 조건연산자를 guard clause로 리펙토링 하였습니다.
- `TodoItems`컴포넌트를 제거하였습니다.
  - 꼭 필요한가 하는 느낌이 들어서 제거했습니다.
- `todoList`와 `list` 라고 지어진 변수명을 `items` 로 변경하였습니다.
- `todoInputValue` 를 `typingValue` 로 변경하였습니다.

# 생각중인 것
- state에 parameter로 들어가는 변수명을 어떤 기준으로 지어야 하는지 정확한 기준이 없다보니 혼란스럽습니다.
  - 각각의 컴포넌트를 묶어서 사용하는 부분에서 (여기서는 App 컴포넌트) UI가 어떻게 생긴지 알아야 하는가 몰라도 되는가...
  - 아는지 모르는지에 따라 변수명이 달라져야 하는가

2020-09-25 16:06 UTC, hannut91 requested changes

2020-09-25 16:06 UTC, hannut91 commented on src/App.jsx
> +    typingValue: '',
사용자가 입력해서 저장한 값이라서 tpingValue인 것 같아요. 우리가 가진 상태를 리액트가 화면에 보여주고, 이벤트를 처리해주는 역할을 해줍니다. UI로부터 우리가 상태를 저장하는게 아닙니다.

만약 todo가 브라우저를 종료하더라도 삭제되지 않도록 한다고 가정해보면, 그래도 여전히 typingValue가 적절할까요?

2020-09-26 02:36 UTC, juunini commented on src/App.jsx
> +    typingValue: '',
너무 생각이 한곳에 묶여있었던 것 같은데 트레이너님의 말을 듣고 묶인 틀에서 풀어진 느낌이 들었습니다.
투두리스트 앱이 꼭 웹으로만 보여질 필요도 없고, 그게 커맨드 라인일수도, 핸드폰 앱일수도, 화이트보드일수도, 머릿속일수도 있는데
제 눈에 보이고있는 웹 인터페이스에만 생각이 묶여 `typingValue` 라고 했습니다.

state가 저장하는건
그저 '추가하려고 하는 것' 과
'추가가 완료된 것들' 인데 너무 틀에 묶여 이상한 방향으로 가고있지 않았나 하는 생각이 듭니다.
(거기까지 생각이 도달했지만 여전히 이름짓기는 어렵군요 ㅠㅠ)

감사합니다.

2020-09-26 10:17 UTC, juunini commented
# 오늘 작업 내용
- `typingValue`를 `currentValue`로 수정했습니다.

# 생각중인 것
- 만들고 있는 것이 웹 브라우저에서 보여지는게 아니라 다른 것이라면, 키보드로 입력하는게 아니라면, 전부 배제하고 어떤 기능을 할 지만 집중해야 한다는걸 책에서 듣고, 말로 듣고 해도 역시나 잘 되지 않는구나 라고 느끼고 있습니다.

2020-09-26 15:56 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 좋은 코드의 작성은 좋은 이름으로부터 시작한다는걸 배우셨길 바랍니다 ㅎㅎ

2020-09-26 15:56 UTC, hannut91 commented
이번 과제를 진행하면서 좋았던 점과 아쉬웠던 점이 있었다면 무엇이 있을까요? 좋았던 것은 어떻게 유지하고 아쉬웠던 것은 어떻게 개선하고 싶으신가요?

2020-09-27 04:31 UTC, juunini commented
좋았던 점이라면 계속 머릿속으로만 생각하고 있던
_'웹 인터페이스에만 묶인 사고를 하지 말아야 한다'_
라는걸 강렬하게 다시 경험하게 되어 좋았습니다.

아쉬운 점은 알긴 알고있지만 여전히 머리와 손은 그렇게 움직여주지 않는다는 점이죠 ㅠㅠ

왕도는 없는 것 같습니다.
끊임없이 이 점에 대해 인지하고 의식하고 잊어버리지 않고 많이 반복적으로 해보는게 유일한 방법 아닐까 라고 생각하고 있어요.

2020-09-27 13:55 UTC, merged