To-do list 구현하기 (미완성)
CodeSoom/week2-assignment-2 pull request #29
Opened 2020-09-22 02:39 UTC by bbhye1

### **간단한 To-do 리스트 만들기**

### **구현 기능**

- [ ] - 할 일 입력받기
- [ ] - 추가버튼을 누르면 할 일 추가되기 - 추가후에는 인풋창 초기화
- [ ] - 할 일 DOM에 리스트업해서 보여주기
- [ ] - 추가된 할일이 없으면 '할 일이 없어요!' 문구 DOM에 보여주기 
- [ ] - 완료버튼을 누르면 해당 할일을 삭제한뒤 다시 DOM에 나머지 할일들 리스트업해서 보여주기

2020-09-22 13:28 UTC, bbhye1 commented
### **중간 구현 내용**

처음에 index.jsx에 구현할 최종 UI를 먼저 디자인해주고 차근차근 파일을 하나씩 분리해갔습니다. 
App 컴포넌트에서 todoItems데이터를 관리를 해주고 Todo컴포넌트는 DOM화면에 보여지는 컴포넌트들로 구성했습니다.

최대한 컴포넌트의 재사용을 고려해서 이름을 짓고 안에 들어갈 속성이나 내용물들을 다 유동적으로 변경가능하도록 만들었습니다. 그러다보니 한가지 아쉬운점이 있었는데 그 부분이 바로 button의 type을 설정하는 부분입니다. 처음에는 inputBox 컴포넌트를 Form이라고 이름짓고 form태그를 이용해서 submit이 된다면 input창이 초기화되고 value가 todoItems로 저장될 수 있도록 하는 것이 계획이었는데 그렇게 하면 다른 button을 타입으로 가지고 있는 버튼들과 type이 달라지게 됩니다.  이 부분 뿐만 아니라 새로 Button 컴포넌트를 재사용할 때 type값은 또 달라질 수 있기 떄문에 이걸 props속성으로 받아서 type을 정해주고 싶었습니다. 하지만 eslint에서 type 속성은 정적인 값만을 받기 때문에 오류가 생깁니다. 검색능력부족으로(영어부족도 한몫합니다ㅜㅜ) 이걸 해결하지 못하고 결국 button의 속성을 button으로 통일하게 되면서 컴포넌트 이름과 코드들이 달라지게 되어서 아쉬움이 많이 남습니다. 이 점을 해결할 방법이 있을까요?? 결국 form과 함께 사용하려면 새로 submit button을 만들어 주어야만 하는건가요?? 아니면 현업에서는 form태그보다 혹시 지금처럼 버튼속성을 가진 버튼을 사용해서 submit을 하는지 궁금합니다. 

 todoItems 배열안에 오브젝트가 들어있는 구조로 추가 버튼을 누를때는 배열에 오브젝트가 추가되고 완료 버튼을 누르면 filter로 제거한뒤 오브젝트의 id값을  다시 정렬시켜서 새로 추가되는 오브젝트의 아이디와 충돌이 일어나지 않도록 했습니다. 처음에는 단지 배열만으로 동일한 값을 가진 배열값을 삭제해주도록 만들었는데 혹시 중복되는 값이 있다면  하나만 삭제해도 filter로 모두 걸러지는 문제가 있기 때문에 고유한 id를 문자열로 만들고 그것으로 데이터를 걸러내고 li들의 key값으로도 지정해주었습니다.
원래 key값에는 보통 인덱스로 지정하는것을 권장하지 않지만 데이터가 계속 추가되고  이전 데이터와 다음 데이터의 아이디가 충돌되면 안되기 때문에 데이터들의 순번을 매기는것이 중요하다고 생각해서 배열의 인덱스값을 id에 문자열로 함께 넣어주었습니다.  

 대부분 재사용과 각자 가지고 있는 고유한 기능들을 고려해서 컴포넌트들을 나눴는데  Todo컴포넌트는 App의 상태값이 아닌 다른 상태값과 함께 쓰인다면 재사용이 쉽다고 생각해 상태값을 관리하는 App컴포넌트와 분리를 해주었는데 InputBox 컴포넌트의 경우 Input과 Submit 버튼은 value값을 관리해주는 기능과 분리해서는 사용이 어렵다고 생각해 굳이 분리시키지는 않았습니다. 이렇게 기준을 나누어서 어디는 컴포넌트를 나누고 어디는 나누지 않고 해도 괜찮을까요? 의도적으로 하긴 했지만 일관성이 없어보일 수도 있을거 같아 어떤 방향이 좋은지 조언을 받고 싶습니다.

2020-09-22 17:25 UTC, Kihyun92 requested changes
많은 고민을 해보신 것 같아 보는 내내 가슴이 웅장해졌습니다..☺️

일단 filter이용해서 제거하는 부분 좋네요~ 다만 배열로 처리하다보니 조금 복잡해보입니다. 혹시 상태값들을 객체로 관리하면 어떻게 될까요? 한번 고민해보셔도 좋을 것 같아요~

그리고 InputBox에서 상태를 관리하는 부분 잘 봤습니다. 고민이 많으실 것 같아요 ㅎㅎ 실제로 많은 사람들이 상태관리에 대해서 고민하고, 그렇기에 Redux라던지 Mobx 등이 나오는거구요. 시간이 되신다면 상태관리 라이브러리들에 대해서 찾아보셔도 좋을 것 같습니다 :)
지금 같은 경우에는 가능하면 App 컴포넌트에서 모든 상태관리를 하는게 좋지 않을까 생각이 듭니다~ 그 이유는 InputBox에서 독립적으로 상태관리를 하는게 아니라, 어차피 App에서 내려받는 함수를 사용해야하는 의존성이 있어보여서 추후 기능 수정이 필요할 경우 App 컴포넌트만 보는게아니라 다른 곳도 수정해야하는 번거로움이 생길 것 같네요~

추가로 현업에서는 form 태그를 사용하는지 아니면 버튼 속성을 가진 버튼을 사용해서 처리하는 지 물어보셨는데, 상황에 따라 다른 것 같아요 ㅎㅎ; 근데 대부분 form으로 감싸서 사용하는 것 같습니다 ㅎㅎ

답변이 됐을지 모르겠네요~~ 잘못된 피드백 같다면 편하게 말씀주세요 :)

2020-09-22 17:25 UTC, Kihyun92 commented on src/Input.jsx
> +    <input type="text" placeholder={placeholder} value={value} onChange={(e) => onChange(e)} />
```suggestion
    <input type="text" placeholder={placeholder} value={value} onChange={onChange} />
```
event의 경우 직접 넘기지 않아도 넘어갑니다~

2020-09-22 17:25 UTC, Kihyun92 commented on src/App.jsx
> +    <Todo addTodoItem={addTodoItem} todoItems={todoItems} removeSelectedTodo={removeSelectedTodo} />
`onClick={handleClick}` 과 같이 event handler convention을 맞춰주세요~ 다른 파일들도 수정해주세요:)

참고: https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2020-09-22 17:25 UTC, Kihyun92 commented on src/Todo.jsx
> +import TodoList from './TodoList';
```suggestion
import React from 'react';

import InputBox from './InputBox';
import TodoList from './TodoList';
```

공백 추가해주세요~ 모듈 간에 역할이 다르기 때문에 관심사를 분리하는 것 처럼 구분해두는 습관을 가지면 좋습니다~ 추후 임포트하는게 많아질 경우 편리하구요 :)

다른 파일들도 동일하게 처리해주세요~

2020-09-22 17:25 UTC, Kihyun92 commented on src/TodoList.jsx
> +  );
```suggestion
  return (
    <ul>
      {todoItems.length === 0 ? <p>할 일이 없어요!</p> : (
        todoItems.map((item) => (
          <TodoItem
            item={item}
            removeSelectedTodo={removeSelectedTodo}
            key={item.id}
          />
        ))}
      </ul>
    )
  );
```
 이렇게 처리하는게 좋아보입니다.

2020-09-23 00:49 UTC, bbhye1 commented on src/App.jsx
> +    <Todo addTodoItem={addTodoItem} todoItems={todoItems} removeSelectedTodo={removeSelectedTodo} />
상위 컴포넌트에서 onClick={~} 과 같이 넘겨주게 된다면 onClick이벤트들이 많아진다면 어떻게 해야하나요?? 그부분이 궁금합니다!

2020-09-23 06:33 UTC, bbhye1 commented
상태관리를 App컴포넌트에서 한번에 해주기 위해 value도 App컴포넌트로 올려주었습니다.  확실히 조언해주신대로 상태를 관리하는 부분은 한 곳에서 이루어 지고 조금 먼 컴포넌트들에게는 상태관리 라이브러리들을 이용해서 전달해주는것이 효율적으로 보이는것 같습니다. 상태관리 라이브러리를 자세히 공부해봐야할것같습니다!

나머지 부분들도 수정을 했는데 제가 리뷰받은 부분에 이해가 안가는 부분이 있어서 질문을 드립니다. 상태값들을 배열이 아닌 객체로 관리한다는 건 `const todoItems = [{ todo: '첫번째 할일', id: 'todo1' }, { todo: '두번째 할일', id: 'todo2' }]; ` 현재 이렇게 관리 되고 있는 것을 배열이 아닌 완전히 객체만 사용한 형태로 말씀하시는 건가요?? `const todoItems ={ todo1 : '첫번째 할일',   todo2: '두번째 할일'};` 이런 형태거나  `const todoItems = { todoItems: { todo1: '첫번째 할일', todo2: '두번째 할일' } };` 이런 구조를 구조를 말씀해주신건가요?? 
객체로 할 경우 객체들의 순서나 이 객체가 다른 추가되는 객체와 다른 객체라는걸 어떤 방법으로 구분할지를 모르겠습니다 ㅜㅜ;;;;  여기서 데이터 구조를 아무리 고민해봐도 배열의 인덱스를 활용하는 방법이나 Math.random()을 이용해서 다른 값을 부여해주는 방법밖에 떠오르지가 않네요(물론 이것도 완전히 구분하는 방법이라고 생각이 안됩니다) ㅜㅜ ;;;; 힌트를 조금 주실수는 없으실까요;;  

그리고위에서 질문드렸듯이 Form 태그 사용을 위해서는 button의 속성을 변경해주는것이 불가피한데 button에 속성을 전달해주어 적용시켜줄 방법이 있을까요?? 새로운 버튼컴포넌트를 만드는 방법밖에는 없을까요??

2020-09-23 06:46 UTC, bbhye1 commented on src/App.jsx
> +    <Todo addTodoItem={addTodoItem} todoItems={todoItems} removeSelectedTodo={removeSelectedTodo} />
`onNameEvent={handleNameEvent}`이렇게 처음에 이벤트함수를 엄겨주고 계속해서 아래로 물려줄땐 `onNameEvent={onNameEvent}` 요렇게 물려주면 되는 건가요??  그렇게 변경해서 적용했는데 지금 변경해서 추가한 방식이 맞는지 궁금합니다!

2020-09-23 15:19 UTC, Kihyun92 commented on src/App.jsx
> +    <Todo addTodoItem={addTodoItem} todoItems={todoItems} removeSelectedTodo={removeSelectedTodo} />
넵 맞습니다 ㅎㅎ

2020-09-23 15:33 UTC, Kihyun92 requested changes
아 상태값을 객체로 관리하면 어떻겠냐고 말씀드린 부분은, 
```javascript
const [state, setState] = useState({
  inputValue: '',
  id: 0,
  todoItems: [
    { },
  ]
});
```
요론 구조를 말했던 거였습니다 ㅎㅎ

많은 고민을 해보신것 같아요. 너무 잘하고 계십니다!
슬랙으로 정보를 잘 주고 받는것 같아 좋네요:)

2020-09-23 15:33 UTC, Kihyun92 commented on src/Todo.jsx
> +function Todo({
이 컴포넌트의 네이밍을 Todo로 한 이유가 있을까요? 어떤 역할을 하는데 Todo가 됐을까요?

2020-09-23 15:33 UTC, Kihyun92 commented on src/TodoForm.jsx
> +      </Button>
굳이 컴포넌트로 따로 추출할 만큼 기능이 많진 않아보입니다. 재사용 측면에서도 그렇구요.

컴포넌트를 재사용하는건 좋지만, 왠지 복잡해지고 예외처리가 추가되고 한다면 그 경우에는 적절하지 않은 경우라고 생각합니다~

button도 그냥 쓴다면 type="submit"이면 될것 같구요 :)

2020-09-24 00:59 UTC, bbhye1 commented on src/Todo.jsx
> +function Todo({
처음에는 TodoForm과 TodoList를 묶어준 상위 컴포넌트라고만 생각해서 Todo라고만 이름을 지었습니다. 다시보니 약간 의미가 애매모하네요;;;  그래서 과제 1과 마찬가지로 페이지를 구성해주는 컴포넌트의 역할로 이름을 Page로 수정해주었습니다!

2020-09-24 01:08 UTC, bbhye1 commented on src/TodoForm.jsx
> +      </Button>
아아 그렇군요! 컴포넌트를 나눌 때 항상 그 부분을 고려해봐야겠네요.

2020-09-24 09:29 UTC, bbhye1 commented
### **중간 구현 내용**

-  Todo컴포넌트의 이름을 Page로 변경해주었습니다. Page라는 이름이 컴포넌트들을 묶어서 최종 화면에 구현해줄 페이지라는 의미를 내포하고 있다고 생각합니다. 
- submit기능을 하는 버튼을 버튼 컴포넌트가 아닌 그냥 하드코딩으로 작성해주었습니다. 버튼의 button속성을 가지고 있다면 여기서는 아니지만 다른 버튼이 추가될 때 각각 다른 click이벤트핸들러 함수들이 들어올 수 있다고 생각해 버튼컴포넌트 자체는 삭제하지 않고 사용했습니다. 
-  state의 구조자체를 조언해주신 것을 참고삼아서 변경해봤습니다. (저는 처음에 배열자체를 사용하지 말라는 말로 이해해서 오해가 있었어요 ㅜㅜ;; 

** 질문 사항**
 상태값을 객체로 관리하다보니 의문이 듭니다. 지금 같이 todoItems 와 value밖에 변경하는 값들이 없는 상황에서 굳이 하나의 객체로 관리하는 이유가 무엇일까요?? 여기서는 상태들을 하나의 객체로 묶으니 value와 todoItems는 어떻게 보면 연동되어 있지 않은 각각의 상태인데 하나를 변경해줄 때마다 전체구조가 다 변경되는 번거로움이 있는거 같기도 합니다.(예를 들어 `setInputValue( event.target.value)` 이런 코드를  `setState({ inputValue: event.target.value, todoItems })` 이렇게 작성해야 한다는 점입니다.) 상태값들이 많아지면 코드가 장황하게 길어져 가독성이 떨어지는 것 말고 다른 특별한 더 있는지도 궁금합니다! 
 컴포넌트를 쪼개다보니상태관리 컴포넌트에서 props들로 데이터를 물려줄 때 (특히 버튼컴포넌트로 이벤트핸들러 함수를 전달해줄때) 많은 불편함을 느꼈습니다. state이름 하나만 고쳐도 줄줄이 다 고쳐줘야 가독성이 좋아지고 이게 무슨값을 전달받은걸까 확인하려면 연어마냥 자꾸 상위컴포넌트를 하나씩 거슬러올라가야 한다는 일이 엄청난 피로감과 시간낭비로 몰려오더라구요;; 상태관리의 라이브러리의 필요성을 크게 느껴서 갈증을 해결하고자 조금씩 리덕스에 대한 공부를 먼저 시작하고 있습니다. 여기서 느낀건데 상태의 객체 구조가 리덕스에서 상태 구조와 비슷해서 지금 간단한 코드에서도 이걸 미리 익혀두는것을 연습하는 의도가 담겨있지 않을까 하는 생각도 들었습니다ㅎㅎ

사실 Todo리스트가 구현하는게 그리 복잡한 코드는 아닌데 생각할 거리를 정말 많이 안겨주고 앞으로 나아가게 만드는 코드 인 것같아요. 구현 할 다른 방법들이 궁금해지면 자주 슬랙에 얘기나눠야겠습니다!

2020-09-24 15:18 UTC, Kihyun92 requested changes
항상 많은 고민을 해주셔서 제가 드린 피드백보다 더 많은걸 받아들여주시는것 같아요~ 👍

매번 새벽에 리뷰를 달다보니 피드백의 상태가 좋지 못한점 양해 부탁드립니다 😭 
좋지 못한 피드백이 있다면 편하게 피드백 해주세요~!

2020-09-24 15:18 UTC, Kihyun92 commented on src/App.jsx
> +  }
오히려 더 불편해진게 아닌가 라는 고민을 해보신게 너무 좋습니다 :) 장단점이 있지만, 제가 말씀드린 부분은 하나의 상태로 관리가 가능하다는 것과, es6 spread 문법을 이용하면 고민하신 부분들이 조금 수월하게 해결된다는 점때문이었습니다 ㅎㅎ
```suggestion
  function handleInputChange(event) {
    setState({
      ...state,
      inputValue: event.target.value
    });
  }
```
굳이 state를 한번 더 써줘는거면 똑같이 불편하다라고 생각할 수 있지만, 이렇게 처리함으로써 이 함수에서 신경쓸 필요 없는 다른 값들은 그대로 가져오고, 신경써야하는 inputValue값만 event.target.value로 업데이트 해줄 수 있다는 점이 장점이지 않을까요? :)

2020-09-24 15:18 UTC, Kihyun92 commented on src/TodoItem.jsx
> +      <Button onClick={() => onDoneButtonClick(item)}>
클릭 함수로 id 값만 넘겨도 되지 않을까요?

2020-09-24 15:18 UTC, Kihyun92 commented on src/App.jsx
> +
공백이 추가된것 같아요~ 제거 부탁드립니다.

2020-09-24 15:18 UTC, Kihyun92 commented on src/App.jsx
> +    if (!inputValue.trim()) return;
이 부분은 공백이 입력됐을때 방어하는 로직같아요~

애초에 버튼이 눌리지 않도록 disabled 하는건 어떨까요?

2020-09-25 01:20 UTC, bbhye1 commented on src/TodoItem.jsx
> +      <Button onClick={() => onDoneButtonClick(item)}>
처음에 App 컴포넌트에서 ` item.id !== selectedItem.id` 이렇게 비교해주는게 더 명시적이지 않을까 해서 그렇게 했었는데 onDoneButtonClick(item.id) 로 넘겨주고 handleDoneButtonClick(selectedItemId) 로 받으면 더 보기 편한 코드가 되네요! ㅎㅎ 감사합니다.

2020-09-25 01:22 UTC, bbhye1 commented on src/App.jsx
> +    if (!inputValue.trim()) return;
앗 생각지도 못한 방법이었습니다! 좋은 방법 알려주셔서 감사합니다! :)

2020-09-25 12:33 UTC, Kihyun92 requested changes
ol 태그로 변경하는건 저도 놓친 부분인데, 잘 처리해주신것 같습니다 👍

2020-09-25 12:33 UTC, Kihyun92 commented on src/App.jsx
> +  function handleDoneButtonClick(selectedItemId) {
매개변수의 네이밍을 조금 수정하면 어떨까요? 이 함수에서 알 필요없는 정보들이 있는 것 같아요ㅎㅎ

함수명도 button은 없어도 될 것 같습니다. 이 함수입장에서는 어떤걸 클릭하는지는 중요치 않은 것 같아서요. 어떤가요?

2020-09-25 12:33 UTC, Kihyun92 commented on src/TodoItem.jsx
> +function TodoItem({ item, onDoneButtonClick }) {
```suggestion
function TodoItem({ item: {todo, id}, onDoneButtonClick }) {
```
이렇게 한번 더 destructuring을 할 수 있을 것 같네요 :)

2020-09-25 12:44 UTC, bbhye1 commented on src/App.jsx
> +  function handleDoneButtonClick(selectedItemId) {
그럼 함수명이 handleDoneClick(ItemId) 이렇게 되는걸까요?? 저도 button은 처음에 넣을까 말까 고민했던 부분이긴한데 보통 그런 태그 이름은 넣지 않는편인가요?? 버튼이 아니라 a 태그거나 그래도 상관이 없다는 말씀이신거죠?

2020-09-25 12:47 UTC, bbhye1 commented
> ol 태그로 변경하는건 저도 놓친 부분인데, 잘 처리해주신것 같습니다 👍

다시 코드를 보다가 저도 놀라서 변경했습니다. 이런 html 기초를 놓치다니 ㅜㅜㅜ;;; 조만간 html도 다시 가볍게라도 살펴봐야할거같아요.

2020-09-26 10:35 UTC, bbhye1 commented
### **변경 사항**

- TodoItem 함수의 파라미터 Item을 디스트럭쳐링 해주었습니다. 
- handleDoneButtonClick 함수의 이름과 매개변수 이름을 변경해 주었습니다. 지금 이 클릭 핸들러는 무엇을 클릭하는지가 중요한것이 아니라 완료가 되는 무언가를 클릭한다는 의미가 중요한것같아 Done은 남겨 준 채로 handleDoneClick 로 변경해 주었고 이 함수의 매개변수명이 filter함수에서 item의 id와 비교 대상으로 들어오는 것이므로  selectedItemId에서 의미만 남겨서 선택한 id라는 의미로 selectedId로 변경했습니다

2020-09-26 14:24 UTC, Kihyun92 commented on src/App.jsx
> +  function handleDoneButtonClick(selectedItemId) {
저라면 `handleClickDone(id)`라고만 할 것 같아요~
혹은, 이 함수의 역할을 보면 id가 일치하는 todo를 찾아서 상태값에서 제거하고 있으니, `handleClickDeleteTodo(id)`와 같이 할 수도 있겠네요 :)

말씀하신대로입니다~ button, selected와 같은 명칭은 굳이 이 함수에서 알 필요 없는 정보들이죠 ㅎㅎ

처음부터 완벽한 코드를 만들 순 없는 것 같아요~ 그리고 네이밍에 정답은 없다고 생각합니다. 지속적으로 돌아보고 개선해가는거죠.☺️

2020-09-26 14:32 UTC, Kihyun92 requested changes
좋습니다~
마지막으로 불필요한 로직은 없는지, 명확하지않은 네이밍은 사용하고 있지 않은지 확인해보시면 좋을 것 같네요👍

2020-09-26 14:32 UTC, Kihyun92 commented on src/App.jsx
> +    inputValue: '',
input의 값인지는 알 필요 없는 것 같고, value라는 네이밍도 명확하지 않는 것 같네요. 여기엔 결국 추가될 todo의 값이 들어오기 때문에, todoTitle이라고 하는건 어떨까요?

2020-09-26 14:32 UTC, Kihyun92 commented on src/App.jsx
> +  }
이 함수들도 Input을 핸들링하는건지 알 필요가 있을까요🤔 App컴포넌트 내에서 이 함수들이 어떤 역할을 하는지를 표현해주는건 어떨까요?

2020-09-26 14:32 UTC, Kihyun92 commented on src/App.jsx
> +      value={inputValue}
속성 명을 value로 넘기는건 별로 좋지 않은 것 같습니다~

2020-09-26 14:32 UTC, Kihyun92 commented on src/Input.jsx
> +    <input type="text" placeholder={placeholder} value={value} onChange={onChange} />
```suggestion
    <input
      type="text"
      placeholder={placeholder}
      value={value}
      onChange={onChange}
    />
```

2020-09-26 14:32 UTC, Kihyun92 commented on src/Page.jsx
> +      <TodoList todoItems={todoItems} onDoneClick={onDoneClick} />
```suggestion
      <TodoForm
        value={value}
        onInputSubmit={onInputSubmit}
        onInputChange={onInputChange}
      />
      <TodoList
        todoItems={todoItems}
        onDoneClick={onDoneClick}
      />
```

2020-09-27 08:59 UTC, bbhye1 commented
### **마지막 수정**

- value를 todoTitle로 이름을 변경시키고 계속 todoTitle속성으로 넘겨주었습니다. 
- 이벤트 핸들러 함수들을 각각 의미에 맞게  handleSubmitAddTodo, handleChangeTodotitle, handleClickDeleteTodo로 변경시켜 주었습니다. 
- 여러 속성들과 파리미터를 가지는 곳에 줄바꿈을 해주어 가독성이 좋도록 했습니다.

2020-09-27 09:00 UTC, bbhye1 commented
### **2주차 주간 회고**

**한 일**

> React에 대해 배우기
> 과제 1: Counter 만들고 파일 분리하기
> 과제 2: 간단한 Todo 앱 만들기 
> '코딩의 기술' 책 읽기 시작
> 리덕스에 대해 공부 시작

**배운 점**

> 상태를 객체로 관리할 때의 장점 : 
>       많은 양의 상태 값을 관리할 때 분리해서 관리하는 것보다 가독성이 더 좋아진다.
>       많은 양의 상태값을 관리할 때재할당하는 횟수를 줄일 수 있다. 
>       spread 문법으로 어떤 값 만을 변경하는지도 명시해줄 수 있다. 
> 컴포넌트의 재사용에서 고려해야 할 점 :
>       컴포넌트를 재사용할 때 예외가 많아지고 더 복잡해지는 경우들이 있다. 그런 경우에는 컴포넌트를 재사용해 코드를 작성하는 것이 더 비효율적이다. 모든 상황을 고려해 어떤 것이 효과적인 방법인가를 고려하며 선택해야 한다.
> 상태 관리 라이브러리의 필요성:
>        상태 값이 많아지고 하위 컴포넌트가 많아지면서 props로 전달해주는 것이 얼마나 불편한 점인지 느끼고 이것을 해소하기 위해 상태 값을 아예 따로 관리해주는 것의 필요성을 알게 되었다.

**느낀 점 & 자기 선언**

> 리뷰를 받을 때 가끔 이해하지 못하는 피드백이 올 때가 있다. 그냥 이렇게 하는 거구나 하고 넘길 수도 있지만 끊임없이 왜?라는 의문을 파고들었다. 그렇게 하나 두 개씩 이유를 찾아가다 보니 확실히 이 코드를 내가 왜 작성하는지 알게 되었고 모든 코드에는 모두 장단점을 가지고 있다는 걸 꺠달았다. 이 상황에서 더 나은 코드가 있을 뿐 한 가지의 정답이 있는 게 아니라는 것도 깨달아 적재적소에 다른 방식대로 코드를 작성할 수 있겠다는 느낌을 받았다. 이렇게 의문점이 남거나 내가 왜 이렇게 코딩했는지 설명할 수 없다면 그건 내가 스스로 사용할 수 없는 코드이므로 끊임없는 의문과 확실한 이해가 중요하다는 생각을 했다. 
> 이번 주도 여전히 네이밍은 어려움으로 다가왔다. Naming Convention과 내가 생각하는 이 함수와 파라미터들의 이름들 사이에서 충돌도 많이 있어서 어떤 이름을 선택하는지에 대한 혼란이 있었다. 이 문제는 장기적으로 계속 고민하면서 차차 나아겠지 하고 기대해본다.  
>  또 이번 주는 슬랙에서 활발한 대화가 있었는데 나에게 생각할 거리도 많이 던져주기도 하고 내가 남에게 내 생각을 공유할 수 있는 기회도 있었다. 이런 각자의 생각들을 나누다 보니 머릿속에 정리도 잘 되고 내가 깨닫지 못했던 방법들도 알게 되어서 서로서로 발전하는 느낌이 들었다. 아무래도 개발이라는 게 더 나은 선택이 있을 뿐이지 정답은 없기 때문에 타인의 의견을 수용하고 타인의 코드를 참고하면서 더 나아가야겠다. 
>  슬랙에서 책 추천 또한 많이 받았다. 사실 관련 서적을 읽는 것에 익숙하지는 않지만 차차 친해지려고 노력해야겠다. 1주 동안 '코딩의 기술'을 읽고 정리해서 블로그 글을 작성하는 것이 목표이다.

2020-09-27 14:48 UTC, Kihyun92 approved these changes
좋습니다~👍 이번주도 고생하셨어요ㅎㅎ

2020-10-05 13:04 UTC, merged