2주차 과제2(Todo 구현) 리뷰 요청드립니다.
CodeSoom/week2-assignment-2 pull request #3
Opened 2020-06-09 08:31 UTC by ccf05017

안녕하세요, 코드숨 리액트 1기 수강생 조범진입니다 :)

2주차 과제2(Todo 구현) 리뷰 요청드립니다.

과제1에서 진행했던 관심사 분리를 적용하기 위해 노력했습니다. 잘 됐는지 모르겠네요 ㅎㅎ.. 많은 피드백 부탁드립니다. 감사합니다.

2020-06-09 10:27 UTC, hannut91 requested changes

2020-06-09 10:27 UTC, hannut91 commented on src/components/App.jsx
> +      ),
스프레드 연산자를 사용하면 더 간단하게 표현할 수 있을거에요.

`todoList`는 `List`데이터 구조인 것 처럼 보이네요. 여러개인 것을 간단하게 표현할 수 있을까요?

`data`보다는 더 명확한 이름이 좋을 것 같아요. `content`라고 하는건 어떨까요?

2020-06-09 10:27 UTC, hannut91 commented on src/components/App.jsx
> +import TodoTemplate from './TodoTemplate';
위에 빈 줄을 추가해주세요

2020-06-09 10:27 UTC, hannut91 commented on src/components/App.jsx
> +        { data: todoContent, key: todoList.length + 1 },
`key`가 `index`를 사용하고 있네요. 각 `todo`를 유니크하게 구분할 수 없다면 리액트에 문제가 생길 수도 있습니다. 

See also
  - https://reactjs.org/docs/lists-and-keys.html

2020-06-09 10:27 UTC, hannut91 commented on src/components/TodoBody/TodoList.jsx
> +      }
3항 연산자 없이 똑같은 결과를 만들어 낼 수 있을까요? 

`todo`들의 길이가 0 일 때 위에서 바로 반환해줘도 될 것 같아요

2020-06-09 10:27 UTC, hannut91 commented on src/components/TodoHeader/TodoHeader.jsx
> +export default function TodoHeader({ onClick }) {
`todoHeader`가 상태를 관리하고 있네요. 2강 카운터에서는 상태관리를 모두 `App`이 하고 있었어요

2020-06-11 02:46 UTC, ccf05017 commented
안녕하세요, 코드숨 리액트 1기 수강생 조범진입니다.

피드백 주신 내용들 반영 완료했습니다. 재리뷰 부탁드립니다 :)
주요 변경사항은 아래와 같습니다.

- 스프레드 연산자를 통해 array state 코드 가독성 높이기
- array 컴포넌트에서 유일한 키값을 만들도록 개선하기
- ESLint 어긋나는 사항들 수정하기
- 3항 연산자 대체하기
- App 컴포넌트에서 모든 상태를 관리하기

추가적인 개선 사항 있으면 많은 피드백 부탁드립니다. 감사합니다.

2020-06-11 04:25 UTC, ccf05017 commented
다른 분들꺼 컨닝하다가 inputValue, todos 상태를 App에 합쳐놓고 왜 이걸 또 다른 메서드로 분리했지..? 라는 생각이 들어서 다시 리팩토링 했습니다 ㅎㅎ..

이제 state에서 todos, inputValue 상태를 함께 객체로 관리하도록 리팩토링 진행해봤습니다. 하고 나니까 어렴풋이 뭔가 이걸 왜 한군데 모으는지 느낌이 올듯 말듯 하네요. 오히려 합치니까 상태 관리를 더 깔끔하게 할 수 있는 것 같습니다 ㅎㅎ

관련해서 팁이나 조언주실 부분 있으시면 요것도 알려주시면 감사하겠습니다.

2020-06-11 11:17 UTC, hannut91 requested changes

2020-06-11 11:17 UTC, hannut91 commented on src/components/TodoBody/TodoRemoveButton.jsx
> +}
이 컴포넌트는 `button`의 `onClick`이벤트를 부모에게 던지기만 해주고, `() => onClick(id)`라는 세부사항은 모르게 해야 될 것 같아요. 이러한 세부사항은 이 컴포넌트를 사용하는 부모가 결정해야 할 것 같아요

2020-06-11 11:17 UTC, hannut91 commented on src/components/TodoHeader/TodoAddButton.jsx
> +    <button type="button" onClick={handleClickAdd}>추가</button>
`<button type="button" onClick={onClick}>추가</button>` 이라고 하면 안되서 이렇게 하신건가요?

2020-06-11 11:17 UTC, hannut91 commented on src/components/TodoHeader/TodoAddInput.jsx
> +    <input value={inputValue} onChange={(e) => onChange(e)} />
여기도 `onChange={onChage}` 라고 사용하면 안되서 이렇게 하신건가요?

2020-06-11 11:17 UTC, hannut91 commented on src/components/TodoHeader/TodoHeader.jsx
> +export default function TodoHeader({ onClick, inputValue, handleChange }) {
`TodoHeader`와 `TodoHeaderTemplate`이 왜 나눠져 있는지 잘 모르겠어요. 어떤 이유에서 나눠져 있는건가요?

2020-06-11 23:40 UTC, ccf05017 commented on src/components/TodoBody/TodoRemoveButton.jsx
> +}
피드백주신 내용을 
- TodoRemoveButton 컴포넌트의 목적은 '이렇게 생긴 button이다'의 역할을 수행해야 한다. 
- 하지만 지금 '버튼을 클릭했을 때 이렇게 동작해!'까지 참고하고 있다.
- 이 때문에 id라는 상태를 불필요하게 가져오면서 관리하는 게 된다
요렇게 이해했는데 맞을까요? 혹시나 요상하게 해석했다면 추가 피드백 부탁드립니다!

2020-06-11 23:43 UTC, ccf05017 commented on src/components/TodoHeader/TodoAddButton.jsx
> +    <button type="button" onClick={handleClickAdd}>추가</button>
엌ㅋㅋㅋ 죄송합니다.. 원리 저 안에 input 상태를 지우는 clearInputState 함수가 있어서 묶어놓느라 저렇게 했었는데 지금은 상태를 통합하면서 onClick 안에서 전부 처리하고 있는데 제가 리팩토링을 안하고 덥썩 올렸네요 ㅎㅎ...

2020-06-11 23:45 UTC, ccf05017 commented on src/components/TodoHeader/TodoAddInput.jsx
> +    <input value={inputValue} onChange={(e) => onChange(e)} />
현재 onChange에 전달한 이벤트 객체 안의 value 속성을 읽어서 state를 관리하고 있어서 이렇게 처리했습니다.
이렇게 처리하기 전에는 todo 컴포넌트가 추가될 때마다 id를 key와 동일하게 설정하고 getElementId로 처리하도록 작성했었는데, 뭔가 id에 너무 의존적이지 않나 해서 이렇게 변경해봤습니다.
더 좋은 방법 있다면 공유 부탁드립니다 :)

2020-06-11 23:46 UTC, ccf05017 commented on src/components/TodoHeader/TodoHeader.jsx
> +export default function TodoHeader({ onClick, inputValue, handleChange }) {
죄송함다 요것도 제가 리팩토링을 덜 했네요 ㅎㅎ.. 이전에 InputValue 상태를 TodoHeader 쪽에서 관리하도록 작성하면서 TodoHeaderTemplate은 그리는 것만 담당하고 TodoHeader가 상태값을 관리하도록 만들어놓은 게 유지되서 그렇습니다. 제거하겠습니다 :)

2020-06-11 23:48 UTC, hannut91 commented on src/components/TodoBody/TodoRemoveButton.jsx
> +}
ㅎㅎㅎ 네 잘 이해하고 계신 것 같아요

2020-06-11 23:48 UTC, hannut91 commented on src/components/TodoHeader/TodoAddInput.jsx
> +    <input value={inputValue} onChange={(e) => onChange(e)} />
음.. `onChange={onChage}`이렇게 해도 동일한 결과가 나오지 않나요?

2020-06-11 23:50 UTC, ccf05017 commented on src/components/TodoHeader/TodoAddInput.jsx
> +    <input value={inputValue} onChange={(e) => onChange(e)} />
음..? 시도해보겠습니다. 그렇게 되는 줄 몰랐습니다 ㅎㅎ ㅜ

2020-06-12 00:08 UTC, hannut91 requested changes

2020-06-12 00:08 UTC, hannut91 commented on src/components/TodoHeader/TodoHeader.jsx
> +export default function TodoHeader({ onClick, inputValue, handleChange }) {
`TodoHeaderTemplate`의 내용이 여기로 바로 들어와도 동일한 결과를 만들어 낼 것 같아요

2020-06-12 00:35 UTC, ccf05017 commented on src/components/TodoHeader/TodoAddInput.jsx
> +    <input value={inputValue} onChange={(e) => onChange(e)} />
으잉?? 말씀하신대로 되네요 ㅋㅋㅋㅋㅋ

이벤트 핸들러에는 기본적으로 현재 이벤트 객체가 넘어가서 그런건가요..? 제가 html 속성 이해가 부족한 거 같네요 ㅎㅎ.... 좀 더 공부하겠습니다.

2020-06-12 10:09 UTC, hannut91 requested changes
`Template`이라고 하면 주어진 기본 설정들이 있고 입력값에 따라서 다르게 생성되는 무언가를 나타내는 것 같아요. `Template`이 지금 필요한지 잘 모르겠어요.

2020-06-12 10:09 UTC, hannut91 commented on src/components/App.jsx
> +  }
`target`이 의미하는바가 파악하기 어려운 것 같아요. key를 받는거죠?

2020-06-14 15:05 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 과제를 진행하시면서 어떤 것을 배우셨나요? 좋았던 점이나 아쉬운 점이 있으신가요?

2020-06-14 23:25 UTC, ccf05017 commented
리액트를 활용해서 기본적인 컴포넌트를 만들고 배포할 수 있게 됐습니다. 추가로 상태(state, props) 관리와 렌더링을 어떻게 나눠서 바라볼 것인지 배울 수 있었습니다. 마지막으로 상태를 한 곳에서 관리하면, 연관된 상태끼리 중복을 제거하고 좀 더 효율적인 상태 관리 코드를 만들 수 있다는 걸 배웠습니다.

좋았던 점은 역시 리뷰어가 있어서 제가 맞는 방향으로 가는지 바로 확인할 수 있다는 점이었습니다. 또한 강의 자료에 첨부된 양질의 링크 자료들을 통해 학습 레퍼런스를 늘릴 수 있었고, 리액트 공식 문서의 대략적인 맥락을 파악할 수 있었습니다.

아쉬웠던 점은 제가 시간 관리를 못해서 좀 더 적극적으로 리뷰를 못했던 부분이 아쉬웠습니다. 이 부분은 제가 노력해서 개선하겠습니다. 두번째로 아쉬웠던 건 피드백의 질문이 너무 추상적일 때가 있었던 것 같습니다. 제가 스스로 생각하고 학습하기 위해서 생각할 부분을 짚어주시는 방식으로 해주신 거겠지만, 생각보다 기초가 부족해서 아무리 짱구를 굴려도 답이 안 나오는 부분이 종종 있습니다 ㅎㅎ.. 이런 부분에 대해서는 조금만 더 구체적인 질문을 주시면 좋을 것 같습니다.

한주 간 감사했습니다. 짧은 기간이었지만 여지껏 혼자 프론트엔드 공부한다고 낑낑거리던 때보다 훨씬 실질적으로 많은 것을 얻을 수 있었던 한주였어요 :)

2020-09-06 14:46 UTC, merged