Create todo app
CodeSoom/week2-assignment-2 pull request #30
Opened 2020-09-22 05:08 UTC by smilee

Create todo app to meet assignment requirments.

2020-09-22 05:19 UTC, smilee commented
`@codeceptjs/configure`가 없어서 check을 통과 못하길래 추가해서 ammend하고 force push했습니다.

2020-09-22 14:08 UTC, hannut91 requested changes

2020-09-22 14:08 UTC, hannut91 commented on src/Page.jsx
> +    />
무언가를 제출하니까 `<TodoForm />`은 어떨까요?

2020-09-22 14:08 UTC, hannut91 commented on src/TodoInput.jsx
> +    </button>
추가 버튼을 클릭했을 때 `addTodo`를 실행해서 text를 넘기는 것 같아요. 이미 App 컴포넌트는 todoText를 상태로 관리하고 있으므로 안넘겨줘도 될까요?

2020-09-22 14:08 UTC, hannut91 commented on src/TodoInput.jsx
> +      }}
event 객체를 처리하는 것과 `updateTodoText`함수호출하는 것을 분리하기 위해서 핸들러 함수로 추출하는건 어떨까요?

2020-09-22 14:08 UTC, hannut91 commented on src/TodoList.jsx
> +));
3항 연산자를 이용해서 투두가 비어있을 때를 조건부 렌더링을 해주신 것 같아요. 이렇게 단순한 경우에는 Guard Clauses를 사용하면 더 간단하게 표현이 가능해요.

```js
const isEmpty = (arr) => arr.length === 0;

export function Todos({ todos, deleteTodo }) {
  if (isEmpty(todos)) {
    return <p>할 일이 없어요!</p>;
  }

  return (
    <ol>
      {todoList.map(({ id, text }) => (
        <li key={id}>
          {text}
          <button type="button" onClick={() => deleteTodo({ id })}>완료</button>
        </li>
      ))}
    </ol>
  );
}
```

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-22 14:08 UTC, hannut91 commented on src/App.jsx
> +  const [todoList, setTodoList] = useState([]);
todo의 목록을 나타내기위해서 `todoList`라고 이름지으신 것 같아요. 여러개를 나타낼때는 List를 사용하시면 우리가 자료형인 List와 혼동이 될 수 있기 때문에 `todos`처럼 본래 복수형을 사용하면 이 변수가 배열이라는 것을 명시적으로 알 수 있습니다.

2020-09-23 07:22 UTC, smilee commented on src/App.jsx
> +  const [todoList, setTodoList] = useState([]);
복수형이 없는 단어도 있어서 다른 방법을 찾는 중인데 `todoArray`는 어떤가요? ㅋㅋㅋ

2020-09-23 16:57 UTC, hannut91 commented on src/App.jsx
> +  const [todoList, setTodoList] = useState([]);
아샬님이 비슷한 질문에 답이 좋아서 가져와봤습니다. 참고하시면 좋을 것 같아요.

![](https://user-images.githubusercontent.com/14071105/94044473-265cd400-fe09-11ea-959f-4bf3e883c439.png)

See also
  - https://www.facebook.com/groups/codingeverybody/permalink/4681969601843539

2020-09-23 16:58 UTC, hannut91 requested changes

2020-09-23 16:58 UTC, hannut91 commented on src/App.jsx
> +  }
`handleChangeTodoText`는 상태를 변경하는 함수고 event는 UI의 이벤트입니다. 상태를 변경하는 함수는 주어진 값으로 상태만 변경하고 이벤트값에 대한 처리를 UI쪽에서 하는게 좋을 것 같은데 어떨까요?

2020-09-24 09:29 UTC, smilee commented on src/App.jsx
> +  }
좋아요. 반영하겠습니다.

2020-09-24 15:06 UTC, hannut91 requested changes
좋습니다. ㅎㅎㅎ 객체로 묶었을 때 어떤 장점이 있을지 한 번 생각해보시면 좋을 것 같습니다

2020-09-24 15:06 UTC, hannut91 commented on src/App.jsx
> +  const [tasks, setTasks] = useState([]);
상태가 늘어날수록 이 부분도 계속 늘어날 것 같아요. 객체로 묶어서 표현해주는건 어떨까요?

2020-09-25 02:12 UTC, smilee commented
state를 객체로 묶으면 내리는 prop의 수를 줄일 수 있습니다. ㅎㅎ

2020-09-25 03:04 UTC, smilee commented on src/App.jsx
> +  const [tasks, setTasks] = useState([]);
`useState` hook을 지금 구조로 쓰면 함수로 기존 값을 받아오는 내장기능(?)도 불필요해지겠네요?

2020-09-25 16:09 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 이번 과제를 통해서 무엇을 할 수 있게 되셨나요?

2020-09-26 02:48 UTC, smilee commented
> 고생하셨습니다 ㅎㅎ 이번 과제를 통해서 무엇을 할 수 있게 되셨나요?

1. 이름 짓는 기준을 더 명확하게 정의하게 되었습니다.
2. Guard clause를 더 넓은 범위의 상황에 적용할 수 있게 되었습니다.
3. 상태와 이벤트 처리를 분리할 수 있게 되었습니다.

2020-09-26 15:57 UTC, merged