week2-2 create todo app
CodeSoom/week2-assignment-2 pull request #33
Opened 2020-09-22 06:40 UTC by JamieShin0201

안녕하세요. ㅎ.ㅎ

1. App :  상태관리 및 함수 비즈니스로직을 구현 하였습니다.

2. TodoPage : Todo 관련 컴포넌트들이 모여있습니다.

 1) TodoAddBox (Todo 입력 부분)
  1-1) TodoInput
  1-2) TodoAddButton

 2) EmptyBox (만약 TodoList가 비어있을때 보여줄 부분)

 3) TodoList
  3-1) TodoItem
   3-1-1) Todo 
   3-1-2) TodoFinishButton

다음과 같이 컴포넌트들을 세분화 해보았습니다. 

감사합니다^^

2020-09-22 16:33 UTC, Kihyun92 requested changes
컴포넌트를 잘게 쪼개셨네요~ 좋습니다. 지금 당장은 TodoItem 내에 텍스트 영역과 버튼 영역을 굳이 나눌 필요는 없을 수도 있지만, 스타일이 추가되거나 이런저런 변경을 생각하면 각각을 컴포넌트화 하는 것도 괜찮아 보이네요~

전반적으로 이벤트 핸들러들의 네이밍 컨벤션을 수정해주셨으면 좋겠습니다~ 그리고 컴포넌트 네임도 불필요하게 TODO가 전부 붙을 필요가 있을까 싶은 생각도 들구요. 이 부분은 한번 생각해보시면 좋을 것 같습니다~ :)

2020-09-22 16:33 UTC, Kihyun92 commented on src/App.jsx
> +    todos.push(todo);
todos에 push를 하면 안됩니다. setState를 이용하면 todos의 상태값을 변경할 수 있지 않을까요?

2020-09-22 16:33 UTC, Kihyun92 commented on src/App.jsx
> +    }
과제의 요구보다 더 고민해보셨군요~👍

TodoAddButton 컴포넌트의 버튼 태그를 아예 안눌리게 disabled 속성을 이용하여 처리할 수도 있을 것 같습니다~

2020-09-22 16:33 UTC, Kihyun92 commented on src/App.jsx
> +    todos.splice(index, 1);
이 부분도 setState를 사용해서 처리할 순 없을까요?

2020-09-22 16:33 UTC, Kihyun92 commented on src/App.jsx
> +      isEmpty: isEmptyCheck,
```suggestion
      isEmpty: todos.length === 0,
```
이 경우엔 인라인으로 처리해도 될 것 같네요~

2020-09-22 16:33 UTC, Kihyun92 commented on src/TodoPage.jsx
> +      />
```suggestion
      {isEmpty ? <EmptyBox /> : (
        <TodoList
          todos={todos}
          handleClickFinish={handleClickFinish}
        />
      )
```
리스트가 비어있을때 EmptyBox가 노출되고 아닐 경우, List가 노출되도록 이렇게 처리하는건 어떤가요?

2020-09-22 16:33 UTC, Kihyun92 commented on src/TodoPage.jsx
> +        handleClickAdd={handleClickAdd}
onClick={handleClick}과 같이 컨벤션을 맞춰주는건 어떨까요??

참고: https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2020-09-23 05:01 UTC, JamieShin0201 commented on src/TodoPage.jsx
> +      />
조건에 따라 컴포넌트가 실행되는 방식이  더 좋은거 같습니다.! 

1.  EmptyBox와 TodoList 두개가 모두 보일 확률이 없어집니다.
2. 굳이 실행되지 않아도 되는 컴포넌트가 실행된 후 그 안에서 조건을 확인하니 비효율 적인거 같습니다.

2020-09-23 06:51 UTC, JamieShin0201 commented
안녕하세요^_^

1. TodoAddButton, TodoFinishButton -> Button 으로 수정하였습니다.
2. 컴포넌트 이름에 Todo가 중복되어 수정하였습니다.
3. 입력없이 추가를 하지 못하게 disabled 설정을 하였습니다.
4. todo 변수에 id를 추가하였습니다.

전반적으로 네이밍에 신경을 썼는데.. 아직 한번에 이해되는거 같진 않습니다. ㅠㅠ
리뷰 부탁드리겠습니다 ㅎ.ㅎ

2020-09-23 15:47 UTC, Kihyun92 requested changes
제가 드리는 피드백보다 더 많은걸 받으시는 것 같네요 👍 

충분히 네이밍이 좋아지고 있습니다 :) Box보다 상황에 따라 Form이나 Item등으로 쓰는게 좋다는건 경험하다보면 충분히 좋아지는 부분이에요~

2020-09-23 15:47 UTC, Kihyun92 commented on src/App.jsx
> +    todos: [],
```suggestion
    todo: [{
      id: 1,
      content: '',
    }],
    todos: [],
```
todo가 이런 모양이면 어떤가요? todos와 todo의 역할이 각각 뭔지 이해가 잘 되지 않는 것 같아요~

2020-09-23 15:47 UTC, Kihyun92 commented on src/List.jsx
> +          <TodoBox
TodoBox보다 TodoItem이라고하면 어떨까요?

2020-09-23 15:47 UTC, Kihyun92 commented on src/List.jsx
> +            onClick={() => onClick(todo.id)}
여기선 `onClick={onClick}을 하고, 어차피 props로 todo를 넘기니까 그곳에서 id를 넣어주는건 어떨까요?

2020-09-23 15:47 UTC, Kihyun92 commented on src/AddBox.jsx
> +function AddBox({ todo, onChange, onClick }) {
AddBox보다는 form과 같은 역할을 하고있으니 그냥 Form이라고 하는건 어떨까요?

2020-09-23 15:47 UTC, Kihyun92 commented on src/TodoBox.jsx
> +      <Todo todo={todo} />
지금 복잡도에서는 굳이 컴포넌트로 추출하지 않아도 될것같네요 :)
그리고 이 경우에는
```suggestion
      <Todo content={todo.content} />
```
이렇게 넘기는게 좋겠네요

2020-09-24 01:49 UTC, JamieShin0201 commented on src/App.jsx
> +    todos: [],
todo의 역할을 명확히 표현 하기 위해서 변수명을 newTodo로 변경하였습니다.

todo가 배열이 되는거 같은데.. 피드백 주신게 잘 이해되지 않습니다 ㅠ.ㅠ

2020-09-24 01:52 UTC, JamieShin0201 commented on src/AddBox.jsx
> +function AddBox({ todo, onChange, onClick }) {
더 좋은거 같습니다 ^_^

2020-09-24 01:54 UTC, JamieShin0201 commented on src/List.jsx
> +            onClick={() => onClick(todo.id)}
두가지가 동작이 똑같은데 혹시 하위 컴포넌트에서 매개변수를 주는게 더 좋은 이유가 있을까요?
하위 컴포넌트만 보고 어떤 매개변수를 넣었는지 바로 파악하기 좋아서일까요?

2020-09-24 01:56 UTC, JamieShin0201 commented
안녕하세요^^

1. 전체적으로 컴포넌트 이름을 수정하고 복잡도가 적은 컴포넌트를 하나로 합쳤습니다.
2. 변수의 이름을 조금 더 명확하게 수정하였습니다.

감사합니다. ㅎ.ㅎ

2020-09-24 15:21 UTC, Kihyun92 commented on src/List.jsx
> +            onClick={() => onClick(todo.id)}
맞습니다~ 그리고 List 컴포넌트에서 굳이 click 함수에 id를 넘겨야하는걸 알 필요가 없기 때문도 있을 것 같네요 :)

2020-09-24 15:32 UTC, Kihyun92 requested changes
제가 드리는 피드백보다 더 많은 고민을 해보시고 적극적으로 질문해 주시는게 너무 감사하네요 👍

2020-09-24 15:32 UTC, Kihyun92 commented on src/App.jsx
> +  });
예시를 들었던 거였는데, 제가 설명이 부족했던것 같네요~

```suggestion
    newTodo: '',
    todos: [
      {
        id: 1,
        content: ''
      }
    ],
  });
```
지금 구조와 비슷하지만, 조금 구조를 바꿔서 이렇게 되면 어떤가요?

2020-09-24 15:32 UTC, Kihyun92 commented on src/Item.jsx
> +function Item({ todo, onClick }) {
```suggestion
function Item({ todo: { content, id }, onClick }) {
```
한번 더 destructuring을 해줘도 좋겠네요~

2020-09-24 15:32 UTC, Kihyun92 commented on src/TodoPage.jsx
> +      />
AddForm보다는 Form이라고 하는건 어떨까요?

2020-09-25 07:38 UTC, JamieShin0201 commented on src/App.jsx
> +  });
제 생각엔 해당 구조로 바꾸면 좋은 이유가

1. newTodo값이 변경될때 id를 유지 하지 않아도 된다.
2. id값은 todos 내의 todo의 고유번호를 매기기 위해 필요하기 때문에??

이 정도로 생각했는데.. 다른 이유가 있을까요?

2020-09-25 07:40 UTC, JamieShin0201 commented on src/TodoPage.jsx
> +      />
AddForm 대신 Form이라고 하면 Form을 추가뿐 아니라 다른 곳에서도 이용할 수 있을 거 같습니다.!

2020-09-25 08:08 UTC, JamieShin0201 commented
안녕하세요~^^

1. AddForm 컴포넌트 이름을 Form으로 수정하였습니다.
2. Item 컴포넌트 안에 매개변수 todo를 destructuring하였습니다.
3. App 컴포넌트안에 newTodo 변수를 id와 content를 같는 객체에서 문자형으로 변경하였습니다.

감사합니다 ㅎ.ㅎ

2020-09-25 12:38 UTC, Kihyun92 commented on src/App.jsx
> +  });
ㅎㅎ 맞습니다 ☺️ newTodo에는 새로 입력 받은 값만 받도록 해서 조금 더 명확하고, newTodo를 todos에 넣어줄때 id값을 지정해줄 수 있을 것 같네요~

2020-09-25 12:47 UTC, Kihyun92 requested changes

2020-09-25 12:47 UTC, Kihyun92 commented on src/App.jsx
> +    const nextId = (todos.length === 0) ? 1 : todos[todos.length - 1].id + 1;
새로 등록되는 todo의 id를 구해주는 로직이 많이 복잡해 보이네요. 복잡해진 이유가 무엇 때문일까요?

2020-09-26 07:13 UTC, JamieShin0201 commented on src/App.jsx
> +    const nextId = (todos.length === 0) ? 1 : todos[todos.length - 1].id + 1;
지금 id생성방법은 todos 배열의 마지막요소 id에 1을 더해주는 방식인데요.

1. 다른 방법을 생각해본다. ex) 시간을 이용하거나, uuid를 이용?
2. 같은방법에서 개선할 점을 찾아본다. (id생성부분을 함수화 한다?, 더 좋은 로직을 생각해본다.)

고민해보도록 하겠습니다. ㅎ.ㅎ

2020-09-26 12:54 UTC, JamieShin0201 commented on src/App.jsx
> +    const nextId = (todos.length === 0) ? 1 : todos[todos.length - 1].id + 1;
뭐가 더 좋은 방법인지.. 아직은 잘 모르겠지만 복잡한 로직을 없애기 위해 newId라는 상태변수를 만들어 관리하도록 해보았습니다.

2020-09-26 14:34 UTC, Kihyun92 commented on src/App.jsx
> +    const nextId = (todos.length === 0) ? 1 : todos[todos.length - 1].id + 1;
오 너무 좋네요! 👍

2020-09-26 14:43 UTC, Kihyun92 requested changes
좋네요~ 전반적으로 불필요한 기능이나 명확하지 않은 네이밍은 사용하고 있지 않은지 한번 확인해보면 좋을 것 같습니다!👍

2020-09-26 14:43 UTC, Kihyun92 commented on src/App.jsx
> +    newTodo: '',
todo의 content를 결국받아오는 부분인데, newTodo라고하니 왠지 객체 정보가들어올 것 같아요 ㅎㅎ
todoContent라고 하는건 어떨까요?

2020-09-26 14:43 UTC, Kihyun92 commented on src/App.jsx
> +      todos: todos.filter((item) => item.id !== id),
```suggestion
      todos: todos.filter((todo) => todo.id !== id),
```

2020-09-26 14:43 UTC, Kihyun92 commented on src/App.jsx
> +  function handleClickFinish(id) {
App내에서 이 함수가 하는 역할이 나타나는 함수명이면 좋을 것 같아요~

지금은 이 함수를 사용하는 쪽에서 봤을때 이해되는 네이밍 같아서요.

2020-09-26 14:43 UTC, Kihyun92 commented on src/Input.jsx
> +    <input type="text" placeholder="할일을 입력해 주세요" value={newTodo || ''} onChange={onChange} />
```suggestion
    <input
      type="text"
      placeholder="할일을 입력해 주세요"
      value={newTodo || ''}
      onChange={onChange}
    />
```

한 줄이 길어질 땐, 여러 줄로 표현하면 더 보기 편할 것 같습니다~

2020-09-27 11:52 UTC, JamieShin0201 commented on src/App.jsx
> +  function handleClickFinish(id) {
App 내에서 todos 배열의 요소를 삭제하는 역할을 하니 handleClickDelete로 이름을 수정하였습니다.!

2020-09-27 11:58 UTC, JamieShin0201 commented
안녕하세요~!

리뷰해주신 부분들 확인하고 전반적인 네이밍을 수정하였습니다!.!

감사합니다 ㅎ.ㅎ

2020-09-27 14:51 UTC, Kihyun92 approved these changes
이번주도 고생하셨어요~

회고도 잘 봤습니다 ㅎㅎ 과제들 복습해보는것도 좋네요 👍

2020-10-05 13:04 UTC, merged