Implement the function of the complete work button.
CodeSoom/week2-assignment-2 pull request #34
Opened 2020-09-22 07:28 UTC by hyejineee

main으로 pr을 잘 못 보내서 다시 pr날립니다ㅏㅏㅏ

## 기능 구현

- [x] 사용자는 할 일을 입력할 수 있습니다.
- [x] 사용자는 추가 버튼을 눌러서 할 일을 추가할 수 있습니다.
- [x] 사용자는 할 일 목록을 볼 수 있습니다.
- [x] 사용자는 완료 버튼을 눌러 할 일을 삭제할 수 있습니다.

## 요구사항

- [x] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [x] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.

## 상태 &질의 

- 아직 컴포넌트로 분리하지 않고 기능만 구현하는 중입니다.
- input의 내용을 지우는 것에 대해서는 다음 문서를 참고했습니다.
      https://reactjs.org/docs/forms.html

2020-09-22 15:30 UTC, hannut91 requested changes

2020-09-22 15:30 UTC, hannut91 commented on src/index.jsx
> +  }
event는 UI에 대한 이벤트이기 때문에 이 함수까지 넘어오기 보다는 값만 넘어오는게 좋을 것 같아요

2020-09-22 15:30 UTC, hannut91 commented on src/index.jsx
> +      }
조건에 해당할 때만 렌더링 하고싶을 때는 다음과 같이 할 수 있습니다.

```js
{works.length <= 0 && <p>할 일이 없어요!</p>}
```

See also
  - https://reactjs.org/docs/conditional-rendering.html

2020-09-22 15:30 UTC, hannut91 commented on src/index.jsx
> +  }
삭제할 TODO의 key를 나타내니 `deleteTodoKey`라고 하신 것 같아요. 변수가 살아있는 기간이 길수록 더 구체적인 이름이어야 하고 짧을수록 단순한 이름이 좋습니다. 여기서는 단순히 key 혹은 value로 받아도 충분히 이해가 될 것 같아요

2020-09-23 14:13 UTC, hyejineee commented on src/index.jsx
> +  }
음... 이 함수까지 넘어오기 보다는 값만 넘어오는게 좋다 라는 말이 잘 이해되지 않아요!! onChange를 handle하는 함수를 사용하지 말라는 건가용???

2020-09-23 14:14 UTC, hyejineee commented on src/index.jsx
> +      }
오... 이런 문서가 있었군요ㅎㅅㅎ 문서를 한 번 정독해야겠네욤ㅎㅅㅎ

2020-09-23 14:15 UTC, hyejineee commented on src/index.jsx
> +  }
아하! 그래서 코드를 작성할 때 변수명이 중복이 많은 것 같다. 라고 느낀 것 같아요! 감사합니다!!

2020-09-23 14:18 UTC, hyejineee commented on src/index.jsx
> +  }
추가적인 질문 하나 더 있습니다! 위의 코드 같은 경우 deleteTodoKey로 할 경우 아래 map에서 사용되는 key변수와 중복이 되는데 이럴때 map에 있는 변수를 어떻게 하면 좋을까요?? 단순히 k한글자만 변수명으로 사용해도 될까요???

2020-09-24 15:27 UTC, hannut91 commented on src/index.jsx
> +  }
한글자만 받아도 상관없습니다. 혹은 `works.filter((work) => work.key !== key));` 처럼 해도 될 것 같아요

2020-09-24 15:32 UTC, hannut91 requested changes

2020-09-24 15:32 UTC, hannut91 commented on src/components/App.jsx
> +  const [work, setWork] = useState('');
객체로 묶어서 하나로 표현해주면 어떨까요?

2020-09-24 15:32 UTC, hannut91 commented on src/components/App.jsx
> +  }
work의 key와 todoKey로 비교하니까 이해가 어려운 것 같아요.

2020-09-24 15:32 UTC, hannut91 commented on src/components/App.jsx
> +
여기 빈 줄이 들어가 있네요

2020-09-24 15:32 UTC, hannut91 commented on src/components/WorkList.jsx
> +export default function WorkList({ works, onClick }) {
여기 위에 빈 줄 하나를 추가해서 구분해주면 좋을 것 같아요

2020-09-24 15:32 UTC, hannut91 commented on src/components/Input.jsx
> +    <input type="text" placeholder="할 일을 입력해주세요." value={value} onChange={(e) => passingValue(e)} />
`onChange={passingValue}`

파라미터가 하나기 때문에 이렇게 써도 됩니다. 

`passing`과 `value`가 어떤 의미인지 파악하기가 어렵습니다.
`handleChange`로만 해도 충분할 것 같아요

2020-09-24 15:32 UTC, hannut91 commented on src/components/Button.jsx
> +}
`여기서도 마찬가지로 `handleClick`으로만 해줘도 충분할 것 같아요.
form이 없으니 버튼의 타입은 `button`이 더 적절할 것 같아요. type submit은 form 안에서만 사용하는게 좋습니다

2020-09-25 11:13 UTC, hyejineee commented on src/index.jsx
> +  }
넵 알겠습니다!

2020-09-25 11:13 UTC, hyejineee commented on src/components/App.jsx
> +  }
넵ㅎㅅㅎ work로 고칠게욤

2020-09-25 11:14 UTC, hyejineee commented on src/components/WorkList.jsx
> +export default function WorkList({ works, onClick }) {
넵 알겠습니다!!

2020-09-25 11:15 UTC, hyejineee commented on src/components/Input.jsx
> +    <input type="text" placeholder="할 일을 입력해주세요." value={value} onChange={(e) => passingValue(e)} />
이벤트를 막고 value만 넘겨준다해서 이렇게 지었는데 생각이 좀 짧았던 것 같습니다. 아침에 후다닥 수정하고 알바 갔거든옇ㅎㅅㅎ

2020-09-25 11:16 UTC, hyejineee commented on src/components/Button.jsx
> +}
그럼 컴포넌트의 이름에 맞춰서 form으로 수정하겠습니다.!

2020-09-25 12:11 UTC, hyejineee commented on src/components/App.jsx
> +  const [work, setWork] = useState('');
음...객체로 묶어야 하는 이유가 뭔가욤???
1. work의 경우 input에서 글자를 받을 때마다 상태를 갱신하는데 객체로 묶게 된다면  works의 복사도 계속 발생하게 됩니다. works가 기본 타입의 값일 경우는 상관없지만 array나 객체 같은 경우에는 성능에 영향을 미치지 않을까요???? 

2. 이건 변수명의 문제도 있는 것 같아요ㅎㅅㅎ변수명을 work로 해서 works와 관계가 있는 것 같아서 객체로 묶여도 되게끔 보이게 하는 것 같습니다. 사실 work가 works에 들어가기 전, 후에도 서로 관계가 없다고 생각합니다.ㅎㅅㅎ 

그리고 이 부분에 대해 공부하면서 궁금한게 몇가지 생겼는데욤

1. 보통 input태그의 입력으로 들어온 값을 이렇게 상태로 관리하나요??? 리액트 문서에 있어 참고하긴 했지만.... 흠.... 
2. 저렇게 input태그로 들어온 값을 App 컴포넌트에서 상태로 관리를 하고 있는데 상태 변화로 App 컴포넌트가 리렌더링 될 경우 하위 컴포넌트들 까지 다시 렌더링 된다구 알고 있어요! input의 상태를 App 컴포넌트에서 관리하는게 맞을까요....??

2020-09-25 17:06 UTC, hannut91 requested changes

2020-09-25 17:06 UTC, hannut91 commented on src/components/App.jsx
> +  const [work, setWork] = useState('');
1. 성능에 영항을 가지 않습니다. 객체를 새로 만든다고 해도 실제 값들은 계속 재활용해서 사용하기 떄문이에요. 예를들어 만약에 

```js
const obj = { a: 3 };

const newObject = { ...obj };
```

이렇게 한다고 해도 property a가 3이라는 것은 계속 재활용하기 때문이에요. 이 내용은 `코어 자바스크립트`라는 책에 더 자세히 나와있습니다.

2. 객체로 관리해보도록 말씀드린 이유는 상태를 하나의 객체로 관리했을 때 어떻게 되는지를 보면 좋을 것 같아서 말씀드렸습니다. 

3. 항상 그런 것은 아닙니다. 정답은 정해져있지 않으니 상황에 따라 다르게 사용해야 합니다. 

4. 이번 과제의 의도는 상태를 관리하는 컴포너트와 UI를 관리하는 컴포넌트를 props를 이용해서 관심사의 분리를 하는게 목적입니다. 렌더링 되는 것은 지금 고려하고 있지 않아요.

See also 
 - https://reactjs.org/docs/uncontrolled-components.html
 - http://www.kyobobook.co.kr/product/detailViewKor.laf?barcode=9791158391720

2020-09-26 08:58 UTC, hyejineee commented on src/components/App.jsx
> +  const [work, setWork] = useState('');
오호.. 재활용에 대해서는 공부를 해봐야겠네요!! 답변 감사합니다.😆😆😆😆😆

2020-09-26 16:13 UTC, hannut91 requested changes

2020-09-26 16:13 UTC, hannut91 commented on src/components/App.jsx
> +    workInput: '',
`input`을 통해 값이 변경되고 사용하기 때문에 `workInput`이라고 하신 것 같아요. 만약에 이 값을 다른 곳에서도 보여주거나 혹은 서버로부터 불러온 값을 보여줘야 한다면, 혹은 localStorage같은 곳에 저장해놓았다고 불러온다고 하더라도 계속 이 이름을 사용할 수 있을까요?

변수이름이라는 것은 처음에는 적절했지만 기능을 수정한다던가, 아니면 기능을 개발하면서 도메인 지식이 늘어남에 따라 잘못된 변수이름이 될 수 있습니다. 변수 이름이라는 것은 계속 다듬어야 하는 것이라는 것을 배우셨으면 좋겠습니다.

2020-09-26 16:13 UTC, hannut91 commented on src/components/Button.jsx
> +    </button>
type이 submit이라면 여기서 handleClick을 처리하지 않는게 좋습니다. `form`에서 `onSubmit`을 이용해서 처리하는게 더 자연스러울 것 같습니다.

2020-09-26 16:13 UTC, hannut91 commented on src/components/Input.jsx
> +    <input type="text" placeholder="할 일을 입력해주세요." value={value} onChange={(e) => handleChange(e)} />
`onChange={(e) => handleChange(e)`대신 `onChange={handleChange}`라고 써도 괜찮을 것 같아요

2020-09-26 16:13 UTC, hannut91 commented on src/components/App.jsx
> +        onChange={(e) => handleWorkInputChange(e)}
여기도 마찬가지로 `onChange={handleWorkInputChange}`라고 해도 될 것 같아요

2021-01-17 12:59 UTC, merged