간단 Todo 리스트 완료
CodeSoom/week2-assignment-2 pull request #35
Opened 2020-09-22 10:45 UTC by dongakim

### 💁🏻‍♂️  간략 설명
관심사 분리를 해보았습니다.

**App 컴포넌트**의 관심사는 todo의 상태관리이고
UI에 대한 부분은 Page 컴포넌트가 담당합니다.

**Page 컴포넌트**는
todo 리스트를 구성하는 컴포넌트를 감싸며
전달받은 props를 하위 컴포넌트에 전달합니다.

**TodoInput 컴포넌트**는
input에 대한 상태관리 로직을 갖고 있으며
button 클릭시 전달받은 이벤트를 실행합니다.

**TodoList 컴포넌트**는
todos에 따라 UI를 분기하고
전달받은 이벤트를 하위 컴포넌트에 전달합니다.

**TodoListItem 컴포넌트**는
전달받은 todo를 표현하고
button 클릭시 전달받은 이벤트를 실행합니다.

### 🙋🏻‍♂️  궁금한 점
어떻게하면 더 좋은 관심사의 분리를 만들어 낼 수 있을지 궁금합니다.
관심사를 분리시키는 포인트를 인식하는 방법이 있을까요?

2020-09-22 16:54 UTC, Kihyun92 requested changes
많은 고민을 하신 것 같네요~👍

관심사의 분리라는 말이 애매모호한 부분이 있지만, 아샬님이 강의에서 말씀하셨듯이 일단 보여지는 부분과 상태를 관리하는 부분으로 분리해보세요. 상태를 관리를 어디서하는게 가장 좋을지 고민해보시면 금방 감을 잡으실 것 같습니다~

이 피드백들이 지금까지 과제들의 의도를 한번 다시 생각해보는 기회가 됐으면 좋겠습니다~

2020-09-22 16:54 UTC, Kihyun92 commented on src/App.jsx
> +    const lastTodo = [...todos].pop();
todos의 변경은 항상 setTodos를 사용해주세요. pop은 불변성을 위반하기 때문에 사용하지 않는게 좋습니다.

2020-09-22 16:54 UTC, Kihyun92 commented on src/App.jsx
> +    addTodo(value);
addTodo로 나눌 필요가 있을까요??

2020-09-22 16:54 UTC, Kihyun92 commented on src/App.jsx
> +  };
이 부분도 굳이 추출할 필요가 없을 것 같습니다. 차라리 함수명에 todo를 지운다는 느낌이 담기게 변경하는건 어떤가요?

2020-09-22 16:54 UTC, Kihyun92 commented on src/App.jsx
> +    setTodos(copiedTods);
로직이 복잡한 것 같습니다. [filter](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)를 사용하면 어떨까요? 
splice도 사용하지 않는게 좋습니다!

2020-09-22 16:54 UTC, Kihyun92 commented on src/TodoInput.jsx
> +  };
이번 과제의 의도가 무엇인지 한번 더 고민해보시면 좋을 것 같아요! :)

2020-09-22 16:54 UTC, Kihyun92 commented on src/TodoList.jsx
> +        : <p>할 일이 없어요!</p>}
```suggestion
      {todos.length === 0 ? <p>할 일이 없어요!</p> : (
          <ol>
            {todos.map(({ key, value }) => (
              <TodoListItem
                key={key}
                todo={value}
                onClick={() => onClick(key)}
              />
            ))}
          </ol>
        )}
```
list가 없을 경우 처리하는 생각은 좋습니다! 다만 순서를 바꿔서 조금 더 명확하게 처리하는건 어떨까요?

2020-09-22 22:12 UTC, dongakim commented on src/App.jsx
> +    const lastTodo = [...todos].pop();
네. 여기서는 todos를 변경하기 위함이 아니라.
가장 마지막 todo를 추출하기 위해 쓰인 코드입니다.

말씀하신대로 pop은 불변성을 위반하기 때문에
todos에 펼침연산자를 써서 todos는 변하지 않게 했습니다.
다만, **pop은 아예 안쓰는게 좋다**면 빼는게 좋겠네요

2020-09-22 22:38 UTC, dongakim commented on src/TodoList.jsx
> +        : <p>할 일이 없어요!</p>}
순서를 바꾸게 되면 어떤 부분에서 더 명확해지는지 궁금합니다!

2020-09-23 14:34 UTC, Kihyun92 commented on src/TodoList.jsx
> +        : <p>할 일이 없어요!</p>}
조건문의 경우, 비교하는 값이 boolean 타입이면 조금 더 이해하기 쉬운 부분이 있어서요 ㅎㅎ 

타입스크립트를 사용할때도, 삼항연산자는 해당이 안되지만,
```typescript
const todos: [] = [];

...
return(
  {todos.length && <p>hi</p>}
);
```
위와 같이 사용하면, 화면에 0이 노출 되버립니다. `todos.length`의 type이 `number`라서죠.
제가 말씀드린 부분은 습관을 잡아두면 좋겠다는 생각에서 였습니다 ☺️

2020-09-23 14:55 UTC, Kihyun92 requested changes
너무 잘하고 계시네요 👍

2020-09-23 14:55 UTC, Kihyun92 commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
todos의 타입을 배열로 하는것과 객체로 하는것에 어떤 차이가 있을까요?

2020-09-24 08:08 UTC, dongakim commented on src/TodoList.jsx
> +        : <p>할 일이 없어요!</p>}
아 설명 감사합니다! 이해했어요!
아무래도 조건문은 boolean 타입으로 하는게 맞겠네요!

2020-09-24 09:02 UTC, dongakim commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
배열은 키가 index인 객체로 알고 있습니다.
todos 배열을 객체처럼 표현한다면
```js
todos = {
  0: { key: 0, value: '장보기' },
  1: { key: 1, value: '회고 작성하기' }
}
```
이런식으로 표현할 수 있습니다.

리스트 형식으로 표현하기에는
배열형태 todos가 더 수월할 것으로 판단됩니다.

2020-09-24 14:32 UTC, Kihyun92 commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
제가 설명을 잘 못한것 같네요 😅

```javascript
const [todos, setTodos] = useState({
    inputValue: '',
    todo: [
      { id: 0, title: '강의 듣기'},
      {~~}
    ],
    ~~
  })
```

이런 형태면 어떨지 질문 드리고 싶었습니다~ :)

2020-09-24 14:34 UTC, Kihyun92 requested changes

2020-09-24 14:34 UTC, Kihyun92 commented on src/TodoListItem.jsx
> +function TodoListItem({
TodoItem이나 Item이라고만 하는건 어떨까요?

2020-09-26 10:10 UTC, dongakim commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
앱내에서 쓰이는 상태를 하나로 관리한다는 관점에서는
객체로 상태를 관리하는것이 용이하겠네요.

추후 새로운 상태가 추가되거나 삭제될때도 마찬가지구요 :)

2020-09-26 10:11 UTC, dongakim commented on src/TodoListItem.jsx
> +function TodoListItem({
네 생각해보니 List는 없어도 되겠네요!

2020-09-26 13:57 UTC, Kihyun92 requested changes
좋습니다~ 기능은 이제 거의 고칠 곳이 없는 것 같네요 ㅎㅎ

다만 전반적으로 불필요한 부분이나 네이밍이 어색한 곳은 없는지 한번 살펴보셔도 좋을 것 같네요 💯

2020-09-26 13:57 UTC, Kihyun92 commented on src/App.jsx
> +  });
```suggestion
  const [state, setState] = useState({
    inputValue: '',
    todos: [],
  });
```
배열 형태의 변수명의 경우 가능하면 복수형으로 처리하면 어떨까요?

2020-09-26 13:57 UTC, Kihyun92 commented on src/App.jsx
> +      key: lastTodo ? lastTodo.key + 1 : 0,
todo에 대한 키 값을 구분하기 위해 추가한것 같은데, id라고 하는건 어떨까요? 

그리고 이 부분에 예외처리가 들어간 이유가 무엇일까요? 제거할 방법은 없을까요? :)

2020-09-26 13:57 UTC, Kihyun92 commented on src/App.jsx
> +      value: inputValue,
todo의 내용 같은 의미가 담기게 하면 어떨까요? title이나 text와 같은 느낌으로하고 마찬가지로 inputValue보다는 todoTitle 과 같이 처리하는건 어떨까요? 굳이 상태관리하는 부분에서 input에서 들어온 값인지 알 필요는 없는 것 같아서요 :)

2020-10-05 13:04 UTC, merged