🎨 Implement ToDoList But, not separate components
CodeSoom/week2-assignment-2 pull request #36
Opened 2020-09-22 12:59 UTC by Knoa0405

Implement ToDoList But, not separate components, not fix error

2020-09-22 14:11 UTC, hannut91 requested changes
질문사항은 DM으로 남겨주시면 답변드리겠습니다!

2020-09-22 14:11 UTC, hannut91 commented on src/index.jsx
> +}
3항 연산자대신에 Guard Clauses를 사용해서 간단하게 표현할 수 있을까요?

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-22 14:11 UTC, hannut91 commented on src/index.jsx
> +    ul.removeChild(e.target.parentNode);
돔에 직접 접근하는 것은 복잡한 로우 레벨 API를 사용하는 것과 같습니다.

2020-09-23 13:34 UTC, Knoa0405 commented
노트북에서 작업하다가 데스크탑으로 작업할려고 
1. git clone <forked repository> 한 뒤에
2. git remote add upstream <upstream repository> 하고 
3. git fetch upstream main
4. git rebase upstream/main <- 이 단계에서 package.lock.json merge 해주고
5. git rebase --continue 하고 난 뒤에 pull 전에 수정을 먼저 해버려서 이상한 커밋이 생겼습니다.

## 첫번째 리팩토링

1. 삼항 연산자 대신 Guard Clauses 사용을 권장 받았는데,
if( ) return 패턴을 쓰면 return 이 반복될 것 같아서 "&&" 연산자로 처리했습니다.

2. DOM 에 직접 접근하지 않고, Array.filter() 메서드를 사용하여 버튼의 핸들러 함수에서
li key에 사용되는 id 값을 그대로 인자로 넣고 클릭되면 id 값을 제외한 toDo만 담아 반환해주고
toDos 배열의 상태를 변경하였습니다.

2020-09-23 16:59 UTC, hannut91 commented
깃에 대한 내용은 직접보기전까진 어려워서 DM을 주시면 좋을 것 같습니다

2020-09-23 17:06 UTC, hannut91 requested changes

2020-09-23 17:06 UTC, hannut91 commented on src/App.jsx
> +    const input = document.getElementById('input');
DOM에 대해서 직접접근 하는 것은 리액트를 사용하는 이유와 조금 멀어지게 됩니다. DOM에 대한 접근은 굉장히 많은 기능들을 제공하지만 그만큼 복잡하기 때문에 복잡성이 빠르게 증가합니다.

2020-09-23 17:06 UTC, hannut91 commented on src/App.jsx
> +    e.preventDefault();
브라우저의 기본 이벤트 처리를 하지 않도록 하신 것 같아요. UI를 처리하는 것은 UI 컴포넌트에서 하고 상태 변경에 대한 것만 이 함수에서 처리하는 것은 어떨까요?

2020-09-23 17:06 UTC, hannut91 commented on src/UnOrderList.jsx
> +function UnOrderList({ onClick, toDos }) {
`ul`태그를 사용해서 `UnOrderList`라고 표현하신 것 같아요. 구조보다는 실제로 이 컴포넌트가 어떤 의도로 만들어졌는지 컴포넌트이름으로 더 표현해주면 좋을 것 같아요.

2020-09-23 17:06 UTC, hannut91 commented on src/UnOrderList.jsx
> +  );
todo목록이 비어있을 때 비어있다는 메세지를 출력하고 그렇지 않으면 투두목록을 보여주는 것 같아요. Guard Clauses를 사용하면 더 명확하게 의도를 드러낼 수 있습니다.

```js
const isEmpty = (arr) => arr.length === 0;

function UnOrderList({ onClick, toDos }) {
  if (isEmpty(toDos)) {
    return <p>할 일이 없어요!</p>;
  }

  return (
    <ul>
      <List
        onClick={onClick}
        toDos={toDos}
      />
    </ul>
  );
}
```

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-24 03:55 UTC, Knoa0405 commented on src/App.jsx
> +    const input = document.getElementById('input');
리액트도 virtual DOM 을 사용하는데 직접 접근하는거 자체가 잘못된 생각이었네요ㅎㅎ
수정해서 어떻게 하면 직접 접근 없이 할 수 있는지 생각해보겠습니다~!

2020-09-24 03:57 UTC, Knoa0405 commented on src/App.jsx
> +    e.preventDefault();
맞네요 이벤트 처리는 UI 처리 부분이였네요 Ul 컴포넌트에서 처리하도록 수정해보겠습니다!

2020-09-24 03:58 UTC, Knoa0405 commented on src/UnOrderList.jsx
> +function UnOrderList({ onClick, toDos }) {
ToDoList라고 해야겠어요 네이밍이 어렵네요ㅠ  더 나은 표현에 대해서 생각해보겠습니다!

2020-09-24 04:00 UTC, Knoa0405 commented on src/UnOrderList.jsx
> +  );
Gaurd Clauses 가 가독성 측면에서 훨씬 보기 좋네요. 명확하게 의도를 드러낼 수 있는 방향으로
코드 표현력에 신경써보도록 하겠습니다!

2020-09-24 06:15 UTC, Knoa0405 commented
# 두번째 리팩토링

## 1. DOM API 제거

Why ? 

- DOM에 직접 접근하여 사용해주는 방식은 로우 레벨 API 를 쓰는 것과 같고 계속 사용하게
될 때는 복잡성이 증가한다.

- React는 virtual DOM 사용으로 DOM에 직접 접근 없이 상태변화를 감지하여 변화된 값이 생길때마다 렌더링 해주는 방식이므로 React 의 상태 관리 hooks 들을 이용해 컴포넌트 간에 일어나는
이벤트로 변화된 value 값을 저장하고 렌더링해주는 방향으로 생각해야한다.

## 2. 컴포넌트 이름 변경

Why ?

- 컴포넌트 이름 또한 함수 이름이나 변수이름을 정할 때처럼 함수 블록 내부 / 우변의 내용을
함축적으로 담아 대표하는 이름을 정하는 것이 좋다.
따라서 컴포넌트 이름은 UI 컴포넌트의 경우 해당 UI 의 구조보다는 전체 프로젝트에서
해당 UI 가 어떤 포지션에 있는지, 어떤 의도로 만들어졌는지에 따라 이름을 정해주는 것이 좋다.


Guard Clauses 같은 스타일의 코드를 사용하여 보는 입장에서 가독성이 좋은 코드를 만드는 데
초점을 두어야 한다.
> 연산자 사용을 이용한 단순 표현은 누가봐도 이해하기 쉽거나 코드 맥락의 흐름상 위에서 아래로 볼 때 같은 로직이 한 레이블에 있을 경우 사용되면 유용할 것 같다.

2020-09-24 15:12 UTC, hannut91 requested changes

2020-09-24 15:12 UTC, hannut91 commented on src/App.jsx
> +  const [value, setValue] = useState('');
`value`라는 이름은 아무런 의도도 드러내지 않습니다. 변수의 scope가 짧으면 이해가 쉽겠지만, 이 변수는 굉장히 scope가 길기 때문에 상대적으로 더 구체적인 이름을 지어줘야 합니다.

그리고 이 값도 `state`에 같이 관리하는건 어떨까요?

2020-09-24 15:12 UTC, hannut91 commented on src/App.jsx
> +  }
InputValue를 어떻게 다루는지 이것만 봐서는 이해가 어렵습니다. 언제 이 함수가 실행되나요? 이걸 의도로 드러내면 좋을 것 같아요.

그리고 e는 UI의 이벤튼데, 이 함수는 UI에서 발생한 것을 몰라도 상관이 없이 동작해야 합니다.

2020-09-24 15:12 UTC, hannut91 commented on src/InputForm.jsx
> +function InputForm({ onClick, onChange, value }) {
`InputForm`에서 `Input`이 어떤걸 의미하는지 이해하기 어려운 것 같습니다. `Input`이 아무런 의도를 드러내지 않기 때문이에요. `TodoForm`은 어떨까요?

2020-09-24 15:12 UTC, hannut91 commented on src/InputForm.jsx
> +  );
브라우저의 기본 이벤트가 호출되지 않도록 해주셨군요. form안에 있는 submit버튼을 클릭하면 onSubmit이 호출됩니다. 따라서 submit 버튼에는 onClick을 추가하지 않는게 좋을 것 같아요

2020-09-24 15:12 UTC, hannut91 commented on src/ToDoList.jsx
> +  }
`is`라는 prefix가 붙으면 true 혹은 false를 반환할 것 같습니다. 근데 지금 isToDo라는 것은 주어진 값이 ToDo와 같은지 비교할 것 처럼 생겼습니다. 만약 `isTrue`라고 하면 어떤 일을 할 것 같나요?

2020-09-25 09:58 UTC, Knoa0405 commented on src/ToDoList.jsx
> +  }
그렇군요 저는 toDo 가 있는지 없는지 isToDo 로 표현하고 싶었습니다!
말씀해주신대로 생각 해보면, is 라는 prefix를 true false라는 결과를 반환해주는 함수로 
작동할 때 사용해준다고 이해했습니다.
isTrue인 함수가 있다면 비교하는 대상이 참인지 아닌지 비교해주는 역할을 한다고 볼 수 있겠네요. prefix 에 대한 제대로 된 이해없이 제 생각대로 사용한 것 같습니다ㅠ 
비교하는 값인 Array 기준으로 배열 안에 값이 빈값인지 들어있는지를 알려주도록
isEmpty 라고 사용해줘야 겠네요.

2020-09-25 10:36 UTC, Knoa0405 commented on src/InputForm.jsx
> +  );
form 안에서 submit 버튼을 누르면 onSubmit 이 호출되는 건 알고 있습니다.
그럼 버튼에 onClick 이벤트를 등록하지 않고도 클릭을 form 이 감지하는 건가요?

2020-09-25 10:43 UTC, hannut91 commented on src/InputForm.jsx
> +  );
맞습니다 ㅎㅎ

2020-09-26 00:10 UTC, Knoa0405 commented
## 세번째 리팩토링

**1. state에서 toDoText 를 추가하여 input에서 넘겨받는 값을 관리 해줄 수 있도록 변경하였습니다.**

>useState를 굳이 두번 써서 할당해 사용하는 것보다 훨씬 코드도 깔끔해지고 이해하기 쉬워진 것 같습니다.
--------------

**2. value 라는 값이 여기저기 많은 스코프를 거쳐가는데 좀 더 명확한 네이밍이 필요하다는 리뷰를 받아서
value 를 리팩토링 전에는 따로 value 분리했다가 같은 state 에 넣어 준 뒤 toDoText 로 변경했습니다.**

--------------------
> InputValue를 어떻게 다루는지 이것만 봐서는 이해가 어렵습니다. 언제 이 함수가 실행되나요? 이걸 의도로 드러내면 좋을 것 같아요.
>그리고 e는 UI의 이벤튼데, 이 함수는 UI에서 발생한 것을 몰라도 상관이 없이 동작해야 합니다.
**3. 위와 같이 말씀해주신 피드포워드를 받고 목적어 가 "value" 로 모호한 것 같아 "toDoText" 로 특정했습니다.**

그리고 event 도 마찬가지로 UI 이벤트인데 상태 관리를 다루는 함수에서 표현되었기 때문에
input 태그에서부터 target.value 로 넘겨주고 함수 선언식 자체에서는 보여지지 않도록 처리했습니다.
> 사실 이게 말씀해주신 의도가 맞는지 정확히 모르겠습니다!
( 이렇게 하다보니 input 태그부분이 지저분해지는 단점이 있었습니다. )
-------
**4. Form onSubmit 을 이번에 처음 알게되어 사용해봤는데, 내부 submit 버튼에 클릭 이벤트가 등록되있지 않더라도
감지하여 동작된다는 것을 알게되었고, onClick이 button 에서 없어지고 대신 onSubmit 함수가 호출되면 onClick이 호출되도록 변경하였습니다!**
> 이부분도 조금 애매한 부분이라고 생각들지만, 마땅한 방법이 떠오르지 않아 사용했습니다.

-----
**5. prefix "is" 에 대한 이해 없이 영어적인 표현?으로만 생각해서 막 사용한 후에 제대로 된 피드백을 받고 수정하였습니다.**

2020-09-26 16:03 UTC, hannut91 requested changes

2020-09-26 16:03 UTC, hannut91 commented on src/App.jsx
> +  }
`Input`을 변경했을 때 값을 변경하기 때문에 `from`과 `input`이라는 이름이 변수에 들어간 것 같아요. 이 함수에서만 보면 어디서 왔는지 중요하지 않습니다.

2020-09-26 16:03 UTC, hannut91 commented on src/App.jsx
> +      toDos: [...toDos, { toDo: toDoText, id: toDos.length + 1 }],
`id`를 길이로 사용하면 원하는대로 동작하지 않을 가능성이 큽니다. 

예를들어서 
[1, 2, 3]이 있을 때 2를 지웁니다.

[2, 3]이 상태에서 새로운 todo를 등록합니다.

[2, 3, 3] 이 됩니다.

2020-09-27 13:56 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 처음 코드와 마지막 코드를 비교해서 어떤 변화가 있었는지 보시면 좋을 것 같아요 ㅎㅎ

이번 과제를 진행하면서 좋았던 점과 아쉬웠던 점이 있었다면 무엇이 있을까요? 좋았던 것은 어떻게 유지하고 아쉬웠던 것은 어떻게 개선하고 싶으신가요?

2020-09-28 14:29 UTC, hannut91 commented
회고를 슬랙 채널에 올려주셔서 머지합니다 ㅎㅎ 고생하셨어요

2020-09-28 14:30 UTC, merged