Week2_2 todo list app
CodeSoom/week2-assignment-2 pull request #38
Opened 2020-09-22 14:59 UTC by saseungmin

## 📚 과제 목표
- 할 일을 입력해서 등록하고, 완료할 수 있는 간단한 To-do 리스트 만들기

2020-09-23 17:16 UTC, hannut91 requested changes

2020-09-23 17:16 UTC, hannut91 commented on src/App.jsx
> +      id: !todos.length ? 1 : todos[todos.length - 1].id + 1,
조건문에는 부정문이 들어가면 이해하기가 어려워집니다. 특별한 상황이 아니라면 긍정문을 사용하는게 좋을 것 같아요

2020-09-23 17:16 UTC, hannut91 commented on src/App.jsx
> +    setTodos(todos.concat(todo));
스프레드 문접을 사용하시면 더 간단하게 표현할 수 있습니다.

```js
setTodos([...todos, todo]);
```
See also
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2020-09-23 17:16 UTC, hannut91 commented on src/App.jsx
> +  };
실제로 일을 처리하는 함수 이니 `handleRemoveTodo`가 좋을 것 같아요. `on`이 붙은 경우는 실제로 사용하는 입장을 고려한거에요

2020-09-23 17:16 UTC, hannut91 commented on src/components/TodoList.jsx
> +}
Guard Clauses를 사용하면 할 일이 없는 경우를 더 의도를 드러낼 수 있을거에요

```js
const isEmpty = (arr) => arr.length === 0;

function TodoList({ todos, onRemove }) {
  if (isEmpty(todos)) {
    return <p>할 일이 없어요!</p>;
  }

  return (
    <div>
      {todos.map((value, index) => (
        <TodoItem
          key={value.id}
          todo={value.item}
          count={index}
          onRemove={() => onRemove(value.id)}
        />
      ))}
    </div>
  );
}
```

See also
  - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2020-09-23 17:16 UTC, hannut91 commented on src/containers/TodoInsertContainer.jsx
> +function TodoInsertContainer({ onInsert }) {
이번 과제의 목적은 상태를 관리하는 컴포넌트와 UI를 담당하는 컴포넌트를 분리하는 것입니다. 상태를 `App`컴포넌트 한곳에서 모두 관리하고 다른 모든 컴포넌트들은 UI만 담당하도록 관심사를 분리하는거죠. Container 컴포넌트를 사용하는건 지금 다루는 내용은 아니에요.

만약 `todo`를 다른 컴포넌트에서 사용해야 한다면 어떻게 될까요?

2020-09-24 13:50 UTC, saseungmin commented on src/App.jsx
> +    setTodos(todos.concat(todo));
- `concat`은 그다지 좋지 않은 방법인건가요??

2020-09-24 13:51 UTC, saseungmin commented on src/containers/TodoInsertContainer.jsx
> +function TodoInsertContainer({ onInsert }) {
`App` 컴포넌트에 모두 관리할 수 있도록 변경하였습니다.
- `Container` 컴포넌트는 삭제하였습니다.

2020-09-24 15:15 UTC, hannut91 requested changes

2020-09-24 15:15 UTC, hannut91 commented on src/App.jsx
> +  const [todo, setTodo] = useState('');
상태관리를 하나의 객체로 관리하는건 어떨까요?

2020-09-24 15:15 UTC, hannut91 commented on src/App.jsx
> +  };
`e`는 UI 컴포넌트에서 관리해야 하는 객체입니다. `handleOnChange`는 상태를 변경해주는 함수이기 때문에 UI 레이어와는 전혀 상관이 없어야 합니다.

2020-09-24 15:15 UTC, hannut91 commented on src/App.jsx
> +  };
여기에서도 UI이벤트를 다루고 있습니다.

2020-09-24 15:15 UTC, hannut91 commented on src/App.jsx
> +    onInsert(todo);
`on`이라는 이름은 어떤 일이 발생했을 때 실행될 것 같이 생겼습니다. 근데 지금은 직접 호출하고 있는 것 같아요. 함수 이름을 `insert`라고 사용하는건 어떨까요?

2020-09-24 15:15 UTC, hannut91 commented on src/App.jsx
> +      <TodoInsert onChange={handleOnChange} onSubmit={onSubmit} todo={todo} />
`on`이라는 이름은 사용하는 입장에서 바라볼 때 `on`이 붙습니다. 실제 `submit`했을 때 어떤 일을 할지는 `handleSubmit`이라는 이름이 더 적절할 것 같아요

2020-09-24 15:45 UTC, saseungmin commented on src/App.jsx
> +  const [todo, setTodo] = useState('');
```javascript
const [todo, setTodo] = useState('');
```
`todo useState`가  `TodoInsert` 컴포넌트에서만 사용해서 `TodoInsert` 안으로 옮겼습니다.

2020-09-24 15:49 UTC, saseungmin commented on src/App.jsx
> +      <TodoInsert onChange={handleOnChange} onSubmit={onSubmit} todo={todo} />
> `on`이라는 이름은 **사용하는 입장**에서 바라볼 때 `on`이 붙습니다.
- 사용하는 입장에서 바라본다는 말이 이해가 가질 않습니다..😢
- 또한, `handle`을 붙일때와 `on`붙일 때의 차이점이 어떤 부분인지 잘 모르겠습니다.
`handle`이라는 것이 이 함수를 가지고 어떤 액션? 행동? 을 한다? 라는 것이고 `on`은 잘모르겠습니다.

2020-09-24 16:11 UTC, hannut91 commented on src/App.jsx
> +      <TodoInsert onChange={handleOnChange} onSubmit={onSubmit} todo={todo} />
`<TodoInsert />`라는 컴포넌트에서 `submit`했을 때를 다루는 함수는 handleSubmit이라는 이름을 사용합니다. 근데 `<TodoInsert />`에서 `handleSubmit`을 받을 때는 `onSubmit`이라고 받습니다.

2020-09-24 16:12 UTC, hannut91 requested changes

2020-09-24 16:12 UTC, hannut91 commented on src/components/TodoInsert.jsx
> +export default TodoInsert;
과제의 의도는 모든 상태를 App 컴포넌트가 관리하고 다른 컴포넌트는 UI를 그리는 역할만 하는 관심삼의 분리를 하는 것입니다. 여러곳의 상태가 흩어질 경우 관리하기가 어려워집니다. 예를들어서 다른 컴포넌트에서 `todo`를 사용해야 한다면 어떻게 사용해야 할까요?

2020-09-25 02:58 UTC, saseungmin commented on src/App.jsx
> +  });
- 모든 상태를 `App` 컴포넌트가 관리할 수 있게 `App` 컴포넌트에서 `todo`를 사용하기 위해 
객체로 변경하여 상태를 관리하도록 하였습니다.
- 코드리뷰 부탁드립니다~!🙏

2020-09-25 16:17 UTC, hannut91 requested changes

2020-09-25 16:17 UTC, hannut91 commented on src/App.jsx
> +      id: todos.length ? todos[todos.length - 1].id + 1 : 1,
const last = (arr) => arr[arr.length - 1];

```js
const item = {
  id: (last(todos) ?? 0) + 1,
  value,
}
```

이렇게하면 마지막 id에서 + 1을 한다는 더 의도를 드러낼 수 있을꺼에요.

See also
  - https://ko.javascript.info/nullish-coalescing-operator

2020-09-25 16:17 UTC, hannut91 commented on src/App.jsx
> +      <TodoInsert insert={onInsert} change={onChange} todo={todo} />
`TodoInsert` 컴포넌트에서 `insert`했을 때 어떤 함수가 이를 처리할건지를 나타내기 위해서
```js
<TodoInsert onInsert={handleInsert} />
```
이렇게 작성하는건 어떨까요?

2020-09-25 16:17 UTC, hannut91 commented on src/components/TodoItem.jsx
> +}
만약에 우리가 완료된 것을 삭제하지 않고, 완료된 목록으로 출력되도록 수정한다면 `onRemove`를 수정해야 할 것 같아요. 이렇게 변경되더라도 이 컴포넌트는 변경이 없도록 하려면 `onRemove`대신에 `onClick`이라는 이름을 사용하는건 어떨까요?

2020-09-26 03:46 UTC, saseungmin commented on src/App.jsx
> +      id: todos.length ? todos[todos.length - 1].id + 1 : 1,
`null` 병합 연산자는 처음봤습니다!

- 하지만 알려주신 방법대로 해본 결과 
```
{id: "[object Object]1", value: "r"}
```
이런 식으로 마지막 객체 자체에 + 1을 해버리게 되서 에러가 발생하게 됩니다.

- 그래서 아래와 같이 변경하였습니다.
```javascript
const last = (arr) => arr.length && arr[arr.length - 1].id;

const item = {
  id: last(todos) + 1,
  value,
};
```

2020-09-26 16:05 UTC, hannut91 approved these changes
고생하셨습니다. 이번 과제를 진행하면서 좋았던 점과 아쉬웠던 점이 있었다면 무엇이 있을까요? 좋았던 것은 어떻게 유지하고 아쉬웠던 것은 어떻게 개선하고 싶으신가요?

2020-09-27 09:03 UTC, saseungmin commented
이번 2주차도 감사합니다!! 너무 많은 걸 배운 한주였던거 같습니다..
- [회고글](https://github.com/saseungmin/codesoom_code_review_repository/tree/master/week_2) 확인해주시면 감사하겠습니다!

2020-09-27 13:57 UTC, merged