Add TodoList 과제
CodeSoom/week2-assignment-2 pull request #4
Opened 2020-06-09 09:02 UTC by kwonmory

투두 리스트 과제 제출합니다. 

리뷰 부탁드려요~~ 👍

2020-06-09 10:43 UTC, hannut91 requested changes

2020-06-09 10:43 UTC, hannut91 commented on src/TodoApp.jsx
> +import TodoAppHeader from './TodoAppHeader';
위에 빈 줄 하나 추가해주세요

2020-06-09 10:43 UTC, hannut91 commented on src/index.jsx
> +import TodoApp from './TodoApp';
위에 빈 줄 하나를 추가해주세요

2020-06-09 10:43 UTC, hannut91 commented on src/index.jsx
> +const App = () => {
App에서 render하는 일도 같이 하고 있네요. App은 상태만 관리해요

2020-06-09 10:43 UTC, hannut91 commented on src/TodoListItem.jsx
> +
여기 빈 줄이 들어가 있네요

2020-06-09 10:43 UTC, hannut91 commented on src/TodoList.jsx
> +  const todoList = todos.map((todo, index) => (
변수 이름에 List가 들어가면 리스트 자료구조를 나타내는 것 처럼 보여요.

2020-06-09 10:43 UTC, hannut91 commented on src/index.jsx
> +        + todo[0],
의도를 파악하기 어렵네요. 유일한 id를 만들고 싶으샸던 건가요?

2020-06-09 10:43 UTC, hannut91 commented on src/TodoInput.jsx
> +  const [todo, setTodo] = useState('');
아샬님의 강의 카운터앱에서는 상태를 다루는 컴포넌트와 상태로 UI를 만드는 컴포넌트로 관심사를 분리했었어요

2020-06-10 01:15 UTC, kwonmory commented on src/TodoApp.jsx
> +import TodoAppHeader from './TodoAppHeader';
수정했습니닷

2020-06-10 01:15 UTC, kwonmory commented on src/index.jsx
> +import TodoApp from './TodoApp';
이 부분도 수정했습니닷!

2020-06-10 01:17 UTC, kwonmory commented on src/TodoListItem.jsx
> +
앗 수정했습니다. 린트가 이부분은 안잡네용.ㅋㅋㅋ

2020-06-10 01:18 UTC, kwonmory commented on src/index.jsx
> +        + todo[0],
네, id 값이 유일하게 되었으면 좋을 것 같아서 작성해보았는데요, 그래도 겹치는 아이디가 분명히 있을 거라 생각되지만.. 좀 더 이 부분은 고민해보겠습니다.

2020-06-10 01:21 UTC, kwonmory commented on src/TodoList.jsx
> +  const todoList = todos.map((todo, index) => (
그럼 다른 이름 생각해보고 바꾸고 Push 를 해보겠습니다ㅋㅋㅋㅋ

2020-06-10 01:23 UTC, kwonmory commented on src/index.jsx
> +const App = () => {
App 을 분리했습니다~

2020-06-10 01:28 UTC, kwonmory commented on src/TodoList.jsx
> +  const todoList = todos.map((todo, index) => (
`Button` 과 `Buttons` 를 생각해서 `TodoItem` 과 `TodoItems` 로 바꿔봤습니다.

2020-06-10 01:31 UTC, kwonmory commented on src/TodoInput.jsx
> +  const [todo, setTodo] = useState('');
네네 그렇네요. 저 부분도 상태를 빼서 push 해보겠습니다! 굿굿 

![짱구](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSRBohQ4um9D5OtRJhaCaRKZeOB-N1AsK-CUT1tw3G5xHflB0uc&usqp=CAU)

2020-06-10 10:15 UTC, hannut91 requested changes

2020-06-10 10:15 UTC, hannut91 commented on src/index.jsx
> +ReactDOM.render(<App />, document.querySelector('#app'));
`document.getElementById`를 사용할 수도 있어요

2020-06-10 10:15 UTC, hannut91 commented on src/App.jsx
> +    handleAddTodoItem({ todo: input });
여기서 handler 함수를 직접 호출하고 있네요. handler는 UI이벤트에 대해서 다루는 함수이니 구분해주는게 좋을 것 같아요

2020-06-10 10:15 UTC, hannut91 commented on src/TodoInput.jsx
> +    </form>
`form`을 사용할 때는 button에 `onClick`을 사용하기 보다는 `form`에 `onSubmit`을 사용하시는게 좋아요.

2020-06-10 10:15 UTC, hannut91 commented on src/TodoItems.jsx
> +}
`todos`의 길이를 먼저 확인해서 먼저 반환해주면 더 간단하게 표현할 수 있을거에요

```js
if (todos.length === 0) {
  return '할일이 없어요'
}

return todos.map(...);
```

2020-06-10 10:15 UTC, hannut91 commented on src/App.jsx
> +        + todo[0],
`id`를 만드는 곳이 복잡해보이네요 별도의 함수로 분리하는 것은 어떨까요?

2020-06-12 12:18 UTC, kwonmory commented on src/TodoInput.jsx
> +    </form>
https://ko.reactjs.org/docs/forms.html

2020-06-12 23:48 UTC, hannut91 requested changes

2020-06-12 23:48 UTC, hannut91 commented on src/TodoItems.jsx
> +      )) }
여기 빈 칸 하나가 들어갔네요!

2020-06-12 23:48 UTC, hannut91 commented on src/App.jsx
> +        input,
사용자가 입력하는 텍스트의 변수 이름을 `input`으로 하셔서 `todo`의 속성 이름에도 `input`을 사용하신 것으로 보여요. `todo`만 보면 `input`이 의미하는 바를 파악하기 어려울 것 같아요. `title`은 어떨까요?

2020-06-12 23:48 UTC, hannut91 commented on src/App.jsx
> +}
`uuid`를 사용해도 좋을 것 같아요

2020-06-13 06:37 UTC, kwonmory commented on src/TodoItems.jsx
> +      )) }
앗 수정했습니다.

2020-06-13 06:38 UTC, kwonmory commented on src/App.jsx
> +        input,
오 넵 `title` 가 파악하기 쉽네요!

2020-06-13 06:39 UTC, kwonmory commented on src/App.jsx
> +}
와우.. UUID 생각도 못했었네요. 좋은 팁 감사합니다.

2020-06-13 10:07 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 더 자세한 내용은 아샬님 과제 풀이를 통해 복습해주세요

2020-06-13 10:07 UTC, hannut91 commented on src/App.jsx
> +}
https://www.npmjs.com/package/uuid

이런걸로 사용하는 걸로 기대했는데 직접 만드셨군요!

2020-06-13 10:50 UTC, merged