Dongjo/week2 assigment 2
CodeSoom/week2-assignment-2 pull request #43
Opened 2020-09-24 17:30 UTC by ParkDongJo

--------------------------------------------------------------------------------------------------------------
### [ 작업내용 ]
- [x] 디렉토리 구조 잡기
- [x] 각 컴포넌트 골격 잡기
- [x] Context API 연결하기
- [ ] Context Provider handler들 구현하기
- [ ] 예외처리
- [ ] lint & test 최종 통과 

### [ 시간 남을 시 할 일 ]
- Context API reducer 정리하기
--------------------------------------------------------------------------------------------------------------

2020-09-25 16:56 UTC, hannut91 requested changes

2020-09-25 16:56 UTC, hannut91 commented on src/index.jsx
> +import App from './App';
위에 빈 줄 하나를 추가해서 리액트 라이브러리와 로컬 컴포넌트 임포트를 분리시켜주면 좋을 것 같아요

2020-09-25 16:56 UTC, hannut91 commented on src/context/TodosProvider.jsx
> +  const { todos, inputValue } = state;
사용자가 입력한 값이라서 `inputValue`라고 하신 것 같아요. 만약 사용자의 입력으로도 수정이 가능하지만, 서버에서 정보를 가져와서 저장해야한다면 그 때는 어떤 이름을 사용해야 할까요?

2020-09-25 16:56 UTC, hannut91 commented on src/context/TodosProvider.jsx
> +    });
상태를 변경할 때, 이전 상태로만 다음 상태가 결정될 때 이렇게 사용하는 걸로 알고 있습니다. `generateId()`는 바깥에 있는 변수니, 온전히 이전 상태로만 결정된다고 보기 어렵지 않을까요?

2020-09-25 16:56 UTC, hannut91 commented on src/context/TodosProvider.jsx
> +  };
`pId`가 무엇을 나타내는건가요? 그냥 `id`대신에 추가적으로 어떤 의도를 더 드러내기위해서 사용하신 건가요?

2020-09-25 16:56 UTC, hannut91 commented on src/components/views/Input.jsx
> +    onChange={(event) => { onChange(event); }}
`onChange={onChange}`이렇게 사용해도 동일한 결과를 얻을 수 있을까요?

2020-09-25 16:56 UTC, hannut91 commented on src/components/views/Button.jsx
> +};
`type`의 기본 값을 button으로 하여 이렇게 작성하는 건 어떨까요?

```
const Button = ({ children, type = "button", onClick }) => {
  return (
    <button type={type} onClick={onClick}>
      {children}
    </button>
  );
};
```

2020-09-25 16:56 UTC, hannut91 commented on src/components/views/Todo.jsx
> +);
`data`는 어떤 의도도 드러내지 않는 것 같아요. `todo`는 어떨까요?

그리고 완료했을 때 지금은 삭제하기로 결정되어 있는데 만약에 삭제하지 않고 완료목록으로 옮긴다고 하면 handleRemove대신에 어떤 이름을 써야할까요? 그리고 이렇게 바뀌었을 때 이 컴포넌트까지 영향을 받는게 괜찮을까요?

2020-09-25 16:56 UTC, hannut91 commented on src/context/TodosProvider.jsx
> +  const getTodo = (pId) => [...todos].filter((_, id) => id === pId);
`filter`에서 두 번째 인자는 index를 나타내는데 index가 id를 의미하나요?

2020-09-25 17:09 UTC, ParkDongJo commented on src/components/views/Button.jsx
> +};
@hannut91 
아 넵 저도 위와 같은 방법이 깔끔하다고 생각합니다. 다만 lint에 걸리더라구요 
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md
ㅠㅠ

lint자체를 바꾸는건, 팀원의 동의 없이는 안된다고 판단해서 lint 에 맞추느라 저렇게 했습니다. 혹시 좋은 방법이 있을까요?

2020-09-25 17:09 UTC, ParkDongJo commented on src/context/TodosProvider.jsx
> +    });
@hannut91 
아! 넵 일괄되게 코드를 작성하는 것이 중요하군요. 그렇다면, prevState를 활용하지 않고 parameter로 입력 내용을 받는 걸로 변경하겠습니다.

2020-09-25 17:09 UTC, ParkDongJo commented on src/context/TodosProvider.jsx
> +  };
@hannut91 
코드 전반적으로 parameter로 넘어오는 변수에는 p를 붙여주고 있습니다..
변수명이 함수에서 겹치거나 하는걸 방지하고, 넘어온 값이라는 의미를 부여하기 위해서요.

2020-09-25 17:09 UTC, ParkDongJo commented on src/index.jsx
> +import App from './App';
@hannut91 
아!! 1차 과제에서 지적해주셔서, 다른 곳은 다 띄웠는데.. 여길 빠져먹었습니다. 
고쳐 넣겠습니다.

2020-09-25 17:12 UTC, ParkDongJo commented on src/context/TodosProvider.jsx
> +  const getTodo = (pId) => [...todos].filter((_, id) => id === pId);
@hannut91 
왓더.. 제가 잘못 생각했습니다.
`
const getTodo = (pId) => [...todos].filter((todo) => todo.id ===  pId);
`
이렇게 바꾸겠습니다.

2020-09-27 15:39 UTC, ParkDongJo commented on src/components/views/Todo.jsx
> +);
@hannut91 
아.. 이해했습니다. 말씀을 곡씹어 보니 느끼는 바가 있습니다.

Todo, Button, Input 등등.. 공통적으로 사용하는 모듈은
특수한 기능을 의미하는 네이밍이 오히려 독이겠다는 생각이 들었습니다.
감사합니다.

2020-09-27 15:50 UTC, ParkDongJo commented on src/components/views/Input.jsx
> +    onChange={(event) => { onChange(event); }}
@hannut91 
피드벡 감사합니다. 이 부분을 코드 개선을 함께 했어야 했는데, 놓쳤더라구요.
말씀해주셔서 바로 개선했습니다.

2020-09-28 14:28 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 많이 바쁘신것 같은데 꾸준히 과제를 하는 모습을 보니 좋네요 ㅎㅎ

이번 과제를 진행하면서 좋았던 점과 아쉬웠던 점이 있었다면 무엇이 있을까요? 좋았던 것은 어떻게 유지하고 아쉬웠던 것은 어떻게 개선하고 싶으신가요?

2021-01-17 12:59 UTC, merged