Todo 과제 진행
CodeSoom/week2-assignment-2 pull request #45
Opened 2020-09-25 13:21 UTC by comejtome508

화면에 입력창 출력하고 입력한 것 onClick으로 받는 것까지 진행하였습니다.
state에 배열을 넣고 concat으로 받을 때 setState로 관리하는 것에 익숙하지 않아 시행착오 중입니다.

2020-09-25 16:45 UTC, hannut91 requested changes
잘해주고 계신데, 지금 너무 한번에 많이 구현하시려고 한 것 같아요. 가장 단순한 것 부터 하나씩 구현해보면 좋을 것 같아요. 

그리고 코드가 정렬이 잘 안되어있는데 편집기의 자동정렬 기능을 사용해서 정리를 하면 코드를 읽는데 더 도움이 되고 그래서 작성할 떄도 더 편하실거에요.

그리고 eslint를 통해서 내가 작성한 코드에 어떤 오류가 있을 수 있는지 검사해주는 도구를 사용하면, 더 편리하고 더 좋은 코드를 작성하는 연습이 자동으로 될거에요. `npm run lint`라는 명령어를 사용해서 실행하면 무엇이 잘못되었는지 알려줍니다

2020-09-25 16:45 UTC, hannut91 commented on src/components/App.jsx
> +    });
사용자에게 입력을 받기 때문에 `input`이라는 이름을 사용하신 것 같아요. 만약에 이 텍스트가 사용자 입력에 의해서도 변경될 수 있지만, 서버에서 데이터를 가져와서도 변경될 수 있는 값이라면 어떻게 이름을 지어야 할까요?

2020-09-26 12:58 UTC, comejtome508 commented
> 잘해주고 계신데, 지금 너무 한번에 많이 구현하시려고 한 것 같아요. 가장 단순한 것 부터 하나씩 구현해보면 좋을 것 같아요.
> 
> 그리고 코드가 정렬이 잘 안되어있는데 편집기의 자동정렬 기능을 사용해서 정리를 하면 코드를 읽는데 더 도움이 되고 그래서 작성할 떄도 더 편하실거에요.
> 
> 그리고 eslint를 통해서 내가 작성한 코드에 어떤 오류가 있을 수 있는지 검사해주는 도구를 사용하면, 더 편리하고 더 좋은 코드를 작성하는 연습이 자동으로 될거에요. `npm run lint`라는 명령어를 사용해서 실행하면 무엇이 잘못되었는지 알려줍니다

> 넵 eslint를 항상 과제 마지막에 하려고 하였는데 틈틈히 진행해야겠습니다

2020-09-26 12:59 UTC, comejtome508 commented on src/components/App.jsx
> +    });
getText로 바꿔보았습니다!

2020-09-26 13:07 UTC, comejtome508 commented
**기능 구현**

- [ ] 사용자는 할 일을 입력할 수 있습니다.

- [ ] 사용자는 추가 버튼을 눌러서 할 일을 추가할 수 있습니다.

- [ ] 사용자는 할 일 목록을 볼 수 있습니다.

- [ ] 사용자는 완료 버튼을 눌러 할 일을 삭제할 수 있습니다.


**요구사항**

- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.

- [ ] 모든 인수 테스트를 통과시켜야 합니다.

- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.

**제한 조건**
if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
switch는 사용하실 수 없습니다.
let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

**진행 중 이슈**
- DeleteItem 컴포넌트에 App에 있는 useState값을 가져와서 쓰도록 해야함
- filter에 필요한 사항을 정확하게 이해하고 사용해야 함
- id를 length로 잡았을 때 중간 순서의 값을 삭제하고 추가했을 때 id가 겹치지 않는지 고려

2020-09-26 16:07 UTC, hannut91 requested changes

2020-09-26 16:07 UTC, hannut91 commented on src/components/App.jsx
> +  });
`getText`는 무엇으로부터 값을 가져올 것 같아요. 하지만 지금은 그냥 단순히 객체죠.

2020-09-26 16:07 UTC, hannut91 commented on src/components/DeleteItem.jsx
> +    };
특별한 상황이 아니면 줄임알은 사용하지 않으시는게 좋습니다. `deleteItem`이 더 나을 것 같아요

2020-09-26 16:07 UTC, hannut91 commented on src/components/DeleteItem.jsx
> +    };
그리고 여기서 setItems은 존재하지 않습니다.

2020-09-26 16:07 UTC, hannut91 commented on src/components/InputBtn.jsx
> +      id: items.length,
`length`를 사용할 경우 의도치 않은대로 동작할 수 있습니다. 예를들어 

[1, 2, 3]에서 2를 지우면

[1, 3]이 됩니다. 여기서 새로운 투두를 등록하면
[1, 3, 3]이 됩니다.

2021-01-17 12:59 UTC, closed without merging