TodoList 만들기
CodeSoom/week2-assignment-2 pull request #46
Opened 2020-09-26 09:53 UTC by hanamDeveloper

안녕하세요 트레이너님
리뷰 부탁드립니다!
항상감사합니다!

2020-09-26 15:01 UTC, Kihyun92 requested changes
과제2-1을 다시 한번 떠올리시면서 컴포넌트 분리를 하시면 좋을 것 같습니다~

전반적으로 이벤트 핸들러 네이밍도 컨벤션에 맞춰주시면 좋을 것 같아요~ [참고](https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364)

2020-09-26 15:01 UTC, Kihyun92 commented on src/CreateTodo.jsx
> +const CreateUser = ({ todolist, onChange, onCreate }) => {
왜 User 인가요?

2020-09-26 15:01 UTC, Kihyun92 commented on src/index.jsx
> +
공백 제거해주세요.

2020-09-26 15:01 UTC, Kihyun92 commented on src/index.jsx
> +  return (
공백 추가해주세요.

2020-09-26 15:01 UTC, Kihyun92 commented on src/index.jsx
> +  const onCreate = () => {
`handleClickAddTodo`와 같은 네이밍은 어떤가요?
`onCreate`는 너무 간결해 함수명만 보고 기능을 예측할 수 없는 것 같아요~

네이밍은 간결하고, **명확해야**합니다.

그리고 이벤트 핸들러 컨벤션을 맞춰주시면 좋을 것 같습니다~ [참고](https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364)

2020-09-26 15:01 UTC, Kihyun92 commented on src/index.jsx
> +  const nextId = useRef(1);
상태값은 상태값끼리, 함수는 함수끼리 배치해준다면 같이 코드를 보는 동료들이 보기 편할 것 같네요 :)

2020-09-26 15:01 UTC, Kihyun92 commented on src/index.jsx
> +    todolist: '',
`todoList`라 함은 뭔가 배열과 같은 형태일 것 같은데, `string` 타입이네요. `todoTitle`과 같이 todo에 노출될 값임을 알 수 있으면 어떨까요?

2020-09-26 15:01 UTC, Kihyun92 commented on src/index.jsx
> +  const [todos, setTodos] = useState([]);
inputs와 todos를 각각의 상태로 관리하는 것도 좋지만, 하나의 상태 내에서 관리할 순 없을까요?
이 경우 어떤 장단점이 있을까요? :)

2020-09-27 06:51 UTC, hanamDeveloper commented on src/CreateTodo.jsx
> +const CreateUser = ({ todolist, onChange, onCreate }) => {
강의보면서 따라하고있었다가 그대로 따라쳤었네요.. 주의하겠습니다

2020-09-27 06:51 UTC, hanamDeveloper commented on src/index.jsx
> +
제거했습니다.

2020-09-27 06:51 UTC, hanamDeveloper commented on src/index.jsx
> +  return (
추가되었습니다.

2020-09-27 06:53 UTC, hanamDeveloper commented on src/index.jsx
> +  const onCreate = () => {
props 로 연결되는 것들은 on+이름을 짓고 
함수로는 handle+이벤트 로 짓는걸로 이해하고있습니다.
이렇게 알고있으면 될까요?

2020-09-27 06:53 UTC, hanamDeveloper commented on src/index.jsx
> +  const nextId = useRef(1);
넵 수정했습니다 감사합니다.!

2020-09-27 06:54 UTC, hanamDeveloper commented on src/index.jsx
> +    todolist: '',
넵 수정했습니다

2020-09-27 06:56 UTC, hanamDeveloper commented on src/index.jsx
> +  const [todos, setTodos] = useState([]);
하나의 상태로 관리하면 코드가 훨씬 짧고 간결해질것같습니다.
input이랑 굳이 따로 관리할 필요는 없는것같네요 아직 방법은 못찾았지만 한번 찾아보겠습니다.!

2020-09-27 14:58 UTC, Kihyun92 approved these changes
고생하셨습니다~ 이번주 과제하시면서 많은 고민을 하신것같아요. 앞으로도 목표하신대로 꾸준히 해주셨으면 좋겠습니다~

아샬님의 과제 풀이 꼭 보시면 좋을 것 같아요! 👍

2020-09-27 14:58 UTC, Kihyun92 commented on src/AddTodo.jsx
> +
불필요한 공백은 제거해주세요~

2020-09-27 14:58 UTC, Kihyun92 commented on src/AddTodo.jsx
> +          {' '}
html 태그인 ol, li를 사용하면 굳이 id값을 표시해줄 필요가 없을 것 같네요~

2020-09-27 14:58 UTC, Kihyun92 commented on src/TodoTitle.jsx
> +          display: todos.length === 0 ? 'block' : 'none',
스타일로 엘리먼트의 노출 여부를 처리하는것보다, jsx를 활용해서 처리하면 좋을 것 같네요~

2020-09-27 23:15 UTC, hanamDeveloper commented on src/AddTodo.jsx
> +
넵.. 알겠습니다!

2020-09-27 23:15 UTC, hanamDeveloper commented on src/AddTodo.jsx
> +          {' '}
엇 그러네요! 생각도못했어요 감사합니다!

2020-09-27 23:16 UTC, hanamDeveloper commented on src/TodoTitle.jsx
> +          display: todos.length === 0 ? 'block' : 'none',
넵 한번 해보겠습니다 감사합니다

2020-10-05 13:02 UTC, Kihyun92 commented
test를 통과하지 못한것 같은데 확인 부탁드립니다~ 이후에 머지할게요~

2021-01-17 12:59 UTC, closed without merging