Feat: 간단한 TodoApp 생성
CodeSoom/week2-assignment-2 pull request #48
Opened 2021-01-26 09:11 UTC by gyeongwon1275

- 컴포넌트를 의미와 역할에 따라 분리하려 했습니다. 
- App.jsx 에서 컴포넌트를 세세히 나열하지 않도록 했습니다.

2021-01-26 13:59 UTC, Kihyun92 requested changes
이번 과제의 의도를 잘 이해하고 계시고, 리엑트도 잘하시는 것 같네요 좋습니다 👍🏼

2021-01-26 13:59 UTC, Kihyun92 commented on src/TodoListPage.jsx
> +  );
현재 컴포넌트의 역할이 무엇인가요? 

관심사 측면에서 봤을때 단순히 페이지들을 관리하는 역할이라면 이런 상태값 관리는 더 상위에서 하고 현재 컴포넌트에서는 보여주는 부분을 관리하는게 좋을 것 같아요~

2021-01-26 13:59 UTC, Kihyun92 commented on src/TodoListPage.jsx
> +  const [TodoState, setTodoState] = useState({
`TodoState`의 맨 앞글자를 대문자로 시작하신 이유가 있나요? 크게 없다면 소문자로 변경하는게 좋을 것 같습니다 :)

2021-01-26 13:59 UTC, Kihyun92 commented on src/TodoListPage.jsx
> +    (indexToDelete) => {
함수명을 통해 지울 투두를 구분할 값임은 알 수 있을 것 같아서 index나 id 라고만 하는건 어떨까요?

2021-01-26 13:59 UTC, Kihyun92 commented on src/TodoListPage.jsx
> +        ),
추후 확장성을 고려해서 영향을 받지 않는 값들은 이렇게 처리할 수 있을 것 같네요.

```suggestion
      setTodoState({
        ...TodoState,
        todoList: todoList.filter(
          (todoText) => todoText !== todoList[indexToDelete],
        ),
```

2021-01-27 01:35 UTC, gyeongwon1275 commented on src/TodoListPage.jsx
> +  );
TodoList Page 자식 컴포넌트들이 사용할 상태, 함수들이라고 생각해서 TodoListPage 컴포넌트 안에 선언했는데 
애초에 이름을 Page 로 한 의미가 없어졌네요 App 에서 선언하고 props 로 받는 걸로 수정하겠습니다!

2021-01-27 01:35 UTC, gyeongwon1275 commented on src/TodoListPage.jsx
> +  const [TodoState, setTodoState] = useState({
아.. 오타를 확인 못했네요 todoState 로 수정하겠습니다!

2021-01-27 01:37 UTC, gyeongwon1275 commented on src/TodoListPage.jsx
> +    (indexToDelete) => {
함수에서 이미 삭제한다는 것을 보여줬는데 굳이 변수에 반영할 필요는 없겠네요 
단순하게 수정해보겠습니다.

2021-01-27 01:38 UTC, gyeongwon1275 commented on src/TodoListPage.jsx
> +        ),
완료한 Todo를 삭제할 때는 input value 를 초기화할 필요는 없었네요 피드백 주신대로 수정해보겠습니다!

2021-01-27 14:06 UTC, Kihyun92 requested changes
리뷰를 잘 반영해주시니 드릴 피드백이 거의 없네요 😂

`id`를 사용하여 todo를 관리하는 방식에 대해서 고민해보시면 좋을 것 같아요. 배열의 index로도 처리가 가능하지만, 더 확장이 되고 기능이 추가됐을때는 어떨까요?

2021-01-27 14:06 UTC, Kihyun92 commented on src/App.jsx
> +        todoList: todoList.filter((todoText) => todoText !== todoList[index]),
텍스트 값으로 체크하고 있네요. 이 방법도 좋지만, `id`와 같은 값을 사용하는 건 어떨까요?

인덱싱에도 장점이 있을 것 같아요~

2021-01-27 14:06 UTC, Kihyun92 commented on src/App.jsx
> +      setTodoState({ ...todoState, todo: e.target.value });
`e`도 좋지만, 이번 과제의 제한조건 중에 하나가 `함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.`입니다. 물론 우리에겐 익숙한 용어지만 조금 더 길더라도 명확하게 써주는게 동료들에게도 도움이 될 것 같아요~

2021-01-28 01:55 UTC, gyeongwon1275 commented on src/App.jsx
> +      setTodoState({ ...todoState, todo: e.target.value });
onChange 에 할당할 함수 parameter 로 e 를 쓰는코드들이 많아서 습관적으로 써버리고 말았네요 
event 로 수정하겠습니다.

2021-01-30 13:08 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍🏼 

강의 풀이 영상을 꼭 보시고, 아샬님은 어떤 관점에서 컴포넌트를 분리하시는지 보시면 좋을 것 같습니다 ☺️

2021-01-31 13:16 UTC, merged