[week2/assingment2] 과제 리뷰 부탁드립니다.
CodeSoom/week2-assignment-2 pull request #5
Opened 2020-06-09 15:34 UTC by yeonhwakim

- `list 상태를 관리하는 `App` 컴포넌트 분리
- todo를 입력하는 `Form` 컴포넌트 분리
- list를 보여주는 `Ul`, `List` 컴포넌트 분리

2020-06-09 23:45 UTC, wholemann requested changes
Test가 깨지네요.

로컬에서 Test를 돌려보시고 수정 후 제출해주시기 바랍니다:)

2020-06-09 23:52 UTC, yeonhwakim commented
> Test가 깨지네요.
> 
> 로컬에서 Test를 돌려보시고 수정 후 제출해주시기 바랍니다:)

아직 로직은 구현 못했고 UI만 구현한 상태여서요ㅎㅎ

2020-06-10 10:29 UTC, wholemann requested changes
일단 컴포넌트 이름이 모두 빠져있네요. 이 부분은 수정해주세요:)

Ul과 List 둘 다 있어서 햇갈립니다.

강의에 나온 것처럼 Page 컴포넌트를 우선 생각해보면 좋겠네요.

App->Page로 가는 구조를 생각해보세요.

2020-06-10 10:29 UTC, wholemann commented on src/App.jsx
> +export default () => {
컴포넌트 이름은 어디에 있나요?

2020-06-10 10:29 UTC, wholemann commented on src/App.jsx
> +  const [value, setValue] = useState('');
어떤 상태를 나타내는지 알 수가 없습니다. 
이 컴포넌트에선 어떤 상태가 있나요? 변수명으로 명확하게 표현되어야 합니다.

또한 상태는 하나의 객체로 관리하려고 해보세요.

2020-06-10 10:29 UTC, wholemann commented on src/App.jsx
> +    setValue('');
하나의 객체로 상태를 관리한다면 이 부분은 단순화 할 수 있을 겁니다.
지금은 상태가 개별 변수로 선언되어 있습니다.

2020-06-10 10:29 UTC, wholemann commented on src/App.jsx
> +  const handleRemove = (e) => {
핸들러 함수에서 어떤 행위에 대한 핸들러인지 표현되면 좋겠습니다.
왜냐하면 전달하는 핸들러 종류가 많아서 구분이 힘들기 때문입니다.
onChange와 onClick이 혼재되어 있다면 더욱 구분이 어렵겠죠?

handleClickAddTodo 등이면 좀 명확하겠죠?

2020-06-10 10:29 UTC, wholemann commented on src/App.jsx
> +        !list.length
명확한 조건식을 써주면 더 좋겠네요.

부정 조건문은 가독성을 저해합니다.

2020-06-10 10:29 UTC, wholemann commented on src/Ul.jsx
> +      <List item={item} index={index} key={`${item.id}`} handleRemove={handleRemove} />
key={item.id} 면 됩니다.

2020-06-10 10:29 UTC, wholemann commented on src/Ul.jsx
> +export default ({ list, handleRemove }) => (
Ul은 태그명입니다. List라고 컴포넌트명을 명확하게 했으면 좋겠네요.

2020-06-13 11:25 UTC, wholemann requested changes
몇 가지 아쉬운 부분 comment 남겼습니다.

잘 고민해보시고 질문있으시면 언제든 DM 주세요:)

다음 PR 기다리겠습니다.

2020-06-13 11:25 UTC, wholemann commented on src/App.jsx
> +      todoList: [...todoList, { id: todoList.length, todo: inputValue }],
배열의 길이를 id로 한다면 어떤 상황에 문제가 생길 수 있을까요?

Hint: 배열은 가변 길이 자료구조입니다.

2020-06-13 11:25 UTC, wholemann commented on src/App.jsx
> +      handleClickRemoveTodo={handleClickRemoveTodo}
onSubmitXXX
onChangeXXX
onClickXXX

가 적절한 props key값으로 보여집니다.

2020-06-13 11:25 UTC, wholemann commented on src/TodoPage.jsx
> +export default function todoPage({
컴포넌트 명은 대문자로 시작해주세요.
어떤 상황에 문제가 될 수 있는지 알아두시기 바랍니다.

- [JSX 컴포넌트 명명](https://ko.reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)

2020-06-13 11:25 UTC, wholemann commented on src/TodoPage.jsx
> +  state, handleSubmitAddTodo, handleChangeInput, handleClickRemoveTodo,
state를 이 부분에서 구조분해 할당한다면 어떨까요?

2020-06-14 02:21 UTC, wholemann requested changes
혹시 별도의 컴포넌트로 각 Item을 분리하지 않은 이유를 알 수 있을까요?

만약 요구사항이 추가되어 각 Todo가 복잡해진다면 List 컴포넌트의 복잡도는 어떻게 될까요?

또 완료 리스트라는 기능이 추가된다면 어떤 일이 벌어질까요?

아래 자료를 다시 읽어보실 때 인 것 같습니다ㅎㅎ

- [Component](https://ko.reactjs.org/docs/components-and-props.html)
- [리스트와 Key](https://ko.reactjs.org/docs/lists-and-keys.html)

2020-06-14 02:21 UTC, wholemann commented on src/App.jsx
> +      todoList: [...todoList, { id: inputValue + generateRandom(), todo: inputValue }],
inputValue를 기반으로 id를 생성해야 할까요? 이유가 뭔가요?

2020-06-14 07:54 UTC, yeonhwakim commented on src/App.jsx
> +      todoList: [...todoList, { id: inputValue + generateRandom(), todo: inputValue }],
음 처음에는 유니크한 키여야한다고 생각되서 inputValue를 생각했어요.
이렇게 하면 똑같은 값을 넣게 되면 중복이되서 뒤에 todoList.length를 추가해볼까로 시작해서 여기까지 왔네요;;;;

2020-06-14 11:25 UTC, wholemann requested changes
거의 마지막 피드백일 듯 하군요.

다음 PR이 마지막이길 기도하며ㅎㅎ 수정 요청 드립니다:)

2020-06-14 11:25 UTC, wholemann commented on src/List.jsx
>        {list.map((item) => (
list라고 하면 너무 모호합니다. 어떤 자료들이 들어있는지 알 수가 없네요.

tasks or todos와 같은 표현은 어떨까요?

2020-06-14 11:25 UTC, wholemann commented on src/Item.jsx
> +export default function Item({ item, onClick }) {
Item({ todo: { id, title }, onClick }) 과 같이 표현할 수도 있겠네요.

그러면 의미적으로 명확하고 하단에서 사용하는 변수도 더 심플하게 표현 가능하겠죠?

2020-06-14 11:25 UTC, wholemann commented on src/App.jsx
> +      todoList: todoList.filter((item) => removeId !== item.id),
item보다는 todo라고 명확하게 표현하는 게 좋겠어요.

2020-06-14 11:25 UTC, wholemann commented on src/App.jsx
> +      todoList: [...todoList, { id: shortId.generate(), todo: inputValue }],
랜덤키 생성은 좋네요!

2020-06-14 12:05 UTC, wholemann approved these changes
이정도에서 Merge하도록 할게요. 고생하셨습니다.

나머진 아샬님 피드백 강의에서 얻어가실 수 있을 겁니다:)

2020-06-14 12:05 UTC, merged