투두리스트 만들기 😮
CodeSoom/week2-assignment-2 pull request #50
Opened 2021-01-26 11:03 UTC by dodoongtak

2021-01-26 11:52 UTC, dodoongtak commented
설계를 하고 코드 진행에 앞서서, 스펙에 필요한 컴포넌트들을 분별하여 미리 생성해서 진행 해볼려고 합니다. 

Q1. 무엇을 만들 계획의 규모에 따라 다르겠지만, 필요하다고 생각되는 컴포넌트들을 미리 생성 해서 하는게 좋을까요?

아니면

필요한 컴포넌트 단일 생성 -> 기능 완료 -> 필요한 컴포넌트 생성 -> 기능완료 이런 절차로 해야 좋을까요?

예시) 
form/input/button 컴포넌트 생성 -> Input Feature 구현 완료 -> List/Task(ul/li) 컴포넌트 생성 -> form 제출 시 list append 기능 완료...

2021-01-26 14:09 UTC, Kihyun92 requested changes
좋은 고민인 것 같아요! 스펙에 필요한 컴포넌트들을 분별하여 미리 생성해보셨어요. 이 경우 어떤 장점과 단점이 있다고 생각하시나요? 한번 정리해보셔도 좋겠네요 :)

A1. 이 부분은 워터폴과 에자일 모델에 대한 부분 같아요 ㅎㅎ 설계를 먼저 하고 개발할지, 일단 작동하도록 필요한 기능들부터 구현하며 기능을 추가할지. 몇십년간 정말 많은 개발자들이 고민했던 과정을 거쳐보고 계신 것 같아요! 넘 좋습니다. 관련해서는 프로젝트마다 다르고, 정답이 없는 것 같아요..ㅎㅎ

개인적으로 관련한 책들을 추천하자면 윤석님 주도하에 지난 리액트 2기분들과 스터디를 했던 [The nature of software development](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788968484650&orderClick=LEa&Kc=), [클린 애자일](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788966262861&orderClick=LEa&Kc=)을 추천합니다 ㅎㅎ 둘다 얇지만 역사들이 정리되어 있어서 이해하는데 도움이 되실거에요 ☺️

고민하고 정리한 부분이 있다면 동료들에게 공유해주셔도 좋을 것 같습니다 💯

2021-01-27 04:29 UTC, dodoongtak commented
Button Component를 활용을 못했습니다. 

이유: 
1. Form에서 사용하는 추가 Button의 타입은 submit, 완료를 하는 버튼의 타입은 button으로 진행할려했지만 default type을 건드리면 안된다는 warning이 나와 중단했습니다. 타입을 둘다 submit으로 작동에는 문제는 없지만 type에 차별을 두고 싶었습니다.

2. 추가 버튼의 submit은 다른 prop들을 넘겨줄 필요없는 반면, 완료 버튼에는 id, 완료를시키는 함수를 넘겨주어 Button Component가 독립적이 아니게 변질되는거같아 중단했습니다. 그래도 Button Component를 사용하고 싶다하면 추가버튼에서 필요없는 prop을 일일이 작성해야되는게 또 변수를 발생시킨다고 판단했습니다. 

예시 ) 
추가 버튼 
```
//Form.jsx
<button type="submit">추가</button>
```

완료버튼
```
//Task.jsx
 <button type="button" onClick={() => onClick(id)}>완료</button>
```

Task에 있는 prop을 전부 Button Component에 넘겨준다 하였을 떄 Form.jsx에서도 
```
<Button id ={null} onClick={null} ">추가</button>
```
이렇게 번거로운 작업을 해야되는거 같아서 default value를 주면 해결이 되지만서도, 
앞서 언급드렸다시피, Button Component가 독립적이 아니게 변질되는거같아보입니다.

```
function Button({ children, id = null, onClick = null }) {
  return (
    <button type="button">{children}</button>
  );
}
```

2021-01-27 14:16 UTC, Kihyun92 requested changes
관심사 분리 측면에서 많이 고민을 해보며 작업해주신 것 같아요~

각각의 컴포넌트 입장에서 관심사는 무엇인지, 불필요하게 처리된 곳은 없는지 한번 점검해봐도 좋을 것 같아요

2021-01-27 14:16 UTC, Kihyun92 commented on src/Page/Page.jsx
> +function Page() {
Page 컴포넌트의 역할이 무엇인가요?

현재 두가지 관심사가 존재하는 것 같아요.

2021-01-27 14:16 UTC, Kihyun92 commented on src/commons/Form.jsx
> +function Form({ appendTask }) {
아직 작업중이실 수 있지만, Form 또한 여러 관심사가 존재하는 것 같습니다. 기능이 추가될때마다 복잡해질 것 같네요. 어떻게 분리할 수 있을까요?

2021-01-27 14:16 UTC, Kihyun92 commented on src/components/List.jsx
> +      { list.length < 1 ? (
```suggestion
      { list.length === 0 ? (
```
위와 같이 처리하면 어떤가요? 좀 더 단순하게 이해 가능해질 것 같네요.

그리고 list가 넘어오지 않는 경우는 없을까요? 이 경우엔 `undefined`라서 에러가 발생할 것 같아서요 🤔

2021-01-27 14:18 UTC, Kihyun92 commented
> Button Component를 활용을 못했습니다.
> 
> 이유:
> 
> 1. Form에서 사용하는 추가 Button의 타입은 submit, 완료를 하는 버튼의 타입은 button으로 진행할려했지만 default type을 건드리면 안된다는 warning이 나와 중단했습니다. 타입을 둘다 submit으로 작동에는 문제는 없지만 type에 차별을 두고 싶었습니다.
> 2. 추가 버튼의 submit은 다른 prop들을 넘겨줄 필요없는 반면, 완료 버튼에는 id, 완료를시키는 함수를 넘겨주어 Button Component가 독립적이 아니게 변질되는거같아 중단했습니다. 그래도 Button Component를 사용하고 싶다하면 추가버튼에서 필요없는 prop을 일일이 작성해야되는게 또 변수를 발생시킨다고 판단했습니다.
> 
> 예시 )
> 추가 버튼
> 
> ```
> //Form.jsx
> <button type="submit">추가</button>
> ```
> 
> 완료버튼
> 
> ```
> //Task.jsx
>  <button type="button" onClick={() => onClick(id)}>완료</button>
> ```
> 
> Task에 있는 prop을 전부 Button Component에 넘겨준다 하였을 떄 Form.jsx에서도
> 
> ```
> <Button id ={null} onClick={null} ">추가</button>
> ```
> 
> 이렇게 번거로운 작업을 해야되는거 같아서 default value를 주면 해결이 되지만서도,
> 앞서 언급드렸다시피, Button Component가 독립적이 아니게 변질되는거같아보입니다.
> 
> ```
> function Button({ children, id = null, onClick = null }) {
>   return (
>     <button type="button">{children}</button>
>   );
> }
> ```

꼭 컴포넌트를 재활용해서 사용해야만 하는건 아닙니다. 각각의 의도가 있다면 그에 맞게 처리하는 것도 방법입니다! 👍🏼 

다만, 기존의 관점에서 벗어나 하나의 컴포넌트로 처리할 방법이 없을지 다른 시각에서 접근해보는 것도 좋을 것 같습니다~

2021-01-28 09:25 UTC, dodoongtak commented on src/Page/Page.jsx
> +function Page() {
Page라는 네이밍 떄문에 역할 구분을 명확하게 표현하지 못했던거 같아요.

Page는 Todo에필요한 다른 컴포넌트 상위에 있는 컴포넌트 역할입니다. 

App에다 해도 변동은 없게지만, 만약 다른 컴포넌트들도 있을수 있는 경우 하에 이렇게 분리해서 작성해봤습니다. 

제 말대로라면 Page에서 한번 더 내려서 분리하는게 옳다고 생각되네요. 

ToDo 만을 위한 컴포넌트.

2021-01-28 09:29 UTC, dodoongtak commented on src/commons/Form.jsx
> +function Form({ appendTask }) {
현재 Input 컴포넌트를 따로 생성한 이유는 Input 컴포넌트를 Page 컴포넌트(Todo 컴포넌트로 네임 변경) 말고 다른 컴포넌트에서도 활용 할 수 있지 않을까 싶어 이렇게 만들었습니다.

[버튼컴포넌트 재활용에 대한 리뷰](https://github.com/CodeSoom/react-week2-assignment-2/pull/50#issuecomment-768315829) 를 참고해보면 현재 투두리스트를 만드는 과제에서 Input 마저 이렇게 컴포넌트로 쪼갤 필요가 없다고 생각됩니다.

2021-01-28 10:31 UTC, dodoongtak commented on src/components/List.jsx
> +      { list.length < 1 ? (
optional chaining을 활용하여 undefined 케이스까지 validation  할 수 있게 처리하였습니다.

#### key point
- 다른 생각이 들지 않게 컨디션은 최대 단순하게 작성 요망
- length 뿐 아니라 null 또 undefined 일 경우의 exception을 대비

2021-01-28 11:48 UTC, dodoongtak commented on src/components/List.jsx
> +      { list.length < 1 ? (
처리했다 생각했지만 "You may need an additional loader to handle the result of these loaders" 라는 에러가 컴파일 나중에 나와 일단 보류 했습니다. 😭😭😭😭😭😭😭😭😭😭

2021-01-28 11:51 UTC, dodoongtak commented
## 관심사의 분리에 대해 
※ 관심사에 대한 정보가 넷상에서는 너무 상이하여 제가 지금 이해하고있는게 맞는지 커멘트남겨보아요.
- 상태를 관리하는 컴포넌트와 UI만을 담당하는 컴포넌트를 분리하는 과정
- 이 코드는 어디에 더 관심을 두고 있는지 다르게 말하자면 어는 목적을 뚜렷히 가지고 있는지에 분별 및 분리를 진행

예시) 
- 하나의 컴포넌트에서 모든 상태를 관리 할 수 있다.
- 하나의 컴포넌트는 UI 그리기만 담당한다. 
- 하나의 컴포넌트는 다른 컴포넌트를 감싸는 일에 집중한다. 

즉, 관심사란, 어디에 더 중점을 뒀는지에 대한 해당 코드의(컴포넌트/클래스/펑션)의 개성이라 해석했습니다.

2021-01-28 14:02 UTC, Kihyun92 commented
> ## 관심사의 분리에 대해
> ※ 관심사에 대한 정보가 넷상에서는 너무 상이하여 제가 지금 이해하고있는게 맞는지 커멘트남겨보아요.
> 
> * 상태를 관리하는 컴포넌트와 UI만을 담당하는 컴포넌트를 분리하는 과정
> * 이 코드는 어디에 더 관심을 두고 있는지 다르게 말하자면 어는 목적을 뚜렷히 가지고 있는지에 분별 및 분리를 진행
> 
> 예시)
> 
> * 하나의 컴포넌트에서 모든 상태를 관리 할 수 있다.
> * 하나의 컴포넌트는 UI 그리기만 담당한다.
> * 하나의 컴포넌트는 다른 컴포넌트를 감싸는 일에 집중한다.
> 
> 즉, 관심사란, 어디에 더 중점을 뒀는지에 대한 해당 코드의(컴포넌트/클래스/펑션)의 개성이라 해석했습니다.

맞아요 관심사라는게 무엇을 기준으로 볼지에 따라 달라질 수 있어요. ㅎㅎ
형탁님 덕분에 저희 채널에 공유가됐고, 모두에게 관심사가 뭔지 도움이 된 것 같아요. 감사합니다 👍🏼 

보셨겠지만, 아샬님께서도 말씀하셨듯이 단일 책임 원칙 관점에서 각각의 컴포넌트들이 어떤 목적인지, 그렇다면 그 내부에있는 이 변수/함수들은 적절한지 등을 생각해보시는게 이번 주차의 의도입니다 ☺️

2021-01-28 14:09 UTC, Kihyun92 requested changes

2021-01-28 14:09 UTC, Kihyun92 commented on src/Page/Page.jsx
> +function Page() {
좋습니다! 각 컴포넌트의 역할이 분명하되 불필요한 역할(관심사에 맞지않는)을 하는 부분은 개선하면 됩니다.

2021-01-28 14:09 UTC, Kihyun92 commented on src/components/ToDo.jsx
> +  function detachTask(id) {
detach는 읽는 사람에 따라 조금 다양하게 읽힐수 있을 것 같기도 해요.

핸들러 네이밍 컨벤션을 한번 참고해보셔도 좋을 것 같습니다~
- https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-01-29 05:15 UTC, dodoongtak commented
## 과제 2-2 복기 
#### 1. Naming Convention
[Naming Convention 리뷰](https://github.com/CodeSoom/react-week2-assignment-2/pull/50#discussion_r566121395)에 따라 변경을 차근차근 해보니 변경 될 부분이 request 주신 부분 말고도 많더라구요! 
(updateValue라는 함수, props로 전달될때 통일되지 않은 이름, input, list라던지)

props는 on으로
array는 복수명칭으로
function은 handle(주목적)

이렇게 정리하니 한결 이름 하나하나에 어떤 목적을 가지고 작성하시는지 볼 수 있었습니다.

#### 2. 관심사의 분리
[관심사가 무엇인지](https://github.com/CodeSoom/react-week2-assignment-2/pull/50#issuecomment-769073909) 조차 몰라 처음에는 어떤 부분을 고쳐야하는지 해맸지만,  따로 부가설명을 해주셔서, 어떤 목적으로 분리를 해야되는지 알았습니다! 최대한  파트 별로 최대한 서로 어떻게 작동하는지 모르게끔. 

이전 처음 코드와 비교하자면, 유지보수면에서 한군데를 고칠시에 다른곳에도 들여보고 계속 하위 컴포넌트로 추척해서 수정해야 되는 경우가 많았습니다만, 최상위컴포넌트에는 관리, 하위 컴포넌트들은 그리기, 이런 분리를 진행해보니 프로젝트 사이즈가 커질수록 좀 더 편해질거라 예상이 되네요!

2021-01-29 14:05 UTC, Kihyun92 approved these changes
고생하셨습니다. 많은 것을 고민해본 한 주가 아니셨을까 싶어요 ☺️

처음 코드와 지금의 코드가 어떻게 달라졌는지 한번 정리해보셔도 좋을 것 같아요.

강의 풀이 영상을 보시고 아샬님은 어떤 관점을 가지고 투두 리스트를 만들어 가시는지를 눈여겨 보시면 좋겠네요 :)

2021-01-29 14:05 UTC, Kihyun92 commented on src/commons/Button.jsx
> +function Button({ children }) {
음 이 버튼 컴포넌트의 역할은 무엇인가요? 단순히 값을 받아와서 버튼 태그에 노출만 해주고 있는 것 같아요.

이러한 경우엔 컴포넌트로 분리하는게 좋은걸까요?

2021-01-29 14:52 UTC, Kihyun92 commented
회고도 부탁드립니다~ ㅎㅎ

2021-01-31 14:27 UTC, merged