To Do App
CodeSoom/week2-assignment-2 pull request #52
Opened 2021-01-26 11:57 UTC by SangHoonly

현재 한창 코드를 짜는 중입니다!!

2021-01-26 15:18 UTC, SangHoonly commented
성공적으로 동작합니다😁😁😁

2021-01-27 14:26 UTC, Kihyun92 requested changes
와 스타일까지 적용해보셨네요! 좋습니다 💯 

이번 과제의 의도인 관심사 분리 측면에서 리뷰를 남겨봤습니다~

지금은 괜찮지만, 추후 기능들이 추가된다면 여러 관심사를 가진 컴포넌트는 더 복잡해질 수 있을 것 같아요

2021-01-27 14:26 UTC, Kihyun92 commented on src/index.jsx
> +}
https://github.com/CodeSoom/react-week2-assignment-1/pull/62#discussion_r565289893

과제 2-1에서 제 부족한 설명에 보완을 한 부분입니다. 참고 부탁드려요~

2021-01-27 14:26 UTC, Kihyun92 commented on src/Components/Page.jsx
> +    list: [],
무엇을 담는 배열인가요? list라는 변수명은 동료들에게 추가 설명이 필요해질 것 같네요~ ☺️

2021-01-27 14:26 UTC, Kihyun92 commented on src/Components/Page.jsx
> +  const [toDo, setToDo] = useState({
이런 경우엔 `todo`가 맞지 않을까요? 개인적으론 마치 하나의 명사처럼 사용하는 느낌인 것 같아서요 😂

2021-01-27 14:26 UTC, Kihyun92 commented on src/Components/ToDoList.jsx
> +function ToDoList({ text, list, setToDo }) {
이 컴포넌트의 관심사는 무엇인가요? 두가지 이상의 역할이 존재하는 것 같아요. 계산도 하고 화면에 그려주는 역할도 하는 것 같이요.

2021-01-27 14:26 UTC, Kihyun92 commented on src/Components/ToDoList.jsx
> +  );
컴포넌트를 분리해주는건 어떤가요?

2021-01-27 15:30 UTC, SangHoonly commented on src/index.jsx
> +}
참고하겠습니다!

2021-01-27 15:45 UTC, SangHoonly commented on src/Components/Page.jsx
> +    list: [],
넵 알겠습니다!

2021-01-27 17:07 UTC, SangHoonly commented
![스크린샷 2021-01-28 오전 2 05 56](https://user-images.githubusercontent.com/54464320/106026601-614f7b00-610d-11eb-8066-db3f6cdb9c4c.png)

제 실행환경에서는 잘 작동하고 테스트도 다 통과하는데, 깃허브에선 왜 작동이 안되는지 모르겠네요...

2021-01-28 14:40 UTC, Kihyun92 requested changes

2021-01-28 14:40 UTC, Kihyun92 commented on src/Components/AddToDo.jsx
> +  const handleOnChange = (e) => {
`e`도 좋지만, 이번 과제의 제한조건 중에 하나가 `함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.`입니다. 물론 우리에겐 익숙한 용어지만 조금 더 길더라도 명확하게 써주는게 동료들에게도 도움이 될 것 같아요~

2021-01-28 14:40 UTC, Kihyun92 commented on src/Components/App.jsx
> +    <Page todoText={todoText} todoList={todoList} setTodo={setTodo} />
과제 2-1에 커맨트 남겨둔 부분과 비슷한 것 같습니다. 한번 확인부탁드려요 ☺️

- https://github.com/CodeSoom/react-week2-assignment-1/pull/62#pullrequestreview-578344083

2021-01-28 14:40 UTC, Kihyun92 commented on src/Components/Page.css
> +}
![image](https://user-images.githubusercontent.com/35797540/106152667-1131f080-61c1-11eb-93ae-4989832020f5.png)

항상 파일의 끝엔 한줄 공백을 추가해주세요~

2021-01-28 14:40 UTC, Kihyun92 commented on src/Components/ViewTodoList.jsx
> +      </li>
이 반복되는 영역은 컴포넌트로 분리하면 어떨까요?

참고
- https://ko.reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

2021-01-28 14:40 UTC, Kihyun92 commented
> ![스크린샷 2021-01-28 오전 2 05 56](https://user-images.githubusercontent.com/54464320/106026601-614f7b00-610d-11eb-8066-db3f6cdb9c4c.png)
> 
> 제 실행환경에서는 잘 작동하고 테스트도 다 통과하는데, 깃허브에선 왜 작동이 안되는지 모르겠네요...
> 
> 리뷰해 주신 내용들은 다 참고하여 코드를 개선하였습니다!

이 부분은 좀 더 확인해보겠습니다 🤔

2021-01-28 17:31 UTC, SangHoonly commented
![스크린샷 2021-01-29 오전 2 25 53](https://user-images.githubusercontent.com/54464320/106175608-aa6d0100-61d9-11eb-9539-6de8dd94e259.png)

오류 원인이 깃허브 환경에서 번들링 할 때 인것 같습니다... 어떻게 해결해야 할까요...???

2021-01-29 08:32 UTC, SangHoonly commented
리뷰해 주신 부분을 개선하였습니다!!

2021-01-29 08:50 UTC, SangHoonly commented
띠용... 에러를 보니 AddTodo 컴포넌트를 자꾸 못 읽어 번들을 못만든다 그러길래 TodoAdd로 이름만 바꿨더니, 오류가 해결됐습니다... 뭘까요...

2021-01-29 08:54 UTC, SangHoonly commented
다시 AddTodo로 바꿨더니 또 되네요 일시적인 오류였던 것 같습니다.👏👏👏👏

2021-01-29 14:49 UTC, Kihyun92 requested changes

2021-01-29 14:49 UTC, Kihyun92 commented on src/Components/App.jsx
> +    todos.splice(todos.indexOf(event.target.name), 1);
`splice`는 원본 배열을 변경하기 때문에 가급적 사용하지 않는게 좋습니다.

`filter`로 처리할 방법은 없을까요? 각 todo들이 id 값을 가지고 있다면 어떨까요?

2021-01-29 14:49 UTC, Kihyun92 commented on src/Components/App.jsx
> +    });
이렇게만 처리해줘도 될 것 같아요
```suggestion
    setTodo({
      ...todo,
      todoText: event.target.value,
    });
```

2021-01-29 14:49 UTC, Kihyun92 commented on src/Components/App.jsx
> +      deleteButton={handleDeleteButton}
```suggestion
      onTextChange={handleTextChange}
      onAddButton={handleAddButton}
      onDeleteButton={handleDeleteButton}
```
핸들러 네이밍 컨벤션 관한 문서 한번 읽어보시면 좋을 것 같습니다~
- https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-01-29 14:49 UTC, Kihyun92 commented on src/Components/App.jsx
> +  const handleAddButton = () => {
함수명만 보면 버튼을 더해주는 역할 같아요.

`handleAddTodo`와 같은 네이밍은 어떤가요?

2021-01-30 07:46 UTC, SangHoonly commented on src/Components/App.jsx
> +  const handleAddButton = () => {
오 그럴 수 있겠네요..

2021-01-30 07:47 UTC, SangHoonly commented on src/Components/App.jsx
> +    todos.splice(todos.indexOf(event.target.name), 1);
splice를 잘 사용하지 않는군요! filter로 처리 해보겠습니당

2021-01-30 07:48 UTC, SangHoonly commented
리뷰해 주신 내용을 바탕으로 코드를 개선했습니다.

2021-01-30 13:11 UTC, Kihyun92 approved these changes
고생하셨습니다~ 쉽지 않은 과제였는데 잘 해주신 것 같아요 👍🏼 

강의 풀이 영상을 꼭 보시고, 아샬님은 어떤 관점에서 컴포넌트를 분리하시는지 보시면 좋을 것 같습니다 ☺️

그리고 슬랙 채널에 회고를 남겨주세요 :)

2021-01-31 15:01 UTC, merged