Create Todo App
CodeSoom/week2-assignment-2 pull request #54
Opened 2021-01-26 12:05 UTC by yoonhe

2021-01-27 14:42 UTC, yoonhe commented
혹쉬... 과제 1이 완료가 안되면 과제 2는 리뷰 못받는건가요?..

2021-01-27 15:00 UTC, Kihyun92 requested changes
좋습니다~ 관심사의 분리 측면에서 잘 진행해보고 계신 것 같아요 👍🏼 

useState에서 반환되는 상태를 변경할 수 있는 함수에 또 다른 콜백 함수를 넘겨서 처리하신 것 같아요.
개인적으로는 그렇게 처리해본 경험이 없어서 피드백을 드리기 어렵네요. 😅  

상태값의 변경이 필요하다면, 핸들러 함수를 만들고 그 안에서 상태값을 변경하는 함수(useState에서 리턴하는)를 통해 상태 변경을 하는건 어떨까요?

2021-01-27 15:00 UTC, Kihyun92 commented on src/App.jsx
> +    // eslint-disable-next-line no-shadow
해당 룰이 필요한 이유가 무엇일까요? 🤔

2021-01-27 15:00 UTC, Kihyun92 commented on src/App.jsx
> +  function handleDeleteTodo(deleteTodoId) {
`deleteTodoId`보다 단순히 `id`라고만 하는건 어떤가요?

함수명을 통해 충분히 어떤 값인지 유추할 수 있을 것 같아요~

2021-01-27 15:00 UTC, Kihyun92 commented on src/TodoForm.jsx
> +function TodoForm({ handleAddTodo }) {
아직 작업중이실 수 있지만, Form 컴포넌트에 여러 관심사가 존재하는 것 같습니다.

기능이 추가될때마다 복잡해질 것 같네요. 어떻게 분리할 수 있을까요?

2021-01-27 15:00 UTC, Kihyun92 commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
todos에는 어떤 값이 들어가나요? 아래 handleAddTodo를 보니 객체와 같이 값이 들어갈 것 같네요 ㅎㅎ

이럴땐 useState내에서 초기값을 설정 해주는 것도 좋을 것 같아요~

2021-01-27 15:00 UTC, Kihyun92 commented on src/App.jsx
> +  const nextId = useRef(todos.length + 1);
id 관리를 따로 하고있네요, 하나의 상태로 처리하면 어떻게 할 수 있을까요? 상태 타입이 객체라면 어떤가요?

2021-01-28 08:42 UTC, yoonhe commented on src/App.jsx
> +  function handleDeleteTodo(deleteTodoId) {
변경하였습니다!

```js
function handleDeleteTodo(id) {
    setTodos(todos.filter((todo) => todo.id !== id));
  }
```

2021-01-28 08:43 UTC, yoonhe commented on src/App.jsx
> +    // eslint-disable-next-line no-shadow
> 상태값의 변경이 필요하다면, 핸들러 함수를 만들고 그 안에서 상태값을 변경하는 함수(useState에서 리턴하는)를 통해 상태 변경을 하는건 어떨까요? 

말씀해주신 방법으로 해결하여 룰 삭제했습니다!

```js
setTodos([...todos, newTodo]);
```

2021-01-28 10:19 UTC, yoonhe commented on src/TodoForm.jsx
> +function TodoForm({ handleAddTodo }) {
Form 컴포넌트에서는 `input` state를 관리해주도록  변경하는 함수만 관심사로 가지게하고,
`AddInput` 컴포넌트를 만들어서 `props`를 받아 그리는것에만 집중하도록 해주었습니다. 

```js
<form onSubmit={onSubmit}>
      <AddInput value={value} handleInput={handleInput} />
    </form>
```

2021-01-28 10:28 UTC, yoonhe commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
최초에는 `todo`를 입력하지 않았기 떄문에 `todos`가 빈배열이어야 하는데 초기값을 어떻게 설정해줘야 하나요?..

2021-01-28 10:29 UTC, yoonhe commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
혹시  아래와 같이 설정하라는 말씀이셨을까요?
```js
const initialState = [];
const [todos, setTodos] = useState(initialState);
```

2021-01-28 10:42 UTC, yoonhe commented on src/App.jsx
> +  const nextId = useRef(todos.length + 1);
`newTodo`를 만들어줄때 계산하도록 해주었습니다.

```js
const [todos, setTodos] = useState(initialState);

  function handleAddTodo(todo) {
    const newTodo = {
      id: todos.length + 1,
      content: todo,
    };

    setTodos([...todos, newTodo]);
  }
```

2021-01-28 14:44 UTC, Kihyun92 commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
배열안에 어떤 정보가 담기나요?

```javascript
[
  {
    id: 0,
    content: '',
  }
]
```

`newTodo`를 참고했는데 이런 형식으로 담기지 않나요?

2021-01-28 14:48 UTC, Kihyun92 requested changes

2021-01-28 14:48 UTC, Kihyun92 commented on src/TodoForm.jsx
> +  function handleInput(e) {
`e`도 좋지만, 이번 과제의 제한조건 중에 하나가 `함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.`입니다. 물론 우리에겐 익숙한 용어지만 조금 더 길더라도 명확하게 써주는게 동료들에게도 도움이 될 것 같아요~

2021-01-28 14:48 UTC, Kihyun92 commented on src/TodoListItem.jsx
> +function TodoListItem({ todo, handleDeleteTodo }) {
한번 더 구조분해할당을 해줄 수 있겠네요 :)
```suggestion
function TodoListItem({ todo: { id, content }, handleDeleteTodo }) {
```

2021-01-29 02:12 UTC, yoonhe commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
네네 그런데 말씀해주신대로 초기값을 설정하면 아무것도 들어가지 않은 todo가 렌더링되는게 아닌가요??
![image](https://user-images.githubusercontent.com/53102889/106222456-e7111a80-6222-11eb-9ed8-163970bca724.png)

```
const initialState = [{
    id: 0,
    content: '',
  }];
  const [todos, setTodos] = useState(initialState);
```

2021-01-29 09:03 UTC, yoonhe commented
질문이 있습니다!

`TodoForm` 컴포넌트에서 `input`의 `value`를 관리해주기 위해 사용하는 상태와 상태를 관리하는 함수를 `TodoForm` 컴포넌트 안에서 관리하는게 맞는지 `App` 컴포넌트에서 관리해줘야하는게 맞는지가 궁금합니다.

```js
function TodoForm({ handleAddTodo }) {
  const [value, setValue] = useState('');
}
```

2021-01-29 09:07 UTC, yoonhe commented on src/TodoListItem.jsx
> +function TodoListItem({ todo, handleDeleteTodo }) {
이부분에서 질문이 있습니다.

`TodoList`에서 `todo`를 넘겨줄때 지금처럼 `todo` 객체를 통으로 `TodoListItem` 컴포넌트에 넘기는 방법과,
아래처럼 `TodoListItem`에서 필요한 항목들만 전달하는 방법중 어느 방법이 더 효율적인? 좋은? 방법인가요?
```js
<TodoListItem
          key={todo.id}
          id={todo.id}
          content={todo.content}
          handleDeleteTodo={handleDeleteTodo}
        />
```

2021-01-29 10:30 UTC, yoonhe commented
기현님 , 제가 다른분 코드리뷰보고 브랜치를 하나 새로 따서 템플릿 기능을 추가해보았습니다
혹시 괜찮으시다면 코드리뷰 요청드려도 될까요 ㅎㅎㅎㅎ

템플릿 기능 추가한 코드 풀리퀘 : https://github.com/CodeSoom/react-week2-assignment-2/pull/60#issue-563863172

아래의 리뷰에서 보았습니다.
https://github.com/CodeSoom/react-week2-assignment-2/pull/26#discussion_r492886915
![image](https://user-images.githubusercontent.com/53102889/106263934-6248ef80-6268-11eb-83ca-880cfdb04226.png)

2021-01-29 14:11 UTC, Kihyun92 commented on src/App.jsx
> +  const [todos, setTodos] = useState([]);
앗 아니에요 제가 잘못 리뷰를 남긴 것 같네요.. ㅠㅠ

지금 처리하신 부분이 맞습니다. 혼동을 드렸네요 🙏

2021-01-29 14:13 UTC, Kihyun92 commented on src/TodoListItem.jsx
> +function TodoListItem({ todo, handleDeleteTodo }) {
지금과 같이 객체 내에 프로퍼티가 몇 없을 경우에는 어떤 방법으로 해도 상관은 없을 것 같아요~ 

대신 객체 내에 프로퍼티가 많아지면 어떨까요? 이 경우엔 하나씩 맵핑해주는 것보다 객체를 넘겨서 그 내부에서 처리하는 것도 방법일 것 같네요

2021-01-29 14:20 UTC, Kihyun92 commented
> 질문이 있습니다!
> 
> `TodoForm` 컴포넌트에서 `input`의 `value`를 관리해주기 위해 사용하는 상태와 상태를 관리하는 함수를 `TodoForm` 컴포넌트 안에서 관리하는게 맞는지 `App` 컴포넌트에서 관리해줘야하는게 맞는지가 궁금합니다.
> 
> ```js
> function TodoForm({ handleAddTodo }) {
>   const [value, setValue] = useState('');
> }
> ```

각 방식의 장단점이 무엇일까요? 🤔

그리고 관심사를 기준으로 봤을때 어떤 방식이 적합한가요?

2021-01-29 14:37 UTC, Kihyun92 commented
> 기현님 , 제가 다른분 코드리뷰보고 템플릿 기능을 추가해보았습니다
> 혹시 괜찮으시다면 코드리뷰 요청드려도 될까요 ㅎㅎㅎㅎ

오 좋은데요? ㅎㅎ 새롱누 기능 추가에 고민해보신 부분 좋습니다 💯 

다만 이 템플릿과 선택된 템플릿에 대한 상태를 App에서도 아는게 좋을지, 아니면 템플릿 선택시에 인풋에 값을 채워주고만 있으므로 Form 컴포넌트에서 관리하는게 좋을지.

이 부분은 고민이 되네요 ㅎㅎ 해은님 생각은 어떤가요?

2021-01-29 14:58 UTC, Kihyun92 commented
질문을 많이해주셔서 너무 좋네요 💯

가능하면 슬랙 채널에 남겨주시면 다른 분들에게 더 도움이 되고 본인에게도 많은 도움이 될 것 같아요 😊

2021-01-30 05:45 UTC, yoonhe commented
> 다만 이 템플릿과 선택된 템플릿에 대한 상태를 App에서도 아는게 좋을지, 아니면 템플릿 선택시에 인풋에 값을 채워주고만 있으므로 Form 컴포넌트에서 관리하는게 좋을지.
이 부분은 고민이 되네요 ㅎㅎ 해은님 생각은 어떤가요?

음... 기현님 말씀대로 인풋에 값을 채워주는 역할이니까 `Form` 컴포넌트에서 상태를 관리해줘도 될거같아요.. 그런데 사실 `App`과 `Form` 중 어디에서 관리하는게 맞는건지는 잘 모르겠습니다 ㅜㅜ

2021-01-30 05:50 UTC, yoonhe commented
> 각 방식의 장단점이 무엇일까요? 🤔
그리고 관심사를 기준으로 봤을때 어떤 방식이 적합한가요?

App 컴포넌트에서 input의 상태를 관리한다면 `Form` 컴포넌트를 하나 만들때마다 App 컴포넌트에 해당 컴포넌트에 해당되는 상태를 추가해줘야 해서 `Form` 컴포넌트가 많이 생길경우에는 `App` 컴포넌트가 복잡해질것 같아요.

`Form` 컴포넌트에서 `input`의 상태를 관리하게 되면 `Form` 컴포넌트가 여러개 추가되도 `App`의 관심사가 아니므로 `App`에는 변화가 없고 각각의 `Form` 컴포넌트 안에서 `input`의 상태를 관리하게 되니... 여러개의 컴포넌트가 추가될 경우에는 `Form` 컴포넌트에서 관리해주는게 더 좋을거 같다는 생각이 듭니다!

제가 알맞게 이해한게 맞을까요? ㅎㅎㅎ...

2021-01-30 13:30 UTC, Kihyun92 commented
> > 다만 이 템플릿과 선택된 템플릿에 대한 상태를 App에서도 아는게 좋을지, 아니면 템플릿 선택시에 인풋에 값을 채워주고만 있으므로 Form 컴포넌트에서 관리하는게 좋을지.
> > 이 부분은 고민이 되네요 ㅎㅎ 해은님 생각은 어떤가요?
> 
> 음... 기현님 말씀대로 `Input` 이 채워지는건 `Form` 컴포넌트의 관심사니까 `Form`에서 상태를 관리해줘도 될거같아요.
> 
> 질문이 2가지가 생각나는데요.
> 
> 1. 사실.. `Form`과 `App` 둘 중 어디에서 관리하는게 맞는건지 잘 모르겠는데 기현님 생각은 어떠신지 궁금합니다!
> 2. `App` 컴포넌트에서만 상태값을 가지고 관리할 수 있다고 생각했는데 상황에 따라 관심사를 분리할 수 있다면 `App `이 아닌 다른 컴포넌트가 상태를 가져도 되는건가요?

1. 음 추후 기능이 확장된다면 더 상위로 옮겨질 수 있겠지만 일단은 Input 외에 다른 곳에 영향을 주지 않으니 `Form`에서 관리할 것 같아요 ㅎㅎ

2. 반드시 App에서만 상태를 관리해야하는 건 아닙니다. 상황에 맞게 해야할 것 같아요. 이번 과제와 같이 관리할 상태가 많지 않은 프로젝트의 경우엔 상위 컴포넌트인 App에서 관리했지만, 관리할 상태가 하나 둘 추가될 때마다 굉장히 복잡해 질 거에요. 이 경우엔 `redux`, `mobx` 와 같은 상태 관리 라이브러리를 사용하는게 좋겠죠.

이번 과제를 하면서 App 컴포넌트에서 상태관리를 해보고, 더 나아가 상태 관리 라이브러리 등의 필요성 등을 느껴보신 것 같아 좋네요 👍🏼

2021-01-30 14:05 UTC, Kihyun92 commented
> > 각 방식의 장단점이 무엇일까요? 🤔
> > 그리고 관심사를 기준으로 봤을때 어떤 방식이 적합한가요?
> 
> App 컴포넌트에서 input의 상태를 관리한다면 `Form` 컴포넌트를 하나 만들때마다 App 컴포넌트에 새로 생성된 `Form` 컴포넌트에 해당되는 상태를 추가해줘야 해서 `Form` 컴포넌트가 많이 생길경우에는 `App` 컴포넌트가 복잡해질것 같아요.
> 
> `Form` 컴포넌트에서 `input`의 상태를 관리하게 되면 `Form` 컴포넌트가 여러개 추가되도 `App`의 관심사가 아니므로 `App`에는 변화가 없고 각각의 `Form` 컴포넌트 안에서 `input`의 상태를 관리하게 되니... 여러개의 컴포넌트가 추가될 경우에는 `Form` 컴포넌트에서 관리해주는게 더 좋을거 같다는 생각이 듭니다!
> 
> 그런데 생각해보니... `Form`에서 스테이트를 관리하게 되면 단순히 부모컴포넌트에서 `props`로 무엇인가를 받아서 그리기만 하는것이 아니라 상태도 관리하게 되니 재사용성이 떨어지게 되는것일까 하는 생각이 듭니다.. 🤔
> 
> 제가 장단점을 잘 얘기한게 맞을까요?

ㅎㅎ 좋습니다. Form 컴포넌트가 더 추가될 경우까지 고려해보셨네요. 👍🏼 

일단 지금 구조에서는 무언가 관리할 상태가 추가될수록 점점 App이 복잡해 질거에요 ㅎㅎ 이 경우엔 상태관리 라이브러리를 통해 상태를 관리하는 것도 방법이 될 것 같네요.

그런데 일단 `Form` 컴포넌트가 추가될 경우가 있을까 생각이 들어요. 단순히 `input`들이 추가된다면 하나의 `form` 내에서 관리할 것 같아요.실제로 저희 팀에서는 [React hook form](https://react-hook-form.com/)으로 Form 내부에 대한 관리를 하고 있습니다.

2021-01-30 14:07 UTC, Kihyun92 approved these changes
고생하셨습니다~ 쉽지 않은 과제였는데 잘 해주신 것 같아요.

정말 많은 고민을 해보셨을 것 같은데, 과제 풀이 영상을 보시면서 아샬님은 어떤 방식으로 접근하시는지 확인해보시면 좋겠네요.

슬랙 채널에 회고 남겨주시면 머지하겠습니다~ 😁

2021-01-31 14:55 UTC, merged