Todo list
CodeSoom/week2-assignment-2 pull request #7
Opened 2020-06-10 01:49 UTC by newoo

안녕하세요.

리뷰 요청합니다.

2020-06-10 13:40 UTC, wholemann requested changes
전체적으로 준수하게 잘해주셨네요.
몇 가지 생각해볼 부분에 대해서 comment 남겼습니다.
comment에 대해 질문 있으시면 언제든 DM 주세요:)

다시 PR 기다리겠습니다.

2020-06-10 13:40 UTC, wholemann commented on src/App.jsx
> +    todos: [],
상태 이름이 명확하고 좋네요.

2020-06-10 13:40 UTC, wholemann commented on src/App.jsx
> +    if (value !== '') {
만약 공백 제거를 해주고 싶다면 trim() 에 대해서 알아보세요:)

2020-06-10 13:40 UTC, wholemann commented on src/App.jsx
> +  function handleAddClick(value) {
handleClickXXX이 더 적절할 듯 싶네요.

어떤 이벤트에 대한 핸들링인지를 좀 더 먼저 표현하면 좋겠습니다.

2020-06-10 13:40 UTC, wholemann commented on src/App.jsx
> +      todos: todos.filter((_, index) => index !== value),
value가 어떤 값인지 예측하기가 힘드네요.
게다가 배열 index와 value의 일치 여부로 삭제를 하고 있어서 더더욱 의미를 알기가 어렵습니다.

2020-06-10 13:40 UTC, wholemann commented on src/pages/Todopage.jsx
> +  inputText, todos, addClick, completeClick, handleChange,
onClickAddTodo, onClickComplete 등으로 표현하면 어떤 점이 좋을까요?

2020-06-10 13:40 UTC, wholemann commented on src/components/Todolist.jsx
> +          <button type="button" onClick={() => completeClick(index)}>완료</button>
지금은 index로 해당 todo를 구분하고 있습니다. 여기서 index는 계속 변하는 값입니다.
만약 완료했다가 취소하는 경우가 생긴다면 index로 todo를 구분하는 건 어떤 문제를 발생시킬 수 있을까요?

2020-06-11 02:35 UTC, newoo commented on src/components/Todolist.jsx
> +          <button type="button" onClick={() => completeClick(index)}>완료</button>
완료했다가 취소하는 경우 원치 않는 todo가 복귀될 수 있을 것 같아요.

예를 들어 index가 2인 todo를 완료처리하면 index가 3이었던 todo의 인덱스가 2로 변경되므로, 잘못된 복구가 일어날 가능성이 존재합니다.

index로 처리한 이유는 동일한 내용의 todo가 있을 가능성을 대비한 경우인데... 생각해보니 내용과 인덱스를 모두 구분하는 것이 더 안전하다고 생각되네요.

2020-06-11 06:27 UTC, newoo commented on src/components/Todolist.jsx
> +          <button type="button" onClick={() => completeClick(index)}>완료</button>
좀 더 생각해보니 identifier 값을 넣어주는 게 가장 좋을 것 같네요

2020-06-11 06:48 UTC, newoo commented
리뷰 재요청합니다~

2020-06-12 11:15 UTC, wholemann requested changes

2020-06-12 11:15 UTC, wholemann commented on src/App.jsx
> +  function handleClickAddTodo(todoText, todoID) {
굳이 nextTodoID를 todoID로 받을 필요는 없어보여요.
이미 위에 상태에서 nextTodoID를 가져다 쓰기 때문이죠.

2020-06-12 11:15 UTC, wholemann commented on src/App.jsx
> +      nextTodoID,
실제로 조작해야 되는 상태를 제외하면 ...state는 어떨까요?

현재는 상태를 갱신하는 게 여럿인 것으로 보입니다.

2020-06-12 11:15 UTC, wholemann commented on src/App.jsx
> +      nextTodoID,
여기도 마찬가지 같습니다.

2020-06-12 11:15 UTC, wholemann commented on src/App.jsx
> +    <Todopage
Page는 대문자가 좋겠네요.

2020-06-12 11:15 UTC, wholemann commented on src/components/Todoinput.jsx
> +function Todoinput({
I도 대문자요!

2020-06-12 11:15 UTC, wholemann commented on src/components/Todoinput.jsx
> +  inputText, nextTodoID, onClickAddTodo, onChangeInputText,
Camel Case일 땐 ID도 Id로 표현하는 게 좋겠어요.

2020-06-12 11:15 UTC, wholemann commented on src/components/Todolist.jsx
> +function Todolist({ todos, onClickCompleteTodo }) {
List도 대문자요!

2020-06-12 11:15 UTC, wholemann commented on src/components/Todolist.jsx
> +          <button type="button" onClick={() => onClickCompleteTodo(todo)}>완료</button>
onClickCompleteTodo에 todo 자체를 전달하기보단 식별자를 전달하는 게 표현력이 더 좋아보입니다.

2020-06-13 18:02 UTC, newoo commented
재리뷰 요청합니다~

2020-06-14 02:35 UTC, wholemann requested changes
한 가지만 더 수정하시면 좋을 것 같네요.

Item 복잡도가 높아진다면 TodoList의 복잡도가 급격히 올라갈 겁니다.

다음 PR 기다릴게요ㅎㅎ

2020-06-14 02:35 UTC, wholemann commented on src/components/Todolist.jsx
>          </p>
이 부분은 Item 컴포넌트로 분리하는 건 어떨까요?

component 재사용 측면에서 분리 단위를 잘 생각해볼 필요가 있습니다.

2020-06-14 03:18 UTC, newoo commented
피드백 반영했습니다.
리뷰 부탁드려요~

2020-06-14 07:22 UTC, wholemann approved these changes
고생 많으셨습니다ㅎㅎ 거의 완벽하네요. 아주 사소한 부분만 comment 남겨놨으니
다음 과제부턴 조금만 주의하시면 될 듯 합니다ㅎㅎ.

Merge하겠습니다! 아샬님 풀이 강의를 참고해주시고 질문은 언제든 DM 주세요:)

2020-06-14 07:22 UTC, wholemann commented on src/pages/TodoPage.jsx
> +function Todopage({
TodoPage가 좋겠네요.

2020-06-14 07:22 UTC, wholemann commented on src/components/TodoList.jsx
> +function Todolist({ todos, onClickCompleteTodo }) {
TodoList가 좋겠네요ㅎㅎ

2020-06-14 07:22 UTC, wholemann commented on src/components/TodoInput.jsx
> +function Todoinput({
TodoInput이 좋겠습니다.

2020-06-14 07:22 UTC, merged