2주차 2번째 과제
CodeSoom/week2-assignment-2 pull request #70
Opened 2021-05-10 02:54 UTC by yujong-lee

`eslint`와 `인수테스트`를 모두 통과함을 확인했습니다.
이제부터 리펙토링을 통해 가독성 등을 개선하려합니다.

2021-05-10 05:41 UTC, yujong-lee commented
조금 고민이 되었던 부분이 상태를 선언하는 부분이었습니다.

```javascript
// 1
const [userInput, setUserInput] = useState('');
const [tasks, setTasks] = useState([]);


// 2
const [userInput, setUserInput] = useState({text: ''});
const [tasks, setTasks] = useState({tasks: []});

// 3
const [state, setState] = useState({text: '', tasks: []});
```

이 세가지 중 생각을 하다가 2번은 전혀 불필요하고 1번의 하위호환이라고 느꼈구요. `To-do`에서 `text`와 `tasks`가 같이 사용되는 상태니까 같은 객체로 묶는 3번도 나쁘진 않아보였습니다. 그런데  어짜피 저 두개 외에는 다른 상태는 없으니까 굳이 저렇게 하는것보다는 1번처럼 간결하게 하는게 나은 것 같아서 1번으로 했는데 혹시 이런걸 결정할 때 어떤 생각과 기준으로 정하면 될까요?

2021-05-10 16:04 UTC, Kihyun92 requested changes
빠른 PR 좋네요 👍🏼 👍🏼 

이번 과제도 2-1과 마찬가지로 Todo 컴포넌트가 여러 관심사를 가지고 있는 것 같아요. 

상태를 관리 하는 부분과 상태를 그려주는 부분을 분리해 보는건 어떨까요? 🤔

2021-05-10 16:04 UTC, Kihyun92 commented on src/index.jsx
> +import App from './App';
외부/내부 모듈 간에 공백을 통해 구분해주세요~

2021-05-10 16:04 UTC, Kihyun92 commented on src/Todo.jsx
> +    const newContent = userInput;
userInput을 바로 사용하지 않고 재할당해주는 이유가 있을까요?

2021-05-10 16:04 UTC, Kihyun92 commented on src/Todo.jsx
> +    document.getElementById('inputBox').value = '';
DOM 객체를 직접 조작하지 않고 처리하는 방법은 없을까요?

2021-05-10 16:04 UTC, Kihyun92 commented on src/Todo.jsx
> +      <Input updater={updatInputText} submitter={addTask} />
```suggestion
      <Input onChangeInput={handleChangeInput} onSubmit={handleAddTask} />
```

위 예시와 같은 네이밍 컨벤션은 어떤가요? 실제 일을 처리하는 관점과 사용하는 입장에서 바라볼 때의 의도를 각각 드러내줄 수 있을 것 같아요.

참고:
- https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-05-10 16:04 UTC, Kihyun92 commented on src/Todo.jsx
> +  const [tasks, setTasks] = useState([]);
상태 관리하는 부분 관련해서 고민을 해보신 것 같아요 😁

이 경우에는 상태관리를 하나의 객체로 해도 좋을 것 같네요.

개인적으로는 상태 간에 추상화를 할 수 있을 만큼 연관이 있고, 관리할 상태들이 많지 않은 경우에 하나의 객체로 상태관리를 하는 것 같아요~

2021-05-10 16:04 UTC, Kihyun92 commented on src/List.jsx
> +    );
```suggestion
  const isEmpty = (array) => (R.isEmpty(array));
  
  if (isEmpty) {
    return <p>할 일이 없어요!</p>;
  }
  
  return (
    <ol>
      {items.map((item) => (
        <Item
          content={item.content}
          onClick={() => onClick(item.id)}
        />
      ))}
    </ol>
  );
```
위와 같이 `Guard Clauses`를 사용하면 할 일이 없는 경우에 대한 의도를 드러낼 수 있을 것 같아요~

참고:
- https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2021-05-11 00:43 UTC, yujong-lee commented on src/index.jsx
> +import App from './App';
`17d36a1`으로 수정했습니다.

2021-05-11 00:45 UTC, yujonglee commented on src/List.jsx
> +    );
`Guard Clauses`를 사용하는 것이 훨씬 읽기 좋네요. `a2813cb`에서 수정했습니다.

그런데 여기에서
```javascript
  const isEmpty = (array) => (R.isEmpty(array));
  
  if (isEmpty) {
    return <p>할 일이 없어요!</p>;
  }
```
위 처럼 하는 것이 다음보다 좋은 이유가 무엇인가요?

```javascript
  if (R.isEmpty(array)) {
    return <p>할 일이 없어요!</p>;
  }
```

2021-05-11 00:49 UTC, yujong-lee commented on src/Todo.jsx
> +    const newContent = userInput;
`newId`와 라임을 맞추려고(?) 했던 것 같은데 불필요한 변수가 맞는 것 같습니다. `8cc13eb`로 수정했습니다.

2021-05-11 01:01 UTC, yujonglee commented on src/Todo.jsx
> +      <Input updater={updatInputText} submitter={addTask} />
굉장히 좋은 말씀입니다. `3ffc815` `16055c1`으로 수정했습니다.

```jsx
<p>
  <h1>To-do</h1>
  <Input onChangeInput={handleChangeInput} onSubmit={handleAddTask} />
  <List items={tasks} onClick={handleDeleteTask} />
</p>
```
이것만 봐도 무엇을 하는지를 명확하게 읽히네요.

2021-05-11 01:29 UTC, yujong-lee commented on src/Todo.jsx
> +  const [tasks, setTasks] = useState([]);
조언 감사합니다. `f5f8bef`로 수정했습니다.

2021-05-11 01:43 UTC, yujong-lee commented on src/Todo.jsx
> +    document.getElementById('inputBox').value = '';
`8c857e2`로 수정했습니다. 이렇게 하는 것이 맞나요?

2021-05-11 02:06 UTC, yujong-lee commented
> 상태를 관리 하는 부분과 상태를 그려주는 부분을 분리해 보는건 어떨까요? 🤔

`Container 컴포넌트`와 `Presentational 컴포넌트`를 도입하여 분리했습니다.

2021-05-11 14:58 UTC, Kihyun92 commented on src/List.jsx
> +    );
앗 이 부분은 람다를 제대로 파악하지 못한 상태에서 예시를 작성하다보니 저렇게 작성한것 같아요 😅

아래에 말씀하신대로 처리하는게 좋을 것 같습니다!

2021-05-11 15:18 UTC, Kihyun92 requested changes
리뷰 드린것보다 더 잘 반영해주시는 것 같아요 👍🏼 

Container/Presentation 구조로 분리하신건 좋지만, 아직 사용할 때가 아닌 것 같습니다.

App 컴포넌트에서 전반적인 상태를 관리해도 될 것 같군요.

2021-05-11 15:18 UTC, Kihyun92 commented on src/List.jsx
> +      ))}
```suggestion
      {items.map(({ content, id }) => (
        <Item
          content={content}
          onClick={() => onClick(id)}
        />
      ))}
```
구조분해할당을 적용해도 좋을 것 같네요 :)

추가로 key 값 추가가 필요해보입니다!

참고: [https://reactjs.org/docs/lists-and-keys.html](https://reactjs.org/docs/lists-and-keys.html)

2021-05-11 15:18 UTC, Kihyun92 commented on src/TodoContainer.jsx
> +  }
`event`는 UI 컴포넌트에서 관리해야 하는 객체입니다. `handleChangeInput`은 상태를 변경해주는 함수이기 때문에 UI 레이어와는 전혀 상관이 없어야 합니다.

2021-05-12 01:09 UTC, yujonglee commented on src/List.jsx
> +      ))}
`b38d1df`, `bbe7315`에서 수정했습니다.

2021-05-12 01:12 UTC, yujonglee commented on src/TodoContainer.jsx
> +  }
생각지도 못한 포인트입니다. 감사합니다. ㅎㅎ 
`db2d293`로 수정했습니다.

2021-05-12 16:58 UTC, Kihyun92 requested changes

2021-05-12 16:58 UTC, Kihyun92 commented on src/App.jsx
> +    userInput: '',
App 컴포넌트의 입장에서 이 값이 유저의 input으로 인한 값인지 알 필요가 있을까요?(적고보니 물론 유저의 인풋이긴 하겠네요 ㅎㅎ;) 조금 단순하게 `task`는 어떨까요?

2021-05-12 16:58 UTC, Kihyun92 commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
```suggestion
      onChangeInput={handleChangeInput}
      onAddTask={handleAddTask}
      onDeleteTask={handleDeleteTask}
```
실제로 `event.target.value` 를 넘기는 건 해당 컴포넌트에 위임하는건 어떨까요? App 컴포넌트 관점에선 `handleChangeInput` 함수는 단순히 값을 받아서 상태값을 업데이트해줄 뿐인거죠.

추가로 받는 쪽에서는 on으로 받도록 처리해주세요.

2021-05-13 01:45 UTC, yujong-lee commented on src/App.jsx
> +    userInput: '',
관심사의 분리의 측면에서 생각해보면 `App.jsx`는 현재 `task`랑 저장된 `tasks`, 그리고 `task`를 추가, 삭제하는 법만 알고 그걸 잘 보여주는 역할은 `Todo`로 위임하는 형태가 맞겠군요. `d53190d`로 수정했습니다.



그런데 한 가지 궁금한 점이 있는데, 이렇게 `task`와 `tasks`를 같이 쓰는 것은 일반적으로 괜찮다고 여겨지나요?
뭔가 헷갈릴 수도 있을 것 같아서요. 저는 괜찮은데 누군가 `저렇게 쓰면 헷갈릴 수 있으니 바꿔라`라고 하면 할말이 없을 것 같네요.

아래와 같이 `map`에서 쓰는 것은 헷갈릴 여지가 없는 것 같고 오히려 이해하기 쉬울 것 같아서 그동안  많이 써왔는데,  
```js
items.map((item) => { something })
```
이런 건 약간 걸리네요.
```js
setState({
  task: '',
  tasks: [...tasks, { id: getNewId(tasks), content: task }],
});
```

2021-05-13 01:49 UTC, yujong-lee commented on src/App.jsx
> +    userInput: '',
쓰고 나서 보니까 그냥 단순히 팀 내에서의 컨벤션에 따라서 다르지 딱 정해진 건 없을 것 같기도 하네요. ㅎㅎ

2021-05-13 02:15 UTC, yujong-lee commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
> 실제로 event.target.value 를 넘기는 건 해당 컴포넌트에 위임하는건 어떨까요?
좋은 말씀입니다.  `6e546af`으로 수정했습니다.

2021-05-13 02:28 UTC, yujong-lee commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
> 추가로 받는 쪽에서는 on으로 받도록 처리해주세요.

이게 조금 헷갈리는 부분인데, 저도 
```js
handleChangeInput={(e) => handleChangeInput(e.target.value)}
handleAddTask={handleAddTask}
handleDeleteTask={handleDeleteTask}
```
이렇게 둘다 `handle`로 되는게 어색했습니다.

가장 바람직한 형태는 아래와 같겠지요.

```js
// App.jsx
  return (
    <Todo
      userInput={task}
      tasks={tasks}
      onChangeInput={handleChangeInput}
      onAddTask={handleAddTask}
      onDeleteTask={handleDeleteTask}
    />
  );

// Todo.jsx
  return (
    <p>
      <h1>To-do</h1>
      <Input
        value={userInput}
        onChangeInput={handleChangeInput}
        onSubmit={handleAddTask}
      />
      <List
        items={tasks}
        onClick={handleDeleteTask}
      />
    </p>
  );
```

위와 같이 작성하는 것이 적절한 이유는 아래와 같이 이해하고 있습니다.


`App`은 상태만 관리합니다. `App`은 `task`, `tasks`, 그리고 이들을 수정하는 함수들 밖에 모릅니다. 이것들을 가지고 `Todo`를 그리는건 `Todo컴포넌트`의 일입니다.

`Todo컴포넌트`는 실제 `task`를 가지고 일을 하는 곳이니, 받을 때 `onChangeInput`, `onAddTask`, `onDeleteTask`와 같이 `구체적`으로 받습니다.

`이와 다르게` `Input`, `List 컴포넌트`는 `Todo`가 뭐하는 것인지는 모르고 받은 함수를 이벤트의 발생에 따라 실행시켜줄 뿐이므로 `onChangeInput`, `onSubmit`, `onClick`와 같이 받습니다.


그런데 이렇게 작성하려면 중간에 `Todo.jsx`에서 다음과 같이 받아야 합니다. 이름을 바꿔줘야하니까요.
```js
export default function Todo({
  userInput,
  tasks,
  onChangeInput: handleChangeInput,
  onAddTask: handleAddTask,
  onDeleteTask: handleDeleteTask,
}) 
```
이렇게 하는 것이 맞나요? 
일단은 이렇게 하는 방법밖에 없는 것 같아 `77a7c96`로 수정했습니다.

2021-05-13 14:35 UTC, Kihyun92 commented on src/App.jsx
> +    userInput: '',
맞아요. 사실 팀 내의 컨벤션이 중요하죠. 😊 

하지만 헷갈리더라도 대체할 적절한 용어가 없는건 사실입니다. 만약 더 의도가 잘 드러나고 읽기 쉬운 네이밍이 있다면 그걸 선택하는게 맞을 것 같습니다. :)

2021-05-13 14:51 UTC, Kihyun92 commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
제가 설명이 조금 부족했던 것 같아요. 자식 컴포넌트에선 받은 함수를 그대로 사용하거나 전달하기 때문에 `handle` prefix를 붙이지 않고 `on`을 그대로 사용하는게 맞을 것 같아요~

```javascript
export default function Todo({
  userInput,
  tasks,
  onChangeInput,
  onAddTask,
  onDeleteTask
}) 

```

2021-05-13 14:55 UTC, Kihyun92 requested changes

2021-05-13 14:55 UTC, Kihyun92 commented on src/List.jsx
> +export default function List({ items, onClick }) {
`List, Item`이라는 컴포넌트 명도 직관적으로 이해되지만, 보다 해당 컴포넌트의 역할을 드러내줄 수 있는 네이밍은 어떨까요?

2021-05-14 01:11 UTC, yujong-lee commented on src/List.jsx
> +export default function List({ items, onClick }) {
`2e7ebaf`로 수정했습니다.

2021-05-14 01:14 UTC, yujong-lee commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
음 그런데 `on~`, `handle~`로 이름을 짓는 이유가 그 컴포넌트를 사용하는 것만 보고 뭐하는지 알려고 하는 것 아닌가요?
`App.jsx`에서 `Todo`를 사용할 때는 `on~`, `handle~`로 하는데, 그 하위에서는 그것이 지켜지지 않는 것은 조금 부자연스럽다고 느껴지네요.

2021-05-14 16:08 UTC, Kihyun92 commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
맞아요. 네이밍만으로 뭘 하는지 알 수 있어야합니다. on/handle은 실제로 구현된 함수인지 아니면 props로 받아온 이벤트인지를 구분합니다.

App 컴포넌트에서는 우리가 사용할 실제 함수를 `handle prefix`를 붙여서 선언한거고, 자식 컴포넌트로 props로 넘겨줬습니다.
자식 컴포넌트에서는 `on prefix`가 붙은 함수 타입 props를 받아서 해당 이벤트를 실행하거나 또다른 하위 컴포넌트로 넘기게 됩니다.

제 설명이 조금 부족했던 것 같아 잘 번역된 블로그의 글을 첨부해볼게요 :) 참고해보시면 좋을 것 같습니다 🙏🏻
의논이 더 필요한 부분이 있다면 말씀주세요 😊

> `on` 접두사가 붙은 경우, 이 `Prop`에 실제 이벤트가 연결되어 있다는 걸 뜻하고,
`handle` 접두사가 붙은 경우, 이벤트가 발생했을 때 호출되는 `실제 Function`을 의미합니다.

참조:
- https://blog.sonim1.com/220

2021-05-14 23:27 UTC, yujong-lee commented on src/App.jsx
> +      handleDeleteTask={handleDeleteTask}
이해가 되었습니다. `94f7116`로 수정했습니다. 감사합니다.

2021-05-15 14:34 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎㅎ 처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.

과제풀이 영상을 통해서 다시 한 번 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

채널에 회고 남겨주시면 머지하겠습니다~ 😊

2021-05-17 15:29 UTC, merged