2주차 과제2 (To-do 앱 만들기)
CodeSoom/week2-assignment-2 pull request #71
Opened 2021-05-11 06:46 UTC by seong-dodo

안녕하세요. 
과제2도 완성해보았습니다.
코드 리뷰 부탁드립니다 😃

2021-05-11 15:36 UTC, Kihyun92 requested changes
관심사의 분리에 맞게 코드를 작성하는것 대해 감을 잡으신 것 같군요 👍🏼

2021-05-11 15:36 UTC, Kihyun92 commented on src/App.jsx
> +  const [todoList, setTodoList] = useState([]);
상태 관리를 하는 App 컴포넌트의 관점에서 각 변수의 네이밍을 조금 더 명확하게 해보는건 어떨까요? 
예를 들면 description은 입력되는 할일에 대한 값이니까 todo가 될 수 있을 것 같고, currentId는 그냥 id가 될 수 있을 것 같아요~

List의 경우엔 여러 의미로 읽힐 수 있을 것 같아요. 단순히 todos라고만 하는건 어떤가요?

그리고 이 상태들을 하나의 객체로 관리하는건 어떤가요? 🤔

2021-05-11 15:36 UTC, Kihyun92 commented on src/App.jsx
> +  }
`event`는 UI 컴포넌트에서 관리해야 하는 객체입니다. `onChange`는 상태를 변경해주는 함수이기 때문에 UI 레이어와는 전혀 상관이 없어야 합니다.

2021-05-11 15:36 UTC, Kihyun92 commented on src/App.jsx
> +      onDelete={onDelete} />
```suggestion
      handleAdd={onAdd}
      handleChange={onChange}
      handleDelete={onDelete} />
```

위 예시와 같은 네이밍 컨벤션은 어떤가요? 실제 일을 처리하는 관점과 사용하는 입장에서 바라볼 때의 의도를 각각 드러내줄 수 있을 것 같아요.

참고:
- https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-05-11 15:36 UTC, Kihyun92 commented on src/Input.jsx
> +        onChange={(e) => onChange(e)} >
```suggestion
        onChange={onChange} >
```
input의 경우 특정한 파라미터가 없을 경우에 기본 파라미터로 이벤트 객체가 생성되기 때문에 위와 같이 처리해줘도 될 것 같아요.

2021-05-11 15:36 UTC, Kihyun92 commented on src/Input.jsx
> +        onClick={() => onAdd()}>
```suggestion
        onClick={onAdd}>
```

위와 같이 처리해줘도 될 것 같군요.

2021-05-11 15:36 UTC, Kihyun92 commented on src/Page.jsx
> +      }
할일 목록에 대한 예외처리는 TodoList 컴포넌트 내에서 해주는게 좋을 것 같아요~

2021-05-11 15:36 UTC, Kihyun92 commented on src/TodoList.jsx
> +          ))
구조분해할당을 적용해줘도 좋을 것 같네요~

참고:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2021-05-12 12:56 UTC, seong-dodo commented
안녕하세요. 
금일 과제 피드백 수정이 늦어져 상태를 하나의 객체로변경 및 변수명 수정까지 하고 PR올립니다 😢

2021-05-12 14:28 UTC, seong-dodo reviewed
https://github.com/CodeSoom/react-week2-assignment-2/pull/71#discussion_r630281614

안녕하세요. 
`event`가 발생하는 Input컴포넌트에서 관리하도록 바꾸어보았습니다. 말씀하신대로 onChange는 상태 변경함수였네요. 
이렇게 수정했을 때 이점이 무엇인지 궁금합니다.

2021-05-12 14:28 UTC, seong-dodo commented on src/App.jsx
> +  const [todoList, setTodoList] = useState([]);
넵!! 피드백 반영해보겠습니다~~

2021-05-12 14:28 UTC, seong-dodo commented on src/App.jsx
> +      onDelete={onDelete} />
자료 첨부 감사드립니다. 핸들러 함수의 네이밍을 할때 사용하는 입장에서 생각하도록 바꿔보겠습니다 🙏

2021-05-12 16:46 UTC, Kihyun92 requested changes
> [#71 (comment)](https://github.com/CodeSoom/react-week2-assignment-2/pull/71#discussion_r630281614)
> 
> 안녕하세요.
> `event`가 발생하는 Input컴포넌트에서 관리하도록 바꾸어보았습니다. 말씀하신대로 onChange는 상태 변경함수였네요.
> 이렇게 수정했을 때 이점이 무엇인지 궁금합니다.

관심사 측면에서 이점이 있습니다. 
App 컴포넌트의 입장에서는 `onChange` 함수는 단순히 무언가 값을 받아서 현재 상태를 업데이트 하는 역할입니다. `event`가 넘어오고, 그 안의 `target.value`를 `todo` 값으로 업데이트 해야하는 건 알 필요 없는 부분입니다 :)

비슷한 맥락에서 컴포넌트 내의 함수명 또한 해당 컴포넌트 관점에서 네이밍 하는게 더 의도가 드러나겠죠.

2021-05-12 16:46 UTC, Kihyun92 commented on src/App.jsx
> +      handleDelete={onDelete} />
헉 제가 반대로 말씀드렸네요 😱 다시 확인 부탁드립니다 🙇🏻

```suggestion
      onAdd={handleAdd}
      onChange={handleChange}
      onDelete={handleDelete} />
```

2021-05-12 16:46 UTC, Kihyun92 commented on src/App.jsx
> +  const onDelete = (e) => {
이 부분도 event 를 받고 있는 것 같네요~

2021-05-13 15:12 UTC, seong-dodo commented on src/App.jsx
> +      handleDelete={onDelete} />
아항! 답변 감사드립니다 🙏  🙏  🙏

2021-05-14 15:10 UTC, seong-dodo commented
안녕하세요.
피드백 반영 & 인수 테스트 & 린트 확인 모두 완료했습니다. 😃

2021-05-15 14:45 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎㅎ 이번 과제를 하시면서 무엇을 배우셨나요? 더 알고 싶은게 있나요? 한번 정리해보셔도 좋을 것 같습니다 :)

과제풀이 영상을 꼭 보시면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

채널에 회고 남겨주시면 머지하겠습니다~

2021-05-17 15:36 UTC, merged