Home work2 2
CodeSoom/week2-assignment-2 pull request #73
Opened 2021-05-12 15:51 UTC by studioLuda

2-2 과제 제출합니다.

로직 구현 & 컴포넌트 분리 까지 완료하였습니다.

2021-05-12 17:10 UTC, Kihyun92 requested changes
과제 2-1에 남긴 커맨트와 겹치는 부분은 함께 수정해주세요~ 😊

2021-05-12 17:10 UTC, Kihyun92 commented on src/components/inputTodo.jsx
> +/* eslint-disable react/prop-types */
이 룰이 필요한 이유가 있나요?

2021-05-12 17:10 UTC, Kihyun92 commented on src/index.jsx
> +    toDoList: [],
`List`는 보는 사람에 따라 여러 방식으로 생각 될 것 같습니다. `todos` 는 어떤가요?

참고:
- https://javascript.info/array
- https://opentutorials.org/module/1335/8636

2021-05-12 17:10 UTC, Kihyun92 commented on src/index.jsx
> +    const input = document.getElementById('input').value;
DOM에 직접 접근하지 않고 처리할 방법은 없을까요?

2021-05-12 17:10 UTC, Kihyun92 commented on src/components/todoItems.jsx
> +      )}
할 일이 없는 경우에 대해서 삼항 연산자로 처리해보셨군요 :)

`Guard Clauses`를 사용하면 할 일이 없는 경우에 대한 의도를 더욱 드러낼 수 있을 것 같아요~

참고:

https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2021-05-12 17:10 UTC, Kihyun92 commented on src/components/todoItems.jsx
> +        toDoList.map((i) => (
i라는 네이밍은 개발자에겐 익숙하지만 의도를 드러내지 못할 것 같아요. todo는 어떤가요?

혹은 구조분해할당을 사용해도 좋을 것 같군요 :)

2021-05-12 17:10 UTC, Kihyun92 commented on src/components/todoItems.jsx
> +          <li>
key 값 추가가 필요해보입니다!

참고: [https://reactjs.org/docs/lists-and-keys.html](https://reactjs.org/docs/lists-and-keys.html)

2021-05-13 07:55 UTC, studioLuda commented on src/components/inputTodo.jsx
> +/* eslint-disable react/prop-types */
PropTypes를 설정하면서, 이제 필요하지 않게 되었습니다! ^^ 감사합니다!

2021-05-13 08:01 UTC, studioLuda commented on src/index.jsx
> +    toDoList: [],
그렇네요.  list 자료형을 떠올리게 할 수 있을 것 같아요. :) 
링크 주신내용 꼼꼼히 완독하겠습니다! 
언어별로 지원하는 자료구조와 array, list, arrayList 차이들 정리되어서 너무 좋아요! 
알려주셔서 감사합니다!! 😄

2021-05-13 08:06 UTC, studioLuda commented on src/index.jsx
> +    const input = document.getElementById('input').value;
input 의 value를  toDoList와 같이 useState에서 관리할 수 있을 것 같아요.
다만 <input > 란에 입력된 value를 어떻게 얻어올지는 조금더 고민하고 공부해보겠습니다!! 

<input>태그에 대해 찾아보려고 하고있어요.
예전에 웹 구현을 했을 때, onChange를 사용했던적이 있는데..
<input>에 입력이 있을 때마다 rendering해주고 그 값을 useState통해 저장할 수 있을 것 같아요.
(다만 그 방법이 좋은걸까? 의심이 들기는 합니다!)

------------------
정리 하자면

1. input tag에 대해서 더 알아본다.
2. onChange를 구현해서 해결이 되는지 확인한다.
3. 만약 2번이 가능하다면, 성능상 무엇이 나을지 찾아본다. (성능 테스트를 알아보는 것도 방법일듯)

2021-05-13 08:08 UTC, studioLuda commented on src/components/todoItems.jsx
> +      )}
더 읽기도 쉬워질 것 같아요! 감사합니다 바로 적용하겠습니다!

2021-05-13 12:03 UTC, studioLuda commented on src/components/todoItems.jsx
> +        toDoList.map((i) => (
우선 todo로 고치겠습니다 ! 

구조분해할당을 사용해서 todo 목록을 그리는 것은 바로 생각이 안나서..
일단 책 <자바스크립트 코딩의 기술 29장 해체 할당으로 객체 속성에 접근하라> 읽어보고 새로운 버전 커밋 드리겠습니다!

2021-05-13 12:03 UTC, studioLuda commented on src/components/todoItems.jsx
> +          <li>
넵! 바로 수정하겠습니다! 다음번에는 key값 꼭 넣겠습니다!

2021-05-13 12:22 UTC, studioLuda commented
안녕하세요 ! 

피드백 내용을 참고삼아 간단히 리팩토링을 진행하였습니다. 

피드백 주신 내용중 아래 2가지 내일 오전에 추가로 공부 및 코딩하여 커밋드리려 합니다.

1)  _DOM에 직접 접근하지 않고 처리할 방법은 없을까요?_

2)  _i라는 네이밍은 개발자에겐 익숙하지만 의도를 드러내지 못할 것 같아요. todo는 어떤가요?
혹은 구조분해할당을 사용해도 좋을 것 같군요 :)_


----------------------------------------

1)번에 대해서는 여러 생각이 들어 바로 밑에 코멘트를 추가 했습니다. 
수행 계획만 요약 드리자면 아래와 같습니다.

```
1. input tag에 대해서 더 알아본다.
2. onChange를 구현해서 해결이 되는지 확인한다.
3. 만약 2번이 가능하다면, 성능상 무엇이 나을지 찾아본다. (성능 테스트를 알아보는 것도 방법일듯)
```

2)번에 대해서는 해당 코드 부분에 "구조 할당 분해"를 어떻게 활용할지 아이디어가 떠오르지 않아서
일단 공부를 하고 다시 코드를 보기로 하였습니다.

` 읽을 책 : <자바스크립트 코딩의 기술>  29장 - 해체 할당으로 객체 속성에 접근하라`

오늘 남은 시간동안에는 책읽고, 일일 회고 정리하려 합니다.
항상 감사합니다.
좋은 밤 되세요!  🌙  🙏

2021-05-13 15:18 UTC, Kihyun92 requested changes
리뷰 드리는것보다 항상 더 많이 고민하시는 것 같아 좋습니다 👍🏼 

진행하시다가 궁금한점이나 의논이 필요하다면 커맨트를 남겨주시거나 슬랙채널 혹은 DM으로 편하게 말씀주세요~ 😊

2021-05-13 15:18 UTC, Kihyun92 commented on src/components/todoItems.jsx
> +  );
```suggestion
  if (toDos.length <= 0) {
    return <p>할 일이 없어요!</p>;
  }

  return (
    <ol type="1">
      {toDos.map((todo) => (
        <li>
          {todo}
          <button type="button" key={todo} onClick={() => { onClick(todo); }}>
            완료
          </button>
        </li>
      ))
      }
    </ol>
  );
```

할 일이 없는 경우에 대해서 잘 분리해주셨네요👍🏼  다만 함수로 한번 더 감싸서 처리하는 것 보다 위와 같이 처리하는건 어떨까요?

2021-05-14 11:11 UTC, studioLuda commented
ToDo List의 Input 값을 얻어오는 방식을 변경해 보았습니다.
기존 방식 : input 태그의 getElementByID.value로 값 얻기. 
변경된 방식 : input 태그의 onChanged를 구현해서 값이 변경될때마다 상태값도 업데이트 해주고있습니다. 

아래 첨부된 이미지는 두 방식의 테스트 코드 실행시간을 비교한 내용입니다.

기존방식(좌) vs 변경된 방식(우) 

<img src ="https://github.com/studioLuda/react-week2-assignment-2/blob/homeWork2-2/test/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%20%EC%84%B8%EB%B2%88%EC%A7%B8%20%EC%84%B1%EB%8A%A5%EB%B9%84%EA%B5%90%20%ED%85%8C%EC%8A%A4%ED%8A%B8.png?raw=true">

3차례 정도 테스트 해보았는데
큰 차이는 없지만, 미세하게 elementByID값이 조금 더 빠른것 같습니다. 

(이렇게 테스트 하는게 정확하진 않은 것 같지만 일단 기록으로 남겨봅니다!) 

-----------------------------

뭔가 제가 놓친게 아닐까 생각이 듭니다. (구현 방법이든, input tag 속성에 대한 이해든)

그리고 검색하면서 input 과 submit 버튼을 가지고 get/post 방식으로 파라미터를 서버에 넘기는 방법도 있었습니다. 
(아주 옛날에 웹사이트 공부할 때 해봤었는데 다 까먹었네요.. )
어쨌거나 다른 아이디어로는 get/post를 이용해서 input 값을 보내고 불러오는 방식도 가능은 할 것 같아 보였습니다.

(가령 get이라면 파라미터 값으로 input값을 받아올 수는 있을 것 같아요. )


아직 리액트나 자바스크립트가 익숙하지 않고, 조각조각 알던 것들이 뒤죽박죽이라..
일단 공부 계속해 나가겠습니다!  급한 궁금증 생기면 DM 드리겠습니다! 

감사합니다 😄

2021-05-14 12:54 UTC, studioLuda commented
https://github.com/CodeSoom/react-week2-assignment-2/pull/73#discussion_r631235168  

위에 코멘트 주신 내용처럼, 
toDo 목록을 생성하는 코드에서, 구조 분해 할당을 이용하는 방법을 생각해 보았습니다. 


for문을 통해 list의 item을 하나씩 꺼내는 방법을 생각해 봤습니다.

```
function testToDos() {
    // eslint-disable-next-line no-restricted-syntax
    for (const todo of toDos) {
      return (
        <li>
          {todo}
          <button
            type="button"
            key={todo}
            onClick={() => {
              onClick(todo);
            }}
          >
            완료
          </button>
        </li>
      );
    }
  }
```

생각과 달리 코드를 실행 시키는데는 오류나 제약이 있어 
왜그런지 알아보아야 할것 같아요~

진행중에 이런 접근이 맞는지 궁금해서 여쭤봅니다!

2021-05-14 15:52 UTC, studioLuda commented
질문 보류합니다 ! 요 사이에 책을 읽었는데 공부한 내용으로  내일 다시코드구현 다시 도전해볼께요! :)

2021-05-14 15:55 UTC, Kihyun92 commented
직접 성능 테스트를 해보셨군요! 👍🏼 👍🏼 

테스트 해보신것 처럼 자바스크립트 코드의 실행 속도도 중요하지만, 프론트 엔드에서의 성능 테스트는 조금 더 복합적입니다.

실제 웹페이지에 그려지는 과정을 고려해야하죠. 번들 크기, 실행 속도, reflow, repaint 여부 등등이 있습니다. 지금 다루기엔 굉장히 분량이 많기 때문에 천천히 알아가보셔도 좋겠네요 :) 중요한건 성능에 대한 고려를 해본거니까요.

`DOM`을 직접 조작하는 것의 장단점이 무엇인지를 알고, 최근의 프론트엔드 프레임워크들은 왜 `Virtual DOM`을 도입했는지를 고민해보시면 좋을 것 같아요~

참고: 
- https://velopert.com/3236
- https://code-masterjung.tistory.com/33

2021-05-14 15:56 UTC, Kihyun92 commented
> 질문 보류합니다 ! 요 사이에 책을 읽었는데 공부한 내용으로 내일 다시코드구현 다시 도전해볼께요! :)

넵, 기다리고 있겠습니다 :)

2021-05-15 13:52 UTC, studioLuda commented
안녕하세요 기현님 ! 

이전에 코멘트 주셨던 -> 
https://github.com/CodeSoom/react-week2-assignment-2/pull/73#discussion_r631235168
에 대해서 업데이트를 하였습니다.

위와같이 결과가 나온 과정을 간단히 공유 드립니다.

---------------
공부한 자료 

[구조분해 할당](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)과 
<책 자바스크립트의 기술> Tip 29 : 해체 할당으로 객체 속성에 접근하라 (p210~) 입니다. 
 

제가 구현한 toDos는 String으로 구성된 Array입니다. 
` toDos = ["할일 1", "할일 2"]`

1) 처음에는 배열의 구조 분해만 공부하고 활용해보려 했는데 답이 잘 나오지 않았습니다. 

2) 책을 읽고 props 객체를 여러 방법으로 재할당 하는 것을 알게 되었고 , 위와 같은 방법으로 코드를 리팩토링 하였습니다. 

3) 그리고 아래 링크첨부한  

- 객체의 구조 분해할당 :  기본값 갖는 새로운 이름의 변수에 할당하기 - 를  
시도 하였으나, 실패하였습니다.  

 [구조분해할당 - 새로운 변수 이름으로 할당하기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%EC%83%88%EB%A1%9C%EC%9A%B4_%EB%B3%80%EC%88%98_%EC%9D%B4%EB%A6%84%EC%9C%BC%EB%A1%9C_%ED%95%A0%EB%8B%B9%ED%95%98%EA%B8%B0)


예제코드 

```
var {a: aa = 10, b: bb = 5} = {a: 3};

console.log(aa); // 3
console.log(bb); // 5
```

시도한 코드 샘플 

```
function ToDoListView({
  onClick,
  toDos : toDoListView 
} = { toDos : <ol> {this.props.toDos.map( ... )} </ol>}) {
  return toDoListView;
}
```

2021-05-15 15:12 UTC, Kihyun92 commented
다시 확인해보니 todos를 객체가 아닌 배열로 구현하셔서 구조분해할당을 적용하기는 쉽지 않으셨을 것 같아요 😭
적절하지 못한 리뷰 남긴점 죄송합니다 🙇🏻 꼼꼼하게 확인하지 못했네요

작업하신 부분은 [이전 코드](https://github.com/CodeSoom/react-week2-assignment-2/pull/73#discussion_r631886203)와 같이 진행하는게 좋을 것 같습니다.

2021-05-16 11:18 UTC, studioLuda commented
안녕하세요 기현 트레이너님! 
과제 풀이 시청후 리팩토링을 진행하였습니다.

크게 3가지를 반영 하였습니다.

1) toDo를 string이 아니라 object 로 변경하였습니다. 
현재 기능 충족은 string으로도 가능하지만,  
코딩 훈련에도 도움이되고, 
나중에 기능이나 정보가 추가 될 수 있기 때문에 object가 더 좋다고 판단하였습니다. 

2)  1)번의 수정에 따라, toDo 객체에 id 값을 추가하였고, id값 부여하는 로직을 추가하였습니다.

3) 기존의 ToDoListView 컴포넌트를 한번더 쪼개어  ToDoItem 컴포넌트를 빼냈습니다. 

이상입니다 ! 😄

2021-05-16 13:31 UTC, Kihyun92 requested changes
이번주도 고생하셨습니다 ㅎㅎ 슬랙 채널에 회고 남겨주세요 :)

2021-05-16 13:31 UTC, Kihyun92 commented on src/App.jsx
> +  const { toDos, inputValue, newIdIndex } = state;
`newIdIndex`에선 id와 index 는 비슷한 의미인 것 같아요. `newId` 라고만 하는건 어떤가요?

2021-05-16 13:31 UTC, Kihyun92 commented on src/components/ToDoListView.jsx
> +  return createToDoListView();
한번 더 함수로 추상화 해줄 필요는 없을 것 같아요~

2021-05-16 13:31 UTC, Kihyun92 commented on src/components/ToDoListView.jsx
> +        {toDos.map((todo) => (<ToDoItem todo={todo} onClick={onClick} />))}
key 값 추가는 이곳에 해주는게 좋을 것 같아요.

참고:
- https://ko.reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

2021-05-16 16:15 UTC, studioLuda commented on src/App.jsx
> +  const { toDos, inputValue, newIdIndex } = state;
네! 말씀듣고 다시보니  id가 index가 아닌데, index처럼 생각했던것 같아요!! 
수정하겠습니다!

2021-05-16 16:17 UTC, studioLuda commented on src/components/ToDoListView.jsx
> +  return createToDoListView();
네! 그렇네요. 기존 함수를 의미없이 남겨놓은 것 같아요!!  변경하고 다시 읽어보는 습관을 길러볼께요!

2021-05-16 16:19 UTC, studioLuda commented on src/components/ToDoListView.jsx
> +        {toDos.map((todo) => (<ToDoItem todo={todo} onClick={onClick} />))}
네 수정하겠습니다! 내일 아침에 맑은 정신으로 링크 읽고, map 잘 이해하겠습니다!!

2021-05-16 17:39 UTC, studioLuda commented
피드백 반영하였습니다!

https://github.com/CodeSoom/react-week2-assignment-2/pull/73#discussion_r633090025 
 변수명 변경 newIdIndex ->` lastId` 로 바꾸어보았습니다. 
(새로운 todo가 추가될 때, 새로운 아이디값 생성시 참고해야할 마지막 ID값이다 란 의미로 적어보았어요 ! )



https://github.com/CodeSoom/react-week2-assignment-2/pull/73#discussion_r633091339
  의미없는 추상화 제거 ( createToDoListView() 함수 제거)

https://github.com/CodeSoom/react-week2-assignment-2/pull/73#discussion_r633091568
map으로 컴포넌트를 반복하여 그릴 때, 해당 컴포넌트에 key 부여하기.

2021-05-17 15:35 UTC, Kihyun92 commented
테스트가 실패하는 것 같아요~ 한번 확인 부탁드립니다😊

수정되면 머지하도록 하겠습니다 :)

2021-05-22 05:24 UTC, studioLuda commented
안녕하세요! 제가 확인이 늦었습니다. 

린트 오류 수정되었고, 테스트는 모두 통과하였습니다. 

만약 오류가 또 난다면
중간에 파일명을 변경하였는데 (스펠링은 같고, 소문자를 대문자로만 수정) 
그 오류인가 의심이 되네요.  

해결방법 찾아보겠습니다. 
한번 확인 부탁드려요.

2021-05-23 12:43 UTC, studioLuda commented
오류 해결되었습니다!

2021-08-08 07:47 UTC, merged