Implement todo app
CodeSoom/week2-assignment-2 pull request #9
Opened 2020-06-10 14:46 UTC by naraekn

Submit assignment2-2 as the first try

2020-06-10 23:06 UTC, wholemann requested changes
금방 잘해주셨네요.
아마 AddForm 부분을 만드시면서 이렇게 하는게 맞을까란 의문이 있으셨을 겁니다.
스스로 '뭔가 이상하다'를 느낀다면 보통은 그 예감이 맞습니다^^;

몇 가지 개선할 부분이 있으니 그 부분 고민해보시면 좋겠습니다.
comment를 참고하시고 질문 있으시면 DM 부탁드려요:)

2020-06-10 23:06 UTC, wholemann commented on src/App.jsx
> +  const [state, setState] = useState([]);
state가 1개일까요?

2020-06-10 23:06 UTC, wholemann commented on src/AddForm.jsx
> +    document.getElementById('add-todo').value = null;
input의 입력값 또한 상태로 바라보는 건 어떨까요?
DOM을 직접 조작하지 않기 위해 사용하는 게 리액트입니다:)

마지막 강의를 보면 아시겠지만 상태에 대한 관리는 어디에서 하나요?

2020-06-10 23:06 UTC, wholemann commented on src/App.jsx
> +      todo={state}
todo가 아닌 복수 형태로 표현해주는 게 좋을 듯 하네요.

2020-06-10 23:06 UTC, wholemann commented on src/Page.jsx
> +              todo={t}
t와 같은 표현보단 좀 더 명확한 게 좋습니다.

- 제약사항 : 줄여쓰지 않기

2020-06-10 23:06 UTC, wholemann commented on src/Page.jsx
> +        todo.length
조건식은 명확한 게 좋습니다.

2020-06-10 23:06 UTC, wholemann commented on src/App.jsx
> +    setState(state.filter((t) => t !== completeTodo));
만약 같은 제목을 가진 todo가 2개 이상이라면 어떻게 될까요?

2020-06-11 02:59 UTC, naraekn commented on src/App.jsx
> +  const [state, setState] = useState([]);
들켰네요ㅎㅎㅎㅎ(돌아가긴 돌아가는데 뭔가 이상하다고 생각했습니다..) 우선 테스트를 통과하는 코드를 빨리 만들어보자!!라는 목표로 우선은 빠르게 만들어보고 푸시했습니다 오늘 피드백 받은 내용 바탕으로, 오늘 다시 고민해보겠습니다!! :)

2020-06-12 17:21 UTC, naraekn commented on src/Page.jsx
> +              todo={t}
넵! todo 묶음들은 'todos'로, todo 하나하나는 'todo'로 통일했습니다.

2020-06-12 17:29 UTC, naraekn commented on src/App.jsx
> +    setState(state.filter((t) => t !== completeTodo));
id라는 새로운 state을 만들어서 문제를 해결해봤습니다. 어떻게 각 todo의 unique한 id값을 만들까 고민하다가, 할 일을 추가한 '시간'이 각 todo의 id로 적당하겠다는 생각이 들었습니다.

2020-06-12 17:29 UTC, naraekn commented on src/Page.jsx
> +        todo.length
```haveTodo```라는 arrow function을 만들었습니다.

2020-06-12 17:30 UTC, naraekn commented on src/App.jsx
> +  const [state, setState] = useState([]);
state가 하나로 해결이 안됐네요!! 새로 제출한 코드에서는, 3개의 state을 가지도록 바꿔봤습니다.

2020-06-12 17:33 UTC, naraekn commented on src/AddForm.jsx
> +    document.getElementById('add-todo').value = null;
<App />에서 상태를 관리했습니다. App에서 상태를 관리하고 싶었는데, 목요일에는 방법을 찾지를 못했네요ㅎㅎㅎ

강의에서 첨부해주신 react official document을 여러번 읽어보고 (아직도 이해를 해나가는 중이지만), 다른 방법을 적용해봤습니다. 새로 제출한 코드에서는 App 에서 상태 관리를 합니다!

2020-06-12 17:48 UTC, naraekn commented
멘토님 과제를 하면서 궁금한 점이 있었습니다!

1주차에 ``` let```을 ```const```로 바꾸는 과정에서, 멘토님께서 '참조투명성'에 대한 이야기를 해주셨어요. 

(그 때 들은 내용을 제가 이해한대로 써보자면,)
저희가 const를 쓰는 이유는 외부의 상태를 변경하지 않는, 즉 참조투명성을 지키는 함수를 만들기 위함입니다. 참조 투명성을 지키는 함수는, 외부의 영향을 받지 않기 떄문에 동일한 인자에 대하여 항상 같은 값을 반환하고, 이렇게 '일관성(?)있는 함수가 되어야 '테스트 코드'를 작성할 수 있는 구조가 된다고 이해를 했어요.

그런데, 이번주 과제들을 곰곰이 생각해보니, 제가 ```App```에서 정의한 함수들은 '참조투명성'을 지키지 않는다는 생각이 들었습니다. 예를 들어, 아래 코드에서 ```handleSubmit``` 함수에서는 외부에 있는 ```todos```, ```ids```등을 참조하죠.

```javascript
const { ids, todos, newTodo } = state;

function handleSubmit(event) {
    setState({
      ids: [...ids, generateId()],
      todos: [...todos, newTodo],
      newTodo: '',
    });
    event.preventDefault();
  }
```

그래서, 제가 궁금한 점은,
1. ```setState```을 사용하는 함수는 참조투명성을 지키는가? ('안지킨다!'가 맞는 답인가?)
2. 그렇다면, 위와 같은 함수들은 테스트 가능한가?

이 두가지가 궁금했습니다:)

2020-06-13 00:19 UTC, wholemann requested changes

2020-06-13 00:19 UTC, wholemann commented on src/App.jsx
> +      todos: todos.filter((_, index) => index !== ids.indexOf(completedId)),
현재는 id와 todo가 따로 놀기 때문에 todo를 삭제할 때 filter를 두번 사용하는 일이 벌어지고 있습니다.
또한 Todos 컴포넌트의 불필요한 처리가 늘어나는 걸 볼 수 있죠.

filter 연산 한 번에 삭제가 이뤄지도록 하려면 어떤 개선을 해야할까요?
id는 무엇을 식별하기 위한 것인지 잊지 말아야 합니다:)

2020-06-13 00:19 UTC, wholemann commented on src/App.jsx
> +    />
todos를 Page 내부에서 Todo 컴포넌트 이외의 컴포넌트에서 사용한다면 현재와 같은 표현은 어떤 오해를 불러일으킬 수 있을까요?
또 다른 컴포넌트가 있다면 어떤 중복이 발생할까요?

2020-06-13 00:19 UTC, wholemann commented on src/Page.jsx
> +        haveToDo(todos)
isNotEmpty(todos)가 더 자연스럽게 읽힐 듯 하네요.

전달하는 인자와 함께 봤을 때 맥락이 자연스러운 문장을 추구해야 합니다.

2020-06-13 00:19 UTC, wholemann commented on src/Page.jsx
> +  const { ids, todos, handleClickComplete } = todoState;
Page에 props를 전달하는 부분에서 구조분해 할당을 하면 이 부분을 없앨 수 있겠죠?

2020-06-13 11:02 UTC, wholemann approved these changes
이번 과제는 Merge하겠습니다. 정말 잘해주셨습니다.
고민의 흔적들을 정말 많이 느낄 수 있었고,
오히려 질문 주신 부분에서 제가 배운 부분이 많네요. 감사합니다.

아마 이번에 진행하시면서 많은 부분을 배우셨을 거라 봅니다.
앞으로도 늘 '왜?'를 질문하고 실험하며 고민을 계속 하시다 보면 정말 실력이 쑥쑥 늘어나실 겁니다.

앞으로도 기대하고 있겠습니다ㅎㅎ

p.s. 한 가지 아쉬운 부분만 comment 남겨드렸으니 이후 과제에 참고하시면 좋겠네요.

2020-06-13 11:02 UTC, wholemann commented on src/App.jsx
>    const generateId = () => Date.now().toString();
고유한 값을 생성하는 이 아이디어는 정말 좋군요ㅎㅎ

2020-06-13 11:02 UTC, wholemann commented on src/App.jsx
>      event.preventDefault();
이 부분은 함수 맨 첫 줄에 있는 게 좋겠습니다ㅎㅎ

2020-06-13 11:02 UTC, wholemann commented on src/App.jsx
> +      todos: [...todos, { id: newId, content: newTodo }],
피드백을 훌륭하게 반영해주셨군요👍

2020-06-13 11:02 UTC, wholemann commented on src/App.jsx
> +      newTodo: '',
filter 한번으로 해결했군요!

2020-06-13 11:02 UTC, wholemann commented on src/Page.jsx
> +        isNotEmpty(todos)
훨씬 의미가 자연스럽죠?

2020-06-13 11:05 UTC, merged

2020-06-13 11:32 UTC, naraekn commented on src/App.jsx
>      event.preventDefault();
앗 그렇군요 참고하겠습니다 :)

2020-06-13 11:34 UTC, naraekn commented
과제 통과될 때는 언제나 행복하네요ㅎㅎㅎ 감사합니다 멘토님! :)